<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><!--[if IE 7 ]>    <html class="ie7 oldie" lang="pl"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8 oldie" lang="pl"> <![endif]-->
<!--[if IE ]>    <html class="ie" lang="pl"> <![endif]-->
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<html lang="pl">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        Witaj!!!<br/>
        Przesyłamy kod rabatowy, który możesz wykorzystać w naszym sklepie:
        <div style="border: 1px solid #B8B8B6; width: 300px; margin: 0 auto; border-radius: 5px; padding: 10px; margin-top: 40px; text-align: center;">
            <div style="font-size: 30px;"><?php echo $this->coupon->getCode(); ?></div>
        </div>

    </body>
</html>