<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <a class="prev" href="<?php echo $this->url(array('page' => $this->previous), 'domain-i18n:last-news-page'); ?>?<?php echo http_build_query(array('count' => $this->count, 'sorted' => true)) ?>"><span>&laquo;</span></a>
<?php endif; ?>
     
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url(array('page' => $page), 'domain-i18n:last-news-page') ?>?<?php echo http_build_query(array('count' => $this->count, 'sorted' => true)) ?>"></a>
    <?php else: ?>
        <a class="active" href="#"><?php echo $page; ?></a> <?php echo $this->translate('of'); ?> <?php echo $this->pageCount; ?>
    <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <a class="next" href="<?php echo $this->url(array('page' => $this->next), 'domain-i18n:last-news-page'); ?>?<?php echo http_build_query(array('count' => $this->count, 'sorted' => true)) ?>"><span>&raquo;</span></a>
<?php endif; ?>

