<?php

/**
 * Media_Model_Doctrine_Attachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Media
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media_Model_Doctrine_Attachment extends Media_Model_Doctrine_BaseAttachment
{
     public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setOffset($offset) {
        $this->_set('offset', $offset);
    }
    
    public function getOffset() {
        return $this->_get('offset');
    }
    
    public function setFilename($filename) {
        $this->_set('filename', $filename);
    }
    
    public function getFilename() {
        return $this->_get('filename');
    }
    
    public function setExtension($extension) {
        $this->_set('extension', $extension);
    }
    
    public function getExtension() {
        return $this->_get('extension');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
}   