<?php

/**
 * Media_Model_Doctrine_AttachmentTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Media_Model_Doctrine_AttachmentTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Media_Model_Doctrine_AttachmentTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Media_Model_Doctrine_AttachmentTranslation');
    }
}