<?php

/**
 * Media_Model_Doctrine_AttachmentTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Media
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media_Model_Doctrine_AttachmentTranslation extends Media_Model_Doctrine_BaseAttachmentTranslation
{

}