<?php

/**
 * Media_Model_Doctrine_Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Media
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media_Model_Doctrine_Photo extends Media_Model_Doctrine_BasePhoto
{
     public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setFilename($filename) {
        $this->_set('filename', $filename);
    }
    
    public function getFilename() {
        return $this->_get('filename');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function setCropData($cropData) {
        $this->_set('crop_data', $cropData);
    } 
    
    public function getCropData() {
        return $this->_get('crop_data');
    }
    
    public function setOffset($offset) {
        $this->_set('offset', $offset);
    }
    
    public function getOffset() {
        return $this->_get('offset');
    }
}