<?php

/**
 * Media_Model_Doctrine_PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Media_Model_Doctrine_PhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Media_Model_Doctrine_PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Media_Model_Doctrine_Photo');
    }
}