<?php

/**
 * Media_Model_Doctrine_VideoUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Media
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media_Model_Doctrine_VideoUrl extends Media_Model_Doctrine_BaseVideoUrl
{
     
    
    public static $videoPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '1078x380' => "Main photo"
    );
   
    
    public static function getVideoPhotoDimensions() {
        return self::$videoPhotoDimensions;
    } 
    
     public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setOffset($offset) {
        $this->_set('offset', $offset);
    }
    
    public function getOffset() {
        return $this->_get('offset');
    }
    
    public function setFilename($filename) {
        $this->_set('filename', $filename);
    }
    
    public function getFilename() {
        return $this->_get('filename');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
     public function setUp() {
//        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
//            'local' => 'photo_root_id',
//            'foreign' => 'id'
//        ));
        
//        $this->hasOne('Banner_Model_Doctrine_Ad as Ad', array(
//            'local' => 'ad_id',
//            'foreign' => 'id'
//        ));
        
        parent::setUp();
    }
}