<script>
    /* <![CDATA[ */
//    // NEWSLETTER FORM AJAX SUBMIT
//    $('.newsletter .submit').on('click', function(event){
//        event.preventDefault();
//        var email = $('.email').val();
//        var form_data = new Array({ 'Email' : email});
//        $.ajax({
//            type: 'POST',
//            url: "contact.php",
//            data: ({'action': 'newsletter', 'form_data' : form_data})
//        }).done(function(data) {
//            alert(data);
//        });
//    });

    // REVOLUTION SLIDER 
    var api;
    jQuery(document).ready(function() {

//        if (jQuery.fn.cssOriginal !== undefined)   // CHECK IF fn.css already extended
//            jQuery.fn.css = jQuery.fn.cssOriginal;

        api = jQuery('.banner').revolution(
                {
                    delay: 4000,
                    startheight: 320,
                    startwidth: 980,
                    
                    hideThumbs: 200,
                    
                    thumbWidth: 100,
                    thumbHeight: 50,
                    thumbAmount: 5,
                    
                    navigationType: "none",
                    navigationArrows: "verticalcentered",
                    
                    navigationStyle: "round-old",
                    
                    navigationHAlign: "right",
                    navigationVAlign: "top",
                    navigationHOffset: 0,
                    navigationVOffset: 20,

                    soloArrowLeftHalign: "left",
                    soloArrowLeftValign: "center",
                    soloArrowLeftHOffset: 20,
                    soloArrowLeftVOffset: 0,
                    
                    soloArrowRightHalign: "right",
                    soloArrowRightValign: "center",
                    soloArrowRightHOffset: 20,
                    soloArrowRightVOffset: 0,

                    touchenabled: "on",
                    onHoverStop: "on",
                    
//                    navOffsetHorizontal: 0,
//                    navOffsetVertical: 20,
//                    hideCaptionAtLimit: 0,
//                    hideAllCaptionAtLilmit: 0,
//                    hideSliderAtLimit: 0,
                    stopAtSlide: -1,
                    stopAfterLoops: -1,
                    
                    shadow: 0,
                    fullWidth: "off"

                });


                //google maps
//                var yourStartLatLng = new google.maps.LatLng(50.001542, 19.905783);
//                $('.map_canvas').gmap({'center': yourStartLatLng, 'zoom': 15, 'disableDefaultUI': true, 'callback': function() {
//                        var self = this;
//                        self.addMarker({'position': this.get('map').getCenter()});
//                }});
            
            // PORTFOLIO CAROUSEL
            $("#foo2").carouFredSel({
                auto: true,
                scroll: 1,
                pagination: "#foo2_pag",
                swipe: {
                    ontouch: true,
                    onMouse: true
                },
                width: 'variable',
                height: 'variable',
                items:{
                    width: 'auto',
                    visible: 3
                }
            });
            $('#gototop').click(function(){
                $('html, body').animate({ scrollTop: 0 }, 1000);
                return false;
             });
    });
</script>
<div class="banner-container">
    <div class="banner">
        <ul>
            <?php foreach($this->slider['Slides'] as $slide): ?>
            <?php if($slide['level'] == 0) continue; ?>
            <li data-transition="<?php echo $slide['animation'] ?>" data-slotamount="7">
                <img src="/media/photos/<?php echo $slide['PhotoRoot']['offset'] ?>/980x320/<?php echo $slide['PhotoRoot']['filename'] ?>" alt="Slider background">
                <?php if($slide['title'] != ''): ?>
                <div class="caption sfl caption-heading" data-x="<?php echo $slide['title_pos_x'] ?>" data-y="<?php echo $slide['title_pos_y'] ?>" data-speed="700" data-start="1200" style="color: <?php echo $slide['title_color'] ?>; font-size: <?php echo $slide['title_size'] ?>px;" ><?php echo $slide['title'] ?></div>
                <?php endif; ?>
                <?php if($slide['description'] != ''): ?>
                <div class="caption sft caption-subtitle" data-x="<?php echo $slide['description_pos_x'] ?>" data-y="<?php echo $slide['description_pos_y'] ?>" data-speed="700" data-start="1900" style="color: <?php echo $slide['description_color'] ?>; font-size: <?php echo $slide['description_size'] ?>px; background-color: <?php echo $slide['description_bg_color'] ?>;" ><?php echo $slide['description'] ?></div>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>