<?php

/**
 * Page_Model_Doctrine_PageShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Page_Model_Doctrine_PageShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Page_Model_Doctrine_PageShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Page_Model_Doctrine_PageShop');
    }
    
    public function getFullPageQuery() {
        $q = $this->createQuery('p')
                ->addSelect('p.*')
                ->addSelect('t.*')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->leftJoin('p.Translation t')
                ->leftJoin('p.Metatag m')
                ->leftJoin('m.Translation mt');
        return $q;
    }
}