<?php

/**
 * Page_Model_Doctrine_PageShopTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Page
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page_Model_Doctrine_PageShopTranslation extends Page_Model_Doctrine_BasePageShopTranslation
{

}