<?php

/**
 * Page_Model_Doctrine_PageTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Page_Model_Doctrine_PageTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Page_Model_Doctrine_PageTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Page_Model_Doctrine_PageTranslation');
    }
}