<?php
  // Remember to copy files from the SDK's src/ directory to a
  // directory in your application on the server, such as php-sdk/
  require_once('php-sdk/facebook.php');

  $config = array(
    'appId' => '530955950330860',
    'secret' => '72762b999910f157d08bcf8f72e830bf',
    'allowSignedRequest' => false // optional but should be set to false for non-canvas apps
  );
  $facebook = new Facebook($config);
 // $user_id = $facebook->getUser();
?>
<html>
  <head></head>
  <body>

  <?php

    //if($user_id) {

      // We have a user ID, so probably a logged in user.
      // If not, we'll get an exception, which we handle below.
      try {
        $ret_obj = $facebook->api('/100001809171702/feed', 'POST',
                                    array(
                                      'link' => 'www.example.com',
                                      'message' => 'Posting with the PHP SDK!'
                                 ));
        echo '<pre>Post ID: ' . $ret_obj['id'] . '</pre>';

        // Give the user a logout link 
        echo '<br /><a href="' . $facebook->getLogoutUrl() . '">logout</a>';
      } catch(FacebookApiException $e) {
          var_dump($e->getMessage());exit;
        // If the user is logged out, you can have a 
        // user ID even though the access token is invalid.
        // In this case, we'll get an exception, so we'll
        // just ask the user to login again here.
        $login_url = $facebook->getLoginUrl( array(
                       'scope' => 'publish_stream'
                       )); 
        echo 'Please <a href="' . $login_url . '">login.</a>';
        error_log($e->getType());
        error_log($e->getMessage());
      }   
//    } else {
//
//      // No user, so print a link for the user to login
//      // To post to a user's wall, we need publish_stream permission
//      // We'll use the current URL as the redirect_uri, so we don't
//      // need to specify it here.
//      $login_url = $facebook->getLoginUrl( array( 'scope' => 'publish_stream' ) );
//      echo 'Please <a href="' . $login_url . '">login.</a>';
//
//    } 

  ?>      

  </body> 
</html>  