<div class="widget">
        <h3>NAJNOWSZE INFORMACJE</h3>
        <div class="article-block">
            <?php foreach($this->lastNewsSidebar as $news): ?>
                <div class="item">
                        <div class="item-header">
                                <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" class="image-hover">
                                    <img src="/media/photos/<?php echo $news['PhotoRoot']['offset'];?>/74x74/<?php echo $news['PhotoRoot']['filename'];?>" alt="No photo">
                                </a>
                        </div>
                        <div class="item-content">
                                <div class="content-category">
                    <?php if($news['Category']['slug']): ?>
                                        <a href="<?php echo $this->url(array('slug' => $news['Category']['slug']),'domain-news-category'); ?>" class="cat-<?php echo $news['Category']['slug']; ?>-title"><?php echo $news['Category']['title']; ?></a>
                   <?php endif; ?>
                                </div>
                                <span><?php echo MF_Text::timeFormat($news['publish_date'], 'Y-m-d H:i'); ?></span>
                                <h4><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a></h4>
                                
                        </div>
                </div>
            <?php endforeach; ?>
                
                
        </div>
</div>
