<div class="main-title cat-<?php echo $this->group['slug']; ?>-main-title">
        <h2>Studencka twórczość</h2>
        <span>Wszystkie wpisy z grupy</span>
</div>

<div class="archive-blocks">
        <?php foreach($this->newsList as $key => $news): ?>
            <div class="archive-single">
                <hr class="cat-<?php echo $news['Category']['slug']; ?>-hr" />
                <div class="article-list">

                        <div class="item">
                            <?php if($key<3): ?>
                                <div class="item-header">
                                        <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" class="image-hover" data-path-hover="M 34,56 45,34 63,41 64,66 47,76 z">
                                                <figure>
                                                        <img src="/media/photos/<?php echo $news['PhotoRoot']['offset']; ?>/265x181/<?php echo $news['PhotoRoot']['filename']; ?>" />
                                                         <?php if(strlen($news['VideoRoot']['url'])): ?>
                                                                <img class="playBtn" src="/images/icon_play.png" />
                                                                <svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M 0,100 0,99 50,97 100,99 100,100 z" fill="<?php echo MF_Text::getCatColor($news['Category']['slug']); ?>" /></svg>

                                                            <?php else: ?>
                                                                <svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M 0,100 0,99 50,97 100,99 100,100 z" fill="<?php echo MF_Text::getCatColor($news['Category']['slug']); ?>" /></svg>

                                                            <?php endif; ?>
                                                </figure>
                                        </a>
                                </div>
                                <div class="item-content">
                                        <h3><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a></h3>
                                        <span class="item-meta">
                                            <span><?php echo MF_Text::polishTimeFormat($news['publish_date']); ?></span>
                                        </span>
                                        <p><?php echo MF_Text::truncate(strip_tags($news['Translation'][$this->language]['content']),120); ?></p>
                                        <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" class="read-more-link">Czytaj więcej<i class="fa fa-angle-double-right"></i></a>
                                </div>
                            <?php else: ?>
                                <div class="item-content">
                                        <h3><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a></h3>
                                        <span class="item-meta">
                                                <span><?php echo MF_Text::polishTimeFormat($news['publish_date']); ?></span>
                                        </span>
                                </div>
                            <?php endif; ?>
                        </div>

                </div>
            </div>
        <?php endforeach; ?>


</div>
