<script>
    $(document).ready(function(){
        
        var currentOrder = "<?php echo $this->orderParam; ?>";
        $('option[value="'+currentOrder+'"]').prop('selected',true);
        $('.orderBox select').change(function(){
           $(location).attr('href',  $(this).find(":selected").attr('href'));
        });
        
        $(".purchase").click(function(e) {
                e.preventDefault();
                var url = $(this).attr("href");
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: url,
                    data: {format: "json", status: "status", counter: "counter"},
                    success: function(resp) {
                         if(resp.status == "success") {
                            $('.cartItems').html(resp.miniCartView);
                            jSuccess(
                                '<?php echo $this->translate('Product has been added to the cart') ?>',
                                {
                                    MinWidth : 250,
                                    TimeShown : 1500,
                                    ShowTimeEffect : 200,
                                    HideTimeEffect : 200,
                                    HorizontalPosition : 'right',
                                    VerticalPosition : 'top',
                                    ShowOverlay : false,
                                }
                            );
                         }
                    }
                });               
        });  
    });
</script>
<div id="content" class="single col-lg-12 col-md-12 col-sm-12">
<section class="singleheader-wrap">
    <div class="singleheader">
        <div class="container">
            <h3 class="new-title" style="text-align: left;"><?php echo $this->translate('Shop') ?></h3>
            <div class="col-lg-12 col-sm-12 col-md-12">
                <div class="single-title">
                    <h3><?php echo $this->translate('For distributors') ?></h3>
                </div>
            </div>
            
        </div>  
    </div>
</section>
</div>          
<section class="homecolon">
    <div class="container">
        <div id="content" class="single col-lg-12 col-md-12 col-sm-12">

            <div class="shop-top">
                <div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
                    <p>Showing <?php echo ($this->page-1) * $this->productCountPerPage + 1; ?>-<?php echo ($this->page-1) * $this->productCountPerPage + $this->paginator->getCurrentItemCount(); ?> of <?php echo $this->paginator->getTotalItemCount(); ?> results</p>
                </div>
                    
                <div class="pull-right col-lg-3 col-md-3 col-sm-6 col-xs-12 orderBox">
                    <select class="form-control">
                        <option value="name_asc" href="<?php echo $this->url(array('page' => $this->page,'order' => 'name_asc'),'domain-i18n:for-distributors-page');?>">By name A-Z</option>
                        <option value="name_desc"  href="<?php echo $this->url(array('page' => $this->page,'order' => 'name_desc'),'domain-i18n:for-distributors-page');?>">By name Z-A</option>
                        <!--<option value="rating" >Sort by average rating</option>-->
                        <option value="new_desc"  href="<?php echo $this->url(array('page' => $this->page,'order' => 'new_desc'),'domain-i18n:for-distributors-page');?>">Sort by newness</option>
                        <option value="price_asc"  href="<?php echo $this->url(array('page' => $this->page,'order' => 'price_asc'),'domain-i18n:for-distributors-page');?>">Sort by price: low to high</option>
                        <option value="price_desc" href="<?php echo $this->url(array('page' => $this->page,'order' => 'price_desc'),'domain-i18n:for-distributors-page');?>">Sort by price: high to low</option>	
                    </select>
                </div>
            </div>
                        
            <div class="clearfix"></div>
                        
            <?php if(isset($this->paginator)): ?>
                <?php foreach($this->paginator as $product):?>
                    <?php if(strlen($product['Categories'][0]['Translation'][$this->language]['slug']) > 0 && $product['Translation'][$this->language]['slug']): ?>
                        <div class="shopcol col-lg-3 col-md-3 col-sm-6 col-xs-12" data-effect="slide-bottom">

                            <div class="product1 image-hover he-wrap tpl6">
                                <?php if($product['new']): ?>
                                    <span class="onsale">Sale!</span>
                                <?php endif; ?>
                                <?php if($product['PhotoRoot']['offset']): ?>
                                    <img class="img-responsive" src="/media/photos/<?php echo $product['PhotoRoot']['offset'] ?>/243x243/<?php echo $product['PhotoRoot']['filename'] ?>" data-original="/media/photos/<?php echo $product['PhotoRoot']['offset'] ?>/<?php echo $product['PhotoRoot']['filename'] ?>" alt="<?php echo $product['PhotoRoot']['alternate_text']; ?>" title="<?php echo $product['PhotoRoot']['title'] ?>" />
                                <?php else: ?>
                                    <img class="img-responsive" src="/images/layout/shop/no_photo.jpg" data-original="/images/layout/shop/no_photo.jpg" width='243' height='243' alt="<?php echo $this->translate('No photo') ?>"  />
                                <?php endif; ?>
                                <div class="he-view">
                                    <div class="bg a0" data-animate="fadeIn">
                                        <h3 class="a1" data-animate="fadeInDown"><?php echo $this->category->Translation[$this->language]->name; ?></h3>
                                        <a href="<?php echo $this->url(array('category' => $product['Categories'][0]['Translation'][$this->language]['slug'], 'product' => $product['Translation'][$this->language]['slug']), 'domain-i18n:product') ?>" class="btn a2" data-animate="rotateInLeft"><i class="fa fa-search"></i> Details</a>
                                        <a href="<?php echo $this->url(array('action' => 'add-to-cart', 'product-id' => $product['id']), 'domain-cart-ajax') ?>" class="purchase btn a2" data-animate="rotateInRight"><i class="fa fa-shopping-cart"></i> Cart</a>
                                    </div>
                                </div>			
                            </div>                       
                            <div class="product-details">
                                <h4>
                                    <?php echo MF_Text::truncate($product['Translation'][$this->language]['name'], 35, 'letters') ?>
                                </h4>
                                <div class="amount">
                                    <ul class="rating">
                                        <?php for($i=0;$i<$product['rate']; $i++): ?>
                                            <li><i class="star-on"></i></li>
                                        <?php endfor; ?>
                                        <?php for($i;$i<5;$i++): ?>
                                             <li><i class="star-off"></i></li>
                                        <?php endfor; ?>
                                    </ul>
                                </div>  
                                <?php
                                    $arrayDiscounts = array($product['Discount'], $product['Producer']['Discount'], $this->userDiscount);
                                    foreach($this->userGroupDiscounts as $userGroupDiscount):
                                        $arrayDiscounts[] = $userGroupDiscount;
                                    endforeach;
					if(strlen($product['promotion_price'])):
                                    $flag = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
					else:
                                    $flag = MF_Discount::getPriceWithDiscount($product['price'], $arrayDiscounts);
					endif;
                                    $flag = $flag['flag'];
                                ?>
                                <?php if($flag || $product['promotion']): ?>
                                    <?php if($product['promotion']): ?>
                                        <?php if($flag): ?>
                                            <span class="price">
                                                <?php
					 if(strlen($product['promotion_price'])):
                                    		$flag = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
					else:
                                    		$flag = MF_Discount::getPriceWithDiscount($product['price'], $arrayDiscounts);
					endif;
                                                $price = $price['price'];
                                                echo $this->currency($price); ?> zł
                                                <span class="price-old">
                                                    <?php echo $this->currency($product['price']); ?>
                                                </span>
                                            </span>
                                        <?php else: ?>
                                            <?php if(strlen($product['promotion_price'])) : ?>
                                                    <span class="price"><?php echo $this->currency($product['promotion_price']); ?> <span class="price-old"><?php echo $this->currency($product['price']); ?></span></span>
                                            <?php else: ?>
                                                    <span class="price"><?php echo $this->currency($product['price']); ?></span>
                                            <?php endif;  ?>
                                        <?php endif; ?>
                                    <?php else: ?> 
                                        <span class="price">
                                            <?php 
                                            if(strlen($product['promotion_price'])):
                                    		$flag = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
					else:
                                    		$flag = MF_Discount::getPriceWithDiscount($product['price'], $arrayDiscounts);
					endif;


                                            $price = $price['price'];
                                            echo $price; ?> zł
                                            <span class="price-old">
                                                <?php echo $this->currency($product['price']); ?>
                                            </span>
                                        </span>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <span class="price">
                                        <?php echo $this->currency($product['price']); ?>
                                    </span>
                                <?php endif; ?>
                            </div><!-- product details -->
                        </div><!-- col-3 -->
                    <?php endif; ?>
                <?php endforeach; ?>
          <?php endif; ?>
          <div class="clearfix text-center" style="clear:both">  
            <ul class="pagination">
                <?php  echo $this->paginationControl($this->paginator, 'Sliding', 'product_distributor_pagination_control.phtml') ?>
            </ul>
          </div>
        </div><!-- end content -->
    </div><!-- end container -->
</section><!-- end slider products -->
