<?php $product = $this->product; ?>
<script src="/assets/plugins/isotope.pkgd.min.js"></script>
<script src="/assets/plugins/jquery.elevateZoom-3.0.8.min.js"></script>
<script src="/assets/plugins/flexslider/jquery.flexslider-min.js"></script>
<script>
    $(document).ready(function(){
        
        $("#mainProduct .purchase").click(function(e) {
                e.preventDefault();
                var counter = $("#quantity").val();
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: '<?php echo $this->url(array('action' => 'add-to-cart', 'product-id' => $product['id']), 'domain-cart-ajax') ?>',
                    data: {format: "json", status: "status", counter: counter},
                    success: function(resp) {
                         if(resp.status == "success") {
                            $('#miniCart').html(resp.miniCartView);
                            jSuccess(
                                '<?php echo $this->translate('Product has been added to the cart') ?>',
                                {
                                    MinWidth : 250,
                                    TimeShown : 1500,
                                    ShowTimeEffect : 200,
                                    HideTimeEffect : 200,
                                    HorizontalPosition : 'center',
                                    VerticalPosition : 'center',
                                    ShowOverlay : true
                                }
                            );
                         }
                    }
                });               
        });

        $(".featured_products .purchase").click(function(e) {
            e.preventDefault();
            var url = $(this).attr("href");
            $.ajax({
                type: "post",
                dataType: "json",
                url: url,
		    data: {format: "json", status: "status", counter: 1},
                success: function(resp) {
                    if(resp.status == "success") {
			$('#miniCart').html(resp.miniCartView);
                        jSuccess(
                            '<?php echo $this->translate('Product has been added to the cart') ?>',
                            {
                                MinWidth : 250,
                                TimeShown : 1500,
                                ShowTimeEffect : 200,
                                HideTimeEffect : 200,
                                HorizontalPosition : 'center',
                                VerticalPosition : 'center',
                                ShowOverlay : true
                            }
                        );
                    }
                }
            });
        });
    });
</script>

<section class="page_title_2 bg_light_2 t_align_c relative wrapper">
	<div class="container">
		<h2 class="color_dark fw_light m_bottom_5"><?php echo $product['Translation'][$this->language]['name']; ?></h2>
		<!--breadcrumbs-->
		<ul class="hr_list d_inline_m breadcrumbs">
			<li class="m_right_8 f_xs_none"><a href="/" class="color_default d_inline_m m_right_10">Strona główna</a><i class="icon-angle-right d_inline_m color_default fs_small"></i></li>
			<li><a class="color_default d_inline_m"><?php echo $product['Translation'][$this->language]['name']; ?></a></li>
		</ul>
	</div>
</section>
			<!--content-->
<div class="section_offset counter">
	<div class="container">
		<div class="row" id='mainProduct'>
			<div class="col-lg-6 col-md-6 col-sm-6 m_md_bottom_30 m_bottom_70">
				<div class="clearfix">
					<div class="thumbnails_carousel type_2 t_align_c f_left m_right_20">
						<ul id="thumbnails">
							<li>
							    <?php foreach($product['Photos'] as $photo): ?>
								<a href="#" data-zoom-image="/media/photos/<?php echo $photo['offset'];?>/<?php echo $photo['filename']; ?>" data-image="/media/photos/<?php echo $photo['offset'];?>/470x648/<?php echo $photo['filename']; ?>" class="active d_block wrapper r_corners tr_all translucent m_bottom_10"><img src="/media/photos/<?php echo $photo['offset'];?>/80x80/<?php echo $photo['filename']; ?>" alt="" class="r_corners"></a>
							    <?php endforeach; ?>

							</li>
						</ul>
						<!---->
						<div class="helper-list"></div>
					</div>
					<div class="wrapper r_corners container_zoom_image relative">
						<img id="img_zoom" src="/media/photos/<?php echo $product['PhotoRoot']['offset'];?>/470x648/<?php echo $product['PhotoRoot']['filename']; ?>" data-zoom-image="/media/photos/<?php echo $product['PhotoRoot']['offset'];?>/<?php echo $product['PhotoRoot']['filename']; ?>" alt="">
						<div class="labels_container">
							<?php if($product['new']): ?>
							    <a href="#" class="d_block label color_scheme tt_uppercase fs_ex_small circle m_bottom_5 vc_child t_align_c"><span class="d_inline_m">Nowość</span></a>
							<?php endif; ?>
							<?php if($product['promotion']): ?>
							    <a href="#" class="d_block label color_pink color_pink_hover tt_uppercase fs_ex_small circle m_bottom_5 vc_child t_align_c"><span class="d_inline_m">Promocja</span></a>
							<?php endif; ?>
						</div>
					</div>
					<a href="#" class="open_product f_right button_type_6 d_block r_corners tr_all t_align_c">
						<i class="icon-resize-full"></i>
					</a>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 m_md_bottom_30 m_bottom_70">
				<div class="clearfix m_bottom_15 m_top_5">
					<ul class="rating_list f_left hr_list tr_all m_right_8">
					    <?php 
					    $rate = round($product['rate']);
					    echo str_repeat('<li class="relative active lh_ex_small">
							<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
							<i class="icon-star-1 color_yellow tr_all"></i>
						</li>', $rate);

					    echo str_repeat('<li class="relative lh_ex_small">
							<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
							<i class="icon-star-1 color_yellow tr_all"></i>
						</li>', 5-$rate);
						?>
					</ul>
					<a class="reviews fs_medium f_left color_dark tr_all lh_ex_small" href="#">Liczba opinii: <?php echo count($this->comments); ?></a>
					&nbsp;&nbsp;<a id="reviewShow" class="reviews fs_medium f_left color_dark tr_all lh_ex_small m_left_10" href="javascript:void(0)">Pokaż opinie</a>
					
					<div class="d_none" id="reviewList">
					    <div class="col-md-5 col-lg-5 col-sm-5">
                                                <h5 class="m_bottom_10 fw_ex_bold m_top_5">Opinie</h5>
						<?php foreach($this->comments as $comment): ?>
                                                <i><?php echo $comment['nick']; ?></i><br />
                                                <small><i><?php echo $comment['description']; ?> </i></small> 
						    <hr /> 
						<?php endforeach; ?>
                                                    <br />
						<form method="POST">
							<h5 class="fw_ex_bold">Dodaj komentarz</h5>
						    <br />
                                                    <?php echo $this->form->nick; ?></i>
						    <br />
						    <?php echo $this->form->description; ?>
						    <br />
						    Moja ocena<br />
						    <ul class="rate_product rating_list hr_list tr_all m_right_8">
							    <li class="relative lh_ex_small" rel="1">
								<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
								<i class="icon-star-1 color_yellow tr_all"></i>
							    </li>
							    <li class="relative lh_ex_small" rel="2">
								<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
								<i class="icon-star-1 color_yellow tr_all"></i>
							    </li>
							    <li class="relative lh_ex_small" rel="3">
								<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
								<i class="icon-star-1 color_yellow tr_all"></i>
							    </li>
							    <li class="relative lh_ex_small" rel="4">
								<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
								<i class="icon-star-1 color_yellow tr_all"></i>
							    </li>
							    <li class="relative lh_ex_small" rel="5">
								<i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
								<i class="icon-star-1 color_yellow tr_all"></i>
							    </li>
						    </ul>
						    <div class="clearfix"></div>
						    <span class="d_none">
						    <?php echo $this->form->partial_rate; ?>
						    </span>
						    <br />
						    <?php echo $this->form->captcha; ?>
						    <br />
						    <button name="save_comment" type="submit" class="m_top_15 button_type_6 d_inline_b color_blue transparent r_corners vc_child tr_all add_to_cart_button">
							<span class="d_inline_m clerarfix">
							    <i class="icon-save f_left m_right_10 fs_large"></i>
							    <span class="fs_medium">Dodaj komentarz</span>
							</span>
						    </button>

						</form>
					    </div>
					    <div class="clearfix"></div>
					</div>
				</div>
				<div class="fw_ex_bold color_pink product_current_price m_bottom_15 lh_medium">
				<?php
					$arrayDiscounts = array($product['Discount'], $product['Producer']['Discount'], $this->userDiscount);
					foreach($this->userGroupDiscounts as $userGroupDiscount):
					    $arrayDiscounts[] = $userGroupDiscount;
					endforeach;
					$flag = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
					$flag = $flag['flag'];
				    ?>
				    <?php 
				    /* price start */
				    if($flag || $product['promotion']): ?>
					<?php if($product['promotion']): ?>
					    <?php if($flag): ?>
						    <span itemprop="price" class="pr">
							<s class="color_grey fw_light"><?php echo $product['price']; ?> zł</s>
							<?php 
							$price = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts); 
							$price = $price['price'];
							echo $price; ?> zł
						    </span>
					    <?php else: ?>
						<span itemprop="price" class="pr">
						    <s class="color_grey fw_light"><?php echo $product['price']; ?> zł</s>
						    <?php echo $product['promotion_price']; ?> zł
						</span>
					    <?php endif; ?>
					<?php elseif($flag): ?> 
						<span itemprop="price" class="pr">
						    <s class="color_grey fw_light"><?php echo $product['price']; ?> zł</s>
						    <?php 
						    $price = MF_Discount::getPriceWithDiscount($product['price'], $arrayDiscounts); 
						    $price = $price['price'];
						    echo $price; ?> zł
						</span>
					<?php endif; ?>
				    <?php else: ?>
					<span itemprop="price" class="pr">
					    <?php echo $product['price']; ?> zł
					</span>
				    <?php endif;
				    /* price end */
				    ?>	

				</div>
				<hr class="m_bottom_10">
				<span class="color_grey fs_medium m_bottom_15">
				    <?php echo $product['Translation'][$this->language]['description']; ?>
				</span>
				<hr class="m_bottom_12 m_top_15">
				<table class="fw_light table_type_9 m_bottom_20">
					<tbody>
					    <tr>
						    <td class="v_align_m">
							    Ilość: 
						    </td>
						    <td class="color_dark">
							    <div class="wrapper d_inline_m fs_medium r_corners quantity type_2 clearfix">
								    <button class="f_left bg_light_3" data-count="minus">
									    <i class="icon-minus "></i>
								    </button>
								    <input type="text" readonly="" value="1" id="quantity" class="f_left color_grey bg_light">
								    <button class="f_left bg_light_3" data-count="plus">
									    <i class="icon-plus"></i>
								    </button>
							    </div>
						    </td>
					    </tr>
				    </tbody>
				</table>
				<div class="m_bottom_15">
					<a href="javascript:void(0)" class="purchase button_type_7 m_mxs_bottom_5 d_inline_b m_right_2 tt_uppercase color_pink r_corners vc_child tr_all add_to_cart_button"><span class="d_inline_m clerarfix"><i class="icon-basket f_left m_right_10 fs_large"></i><span class="fs_medium">Dodaj do koszyka</span></span></a>
				</div>
				<!--share buttons-->
				<?php if($this->loginUrl): ?>
				    <a class="m_top_10" href="<?php echo $this->loginUrl; ?>">

					<img src="/images/layout/facebook_share_button.png" /> <br />

				    </a>
				<div class="col-lg-8 col-md-8 col-sm-8 m_bottom_12 m_xs_bottom_0 bannerWrapper m_top_15 m_left_0" style="padding-left:0px;" data-appear-animation="fadeInUp" data-appear-animation-delay="400">
                <div class="bannerContent" id="banner1" style="top:15px;">
                    <?php echo $this->banner3['Translation'][$this->language]['content']; ?>
                </div>
			    <a href="#" class="d_block d_xs_inline_b d_mxs_block"><img src="/assets/images/banner_3.jpg" alt="Banner 3"></a>
		    </div>

							<?php endif; ?>
							 <?php if($this->messages()->count()): ?>
							    <div class="alert alert-error">
								<?php echo $this->messages()->render() ?>
							    </div>
							<?php endif; ?>
				<div class="col-md-4 col-lg-4 col-sm-4">&nbsp;</div>
				<div class="clearfix"></div>
				
						</div>
					</div>
					<!--title & nav-->
					<div class="clearfix m_bottom_23 m_sm_bottom_10 m_xs_bottom_20">
					    <h5 class="fw_light f_left f_xs_none color_dark m_xs_bottom_10">Pozostałe produkty w kategorii <strong><?php echo $this->category['Translation'][$this->language]['name']; ?></strong></h5>
						<div class="f_right f_xs_none clearfix">
							<button class="icon_wrap_size_5 circle color_grey_light f_left m_right_8 fproducts_nav_1_prev fn_type_2 color_scheme_hover tr_all">
								<i class="icon-angle-left fs_large"></i>
							</button>
							<button class="icon_wrap_size_5 circle color_grey_light f_left fproducts_nav_1_next fn_type_2 color_scheme_hover tr_all">
								<i class="icon-angle-right fs_large"></i>
							</button>
						</div>
					</div>
					<div class="row">
						<div class="featured_products owl-carousel type_2 t_xs_align_c m_bottom_45 m_xs_bottom_30" data-plugin-options='{"singleItem":false,"itemsCustom":[[992,4],[768,3],[600,2],[10,1]],"autoPlay":true}' data-nav="fproducts_nav_1_">
							<?php foreach($this->categoryProducts as $product): ?>
							    <figure class="fp_item t_align_c d_xs_inline_b col-lg-12 col-md-12 col-sm-12">
								    <div class="relative r_corners d_xs_inline_b d_mxs_block wrapper m_bottom_23">
									    <!--images container-->
									    <div class="fp_images relative">
										<img src="<?php echo MF_Text::getPhotoPath($product['PhotoRoot'], '270x300');?>" alt="<?php echo $product['Translation'][$this->language]['name']; ?>" class="tr_all">
									    </div>
									    <!--labels-->
									    <div class="labels_container">
										<?php if($product['new']): ?>
										    <a href="#" class="d_block label color_scheme tt_uppercase fs_ex_small circle m_bottom_5 vc_child t_align_c"><span class="d_inline_m">Nowość</span></a>
										<?php endif; ?>
										<?php if($product['promotion']): ?>
										    <a href="#" class="d_block label color_pink color_pink_hover tt_uppercase fs_ex_small circle m_bottom_5 vc_child t_align_c"><span class="d_inline_m">Promocja</span></a>
										<?php endif; ?>
									    </div>
								    </div>
								    <figcaption>
									    <h6 class="m_bottom_5"><a href="#" class="color_dark"><?php echo $product['Translation'][$this->language]['name']; ?></a></h6>
									    <a href="#" class="fs_medium color_grey d_inline_b m_bottom_3"><i><?php echo $this->category['Translation'][$this->language]['name']; ?></i></a>
									    <div class="im_half_container m_bottom_10">
                                            <p class="color_dark fw_ex_bold  d_block t_align_c tr_all fp_price">
                                                <?php
                                                /* price counter start */
                                                $arrayDiscounts = array($product['Discount'], $product['Producer']['Discount'], $this->userDiscount);
                                                foreach($this->userGroupDiscounts as $userGroupDiscount):
                                                    $arrayDiscounts[] = $userGroupDiscount;
                                                endforeach;
                                                $flag = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
                                                $flag = $flag['flag'];
                                                ?>
                                                <?php if($flag || $product['promotion']): ?>
                                                    <?php if($product['promotion']): ?>
                                                        <?php if($flag): ?>
                                                            <?php
                                                            $price = MF_Discount::getPriceWithDiscount($product['promotion_price'], $arrayDiscounts);
                                                            $price = $price['price'];
                                                            echo $price; ?> zł
                                                            <s class="fw_normal color_grey"><?php echo $product['price']; ?> zł</s>

                                                        <?php else: ?>
                                                            <?php echo $product['promotion_price']; ?> zł
                                                            <s class="fw_normal color_grey"><?php echo $product['price']; ?> zł</s>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php
                                                        $price = MF_Discount::getPriceWithDiscount($product['price'], $arrayDiscounts);
                                                        $price = $price['price'];
                                                        echo $price; ?> zł
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php echo $product['price']; ?> zł
                                                <?php endif; ?>
                                            </p>
                                            <div class="half_column d_inline_m t_align_c tr_all">
                                                <ul class="rating_list d_inline_m hr_list tr_all">
                                                    <?php
                                                    $rate = round($rate);
                                                    echo str_repeat('<li class="relative active lh_ex_small">
                                                            <i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
                                                            <i class="icon-star-1 color_yellow tr_all"></i>
                                                        </li>', $rate);

                                                                    echo str_repeat('<li class="relative lh_ex_small">
                                                            <i class="icon-star-empty-1 color_grey_light_2 tr_all"></i>
                                                            <i class="icon-star-1 color_yellow tr_all"></i>
                                                        </li>', 5-$rate);
                                                    ?>
                                                </ul>
                                            </div>
					
									    </div>
									    <div class="clearfix">
                                            <div class="half_column w_md_full m_md_bottom_10 animate_fctl tr_all f_left f_md_none with_ie">
                                                <a href="<?php echo $this->url(array('action' => 'add-to-cart', 'product-id' => $product['id']), 'domain-cart-ajax') ?>" class="purchase button_type_6 d_inline_b color_pink transparent r_corners vc_child tr_all add_to_cart_button"><span class="d_inline_m clerarfix"><i class="icon-basket f_left m_right_10 fs_large"></i><span class="fs_medium">Do koszyka</span></span></a>
                                            </div>
									    </div>
								    </figcaption>
							    </figure>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
			</div>
			<hr class="divider_type_2">

			<script>
			    $(document).ready(function(){
				$('#reviewShow').click(function(){
				    if($('#reviewList').is(':visible')){
					$('#reviewList').hide();
				    }
				    else{
					$('#reviewList').fadeIn(1000);
				    }
				})
				
				$('.rate_product li').click(function(){
				    var value = $(this).attr('rel');
				    
				    $('#partial_rate').val(value);
				});
			    });
			</script>