<script type="text/javascript">
  
    $(document).ready(function() { 
        
        $(".stars").jRating();
        
  });
</script>

<section id="product">
    <div itemscope itemtype="http://data-vocabulary.org/Product">
        <div id="product_top_bar">
            <ul>
                <span itemprop="category" content="<?php echo $this->product['Producer']->Translation[$this->language]->name.' > '.$this->product->Translation[$this->language]->name; ?>">
                    <li>
                        <?php if($this->product['Producer']->Translation[$this->language]->slug): ?>
                            <a href="<?php echo $this->url(array('producer' => $this->product['Producer']->Translation[$this->language]->slug), 'domain-i18n:producer'); ?>">
                                <?php echo ucfirst($this->product['Producer']->Translation[$this->language]->name); ?>
                            </a>
                        <?php endif; ?>
                    </li>
                    <li>
                        <?php echo ucfirst($this->product->Translation[$this->language]->name); ?>
                    </li>
                </span>
            </ul>
        </div>
        <div id="product_bottom_bar">
                <div class="product_left">
                    <div class="viewport">              
                        <?php if(isset($this->productPhotos)): ?>
                            <?php $counter = 0; ?>
                            <?php foreach($this->productPhotos as $photo): ?>
                                <?php if($counter < 4 && $photo['offset']): ?>
                                    <a href="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" data-lightbox="product[]" title="<?php echo $this->product->get('PhotoRoot')->getTitle() ?>">
                                        <img itemprop="image" src="/media/photos/<?php echo $photo['offset'] ?>/510x510/<?php echo $photo['filename'] ?>" data-original="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['alternate_text']; ?>" title="<?php echo $photo['title'] ?>" id="imageid"/>
                                    </a>
                                <?php $counter++; endif; ?>    
                            <?php endforeach; ?>   
                            <?php if($counter == 0): ?>
                                <img src="/images/layout/shop/no_photo.jpg" data-original="/images/layout/shop/no_photo.jpg" alt="<?php echo $this->translate('No photo') ?>" style="width: 510px; height: 510px" />
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <ul class="thumbs">
                        <?php if(isset($this->productPhotos)):  ?>
                            <?php $counter = 0; ?>
                            <?php foreach($this->productPhotos as $photo): ?>
                                <?php if($counter < 4 && $photo['offset']): ?>  
                                    <li><img src="/media/photos/<?php echo $photo['offset'] ?>/115x115/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['alternate_text']; ?>" title="<?php echo $photo['title'] ?>"></li>
                               <?php $counter++; endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </ul>
                    <div class="more_buy">
                        <header>
                            <?php echo $this->translate('Person who bought this product also purchased');?>
                        </header>
                        <ul>
                            <?php foreach($this->categoryBestsellers as $categoryBestseller):?>
                                <?php if($this->category->Translation[$this->language]->slug && $categoryBestseller['Translation'][$this->language]['slug']): ?>
                                    <li>
                                        <a href="<?php echo $this->url(array('category' => $this->category->Translation[$this->language]->slug, 'product' => $categoryBestseller['Translation'][$this->language]['slug']), 'domain-i18n:product') ?>">
                                            <span class="product_image">
                                                <?php if($categoryBestseller['PhotoRoot']['offset']): ?>
                                                    <img src="/media/photos/<?php echo $categoryBestseller['PhotoRoot']['offset'] ?>/120x120/<?php echo $categoryBestseller['PhotoRoot']['filename'] ?>" data-original="/media/photos/<?php echo $categoryBestseller['PhotoRoot']['offset'] ?>/<?php echo $categoryBestseller['PhotoRoot']['filename'] ?>" alt="<?php echo $categoryBestseller['PhotoRoot']['alternate_text']; ?>" title="<?php echo $categoryBestseller['PhotoRoot']['title'] ?>" />
                                                <?php else: ?>
                                                    <img src="/images/layout/shop/no_photo.jpg" data-original="/images/layout/shop/no_photo.jpg" alt="<?php echo $this->translate('No photo') ?>" style="width: 120px; height: 120px" />
                                                <?php endif; ?>
                                            </span>
                                            <div class="clearfix"></div>
                                            <span class="name">
                                                <header><?php echo MF_Text::truncate($categoryBestseller['Translation'][$this->language]['name'], 44); ?></header>
                                            </span>
                                            <span class="price">
                                                    <span class="buy"><?php echo $this->translate('buy now') ?></span> <span class="pr"><?php echo $categoryBestseller['price']; ?> zł</span>
                                            </span>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="product_right">
                    <div class="price">
                        <span itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
                            <meta itemprop="currency" content="PLN" />
                            <?php if($this->product['Discount']): ?>
                                <span class="buy"><?php echo $this->translate('buy now') ?></span> <span itemprop="price" class="pr"><?php echo $this->product['price']; ?> zł</span>
                                <div class="promotion"><?php echo $this->product['price']; ?> zł</div>
                            <?php else: ?>
                                <span class="buy"><?php echo $this->translate('buy now') ?></span> <span itemprop="price" class="pr"><?php echo $this->product['price']; ?> zł</span>
                            <?php endif; ?>
                            <span itemprop="condition" content="nowe"></span>
                            <span itemprop="availability" content="<?php echo $this->product->getAvailability(); ?>"></span>
                        </span> 
                    </div>
                    <div class="cart">
                        <a href="<?php echo $this->url(array('action' => 'add-to-cart', 'product-id' => $this->product['id']), 'domain-cart-ajax') ?>" class="purchase">
                            <img src="/images/layout/shop/KOSZYK.png" alt="<?php echo $this->translate('Cart') ?>" />
                        </a>
                    </div>
                    <div class="name" itemprop="name">
                        <?php echo $this->product['Translation'][$this->language]['name']; ?>
                    </div>
                    <span class="brand" itemprop="brand"><?php echo $this->product['Producer']->Translation[$this->language]->name; ?></span>
                    <span class="identifier" itemprop="identifier" content="<?php echo $this->product->getCode(); ?>"><?php echo $this->product->getCode(); ?></span>
                    <div class="rating">
                        <div class="stars" data-average="10" data-id="6"></div>
                        <span itemprop="review" itemscope itemtype="http://data-vocabulary.org/Review-aggregate">
                            <span class="rating_google" itemprop="rating">4.4</span>
                            <span class="count" itemprop="count">89</span>
                        </span>
                        <span><?php echo $this->translate('rating buyers') ?></span>
                    </div>

                    <div class="description" itemprop="description">
                        <?php echo $this->product['Translation'][$this->language]['description']; ?>
                    </div>

                </div>
            </div>
    </div>
</section>
        
        