<?php

/**
 * Product_Model_Doctrine_AttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_AttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_AttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Attachment');
    }
    
     public function getAttachmentQuery() {
        $q = $this->createQuery('a');
        $q->addSelect('a.*');
        $q->addSelect('at.*');
        $q->leftJoin('a.Translation at');
        return $q;
    }
}