<?php

/**
 * Product_Model_Doctrine_BaseProducer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $owner
 * @property string $email
 * @property string $phone
 * @property string $website
 * @property string $address
 * @property string $post_code
 * @property string $city
 * @property string $province
 * @property clob $description
 * @property string $nip
 * @property string $slug
 * @property integer $photo_root_id
 * @property integer $metatag_id
 * @property boolean $status
 * @property integer $discount_id
 * @property string $cord_x
 * @property string $cord_y
 * @property integer $views
 * @property integer $clicks
 * @property Product_Model_Doctrine_Discount $Discount
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $Previews
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseProducer extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_producer');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('owner', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('post_code', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('province', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('nip', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('metatag_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('discount_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('cord_x', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('cord_y', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('views', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('clicks', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
             'local' => 'discount_id',
             'foreign' => 'id'));

        $this->hasMany('Product_Model_Doctrine_Product as Products', array(
             'local' => 'id',
             'foreign' => 'producer_id'));

        $this->hasMany('Product_Model_Doctrine_Preview as Previews', array(
             'local' => 'id',
             'foreign' => 'producer_id'));

        $this->hasMany('Product_Model_Doctrine_ProducerTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'slug',
              2 => 'description',
             ),
             'tableName' => 'product_producer_translation',
             'className' => 'ProducerTranslation',
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'HasManyRoots' => false,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($nestedset0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}