<?php

/**
 * Product_Model_Doctrine_BaseProductRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $user_id
 * @property decimal $rate
 * @property Product_Model_Doctrine_Product $Product
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseProductRate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_product_rate');
        $this->hasColumn('product_id', 'integer', 4, array(
             'primary' => false,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'primary' => false,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rate', 'decimal', null, array(
             'type' => 'decimal',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Doctrine_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}