<?php

/**
 * Product_Model_Doctrine_BaseProductTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $lang
 * @property string $name
 * @property string $slug
 * @property clob $short_description
 * @property clob $description
 * @property clob $ingredients
 * @property clob $how_to_use
 * @property clob $reduced_price_text
 * @property Product_Model_Doctrine_Product $Product
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseProductTranslation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_product_translation');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('lang', 'string', 64, array(
             'primary' => true,
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('short_description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ingredients', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('how_to_use', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('reduced_price_text', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Doctrine_Product as Product', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}