<?php

/**
 * Product_Model_Doctrine_BasePreviewCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $preview_id
 * @property integer $category_id
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BasePreviewCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_preview_category');
        $this->hasColumn('preview_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}