<?php

/**
 * Product_Model_Doctrine_BaseDiscount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $status
 * @property timestamp $start_date
 * @property timestamp $finish_date
 * @property integer $amount_discount
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $Producers
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseDiscount extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_discount');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('amount_discount', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_Doctrine_Product as Products', array(
             'local' => 'id',
             'foreign' => 'discount_id'));

        $this->hasMany('Product_Model_Doctrine_Producer as Producers', array(
             'local' => 'id',
             'foreign' => 'discount_id'));

        $this->hasMany('Product_Model_Doctrine_DiscountTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'tableName' => 'product_discount_translation',
             'className' => 'DiscountTranslation',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}