<?php

/**
 * Product_Model_Doctrine_BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property clob $short_description
 * @property clob $description
 * @property clob $ingredients
 * @property clob $how_to_use
 * @property decimal $price
 * @property string $code
 * @property integer $availability
 * @property integer $distributor
 * @property boolean $status
 * @property boolean $promotion
 * @property decimal $promotion_price
 * @property boolean $new
 * @property boolean $most_frequently_purchased
 * @property boolean $reduced_price
 * @property clob $reduced_price_text
 * @property string $youtube
 * @property decimal $vat
 * @property integer $producer_id
 * @property integer $discount_id
 * @property integer $photo_root_id
 * @property decimal $rate
 * @property integer $metatag_id
 * @property integer $views
 * @property integer $clicks
 * @property integer $order_counter
 * @property Product_Model_Doctrine_Producer $Producer
 * @property Product_Model_Doctrine_Discount $Discount
 * @property Product_Model_Doctrine_ProductRelated $RelatedProducts
 * @property Product_Model_Doctrine_ProductSet $SetProducts
 * @property Doctrine_Collection $Translation
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $Attachments
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseProduct extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_product');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('short_description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ingredients', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('how_to_use', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('code', 'string', 255, array(
             'unique' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('availability', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('distributor', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('promotion', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('promotion_price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('most_frequently_purchased', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('reduced_price', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('reduced_price_text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('youtube', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('vat', 'decimal', null, array(
             'type' => 'decimal',
             'default' => 23,
             ));
        $this->hasColumn('producer_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('discount_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rate', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('metatag_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('views', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('clicks', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('order_counter', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '5',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Doctrine_Producer as Producer', array(
             'local' => 'producer_id',
             'foreign' => 'id'));

        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
             'local' => 'discount_id',
             'foreign' => 'id'));

        $this->hasOne('Product_Model_Doctrine_ProductRelated as RelatedProducts', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasOne('Product_Model_Doctrine_ProductSet as SetProducts', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Product_Model_Doctrine_ProductTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Product_Model_Doctrine_Category as Categories', array(
             'refClass' => 'Product_Model_Doctrine_ProductCategory',
             'local' => 'product_id',
             'foreign' => 'category_id'));

        $this->hasMany('Product_Model_Doctrine_Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Product_Model_Doctrine_Attachment as Attachments', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'slug',
              2 => 'short_description',
              3 => 'description',
              4 => 'ingredients',
              5 => 'how_to_use',
              6 => 'reduced_price_text',
             ),
             'tableName' => 'product_product_translation',
             'className' => 'ProductTranslation',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}