<?php

/**
 * Product_Model_Doctrine_BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $description
 * @property string $slug
 * @property boolean $status
 * @property integer $metatag_id
 * @property integer $photo_root_id
 * @property integer $views
 * @property integer $clicks
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $Previews
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_category');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('metatag_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('views', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('clicks', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_Doctrine_Product as Products', array(
             'refClass' => 'Product_Model_Doctrine_ProductCategory',
             'local' => 'category_id',
             'foreign' => 'product_id'));

        $this->hasMany('Product_Model_Doctrine_Preview as Previews', array(
             'refClass' => 'Product_Model_Doctrine_PreviewCategory',
             'local' => 'category_id',
             'foreign' => 'preview_id'));

        $this->hasMany('Product_Model_Doctrine_CategoryTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'slug',
              2 => 'description',
             ),
             'tableName' => 'product_category_translation',
             'className' => 'CategoryTranslation',
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'HasManyRoots' => false,
             ));
        $this->actAs($i18n0);
        $this->actAs($nestedset0);
    }
}