<?php

/**
 * Product_Model_Doctrine_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Comment extends Product_Model_Doctrine_BaseComment
{
    public function isStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function isModeration() {
        return $this->_get('moderation');
    }
    
    public function setModeration($moderation = true) {
        $this->_set('moderation', $moderation);
    }
    
    public function getPartialRate() {
        return $this->_get('partial_rate');    
    }
    
    public function getProductId() {
        return $this->_get('product_id');    
    }
         
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}