<?php

/**
 * Product_Model_Doctrine_CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Comment');
    }
    
    public function getCommentQuery() {
        $q = $this->createQuery('co');
        $q->addSelect('co.*');
        return $q;
    }
    
    public function getPublishCommentQuery() {
        $q = $this->createQuery('co');
        $q->addSelect('co.*');
        $q->addSelect('pro.*');
        $q->addSelect('u.*');
        $q->leftJoin('co.Product pro');
        $q->leftJoin('co.User u');
        $q->andWhere('co.moderation = ?', 1);
        return $q;
    }
    
    public function getPublishCommentWithProductsQuery() {
        $q = $this->createQuery('co');
        $q->addSelect('co.*');
        $q->addSelect('pro.*');
        $q->addSelect('u.*');
        $q->addSelect('prot.*');
        $q->leftJoin('co.Product pro');
        $q->leftJoin('pro.Translation prot');
        $q->leftJoin('co.User u');
        $q->andWhere('co.moderation = ?', 1);
        return $q;
    }
}