<?php

/**
 * Product_Model_Doctrine_Discount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Discount extends Product_Model_Doctrine_BaseDiscount
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getAmount() {
        return $this->_get('amount_discount');
    }
    
    public function isStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function setUp() {
        $this->hasMany('User_Model_Doctrine_User as Users', array(
             'local' => 'id',
             'foreign' => 'discount_id'));
        
        $this->hasMany('User_Model_Doctrine_Group as Groups', array(
             'local' => 'id',
             'foreign' => 'discount_id'));
        parent::setUp();
    }
}