<?php

/**
 * Product_Model_Doctrine_DiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_DiscountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_DiscountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Discount');
    }
    
    public function getDiscountQuery() {
        $q = $this->createQuery('d');
        $q->addSelect('d.*');
        return $q;
    }
}