<?php

/**
 * Product_Model_Doctrine_Preview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Preview extends Product_Model_Doctrine_BasePreview
{
    public static $previewPhotoDimensions = array(
        '126x126' => 'Zdjęcie w panelu administracyjnym',                  // admin
        '660x440' => 'Zdjęcie'
    );
    
    public static $previewMainPhotoDimensions = array(
        '126x126' => 'Zdjęcie w panelu administracyjnym',                  // admin
        '200x200' => "Zdjęcie główne"
    );
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getName() {
        return $this->_get('name');
    }
    
    public function getMetatagId() {
        return $this->_get('metatag_id');    
    }
    
    public static function getPreviewPhotoDimensions() {
        return self::$previewPhotoDimensions;
    } 
    
    public static function getPreviewMainPhotoDimensions() {
        return self::$previewMainPhotoDimensions;
    } 
    
    public function isStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function setUp() {
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        
        $this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
        
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        parent::setUp();
    }
}