<?php

/**
 * Product_Model_Doctrine_PreviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_PreviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_PreviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Preview');
    }
    
    public function getPreviewQuery() {
        $q = $this->createQuery('p');
        $q->addSelect('p.*');
        $q->addSelect('pro.*');
        $q->addSelect('cat.*');
        $q->addSelect('pr.*');
        $q->leftJoin('p.Producer c');
        $q->leftJoin('p.Categories cat');
        $q->leftJoin('p.PhotoRoot pr');
        return $q;
    }
}