<?php

/**
 * Product_Model_Doctrine_ProductSet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_ProductSet extends Product_Model_Doctrine_BaseProductSet
{
    public function getCounter() {
        return $this->_get('counter');    
    }
    
    public function setSetProducts($setProducts) {
        $this->_set('set_products', $setProducts);
    }
    
    public function getSetProducts() {
        return $this->_get('set_products');    
    }
    
    public function getProductId() {
        return $this->_get('product_id');    
    }
    
    public function setProductId($productId) {
        $this->_set('product_id', $productId);
    }
    
    public function setCounter($counter) {
        $this->_set('counter', $counter);
    }
}