<?php

/**
 * Product_Model_Doctrine_ProductRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_ProductRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_ProductRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_ProductRelated');
    }
    
    public function getRelatedProductQuery() {
        $q = $this->createQuery('rp');
        $q->addSelect('rp.*');
        return $q;
    }
  
}