<?php

/**
 * Product_Model_Doctrine_ProductRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_ProductRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_ProductRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_ProductRate');
    }
    
    public function getProductRateQuery() {
        $q = $this->createQuery('r');
        $q->addSelect('r.*');
        return $q;
    }
}