<?php

/**
 * Product_Model_Doctrine_ProductSetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_ProductSetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_ProductSetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_ProductSet');
    }
    
    public function getSetProductQuery() {
        $q = $this->createQuery('sp');
        $q->addSelect('sp.*');
        return $q;
    }
}