<?php  $gallery = $this->gallery; ?>
<section id="bc-t">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="#">Strona główna</a></li>
            <li><span class="sep">   →   </span>
            </li><li><a href="<?php echo $this->url(array(),'domain-gallery-list'); ?>">Galeria</a></li>
            <li><span class="sep">   →   </span></li><li><a href="#"><?php echo $gallery['Translation'][$this->language]['name']; ?></a></li>
       
        </ul>
        <h1 class="blog-title"><?php echo $gallery['Translation'][$this->language]['name']; ?></h1>
    </div>
</section>
<section id="gallery-grid">
    <div class="container">
        <div class="b-menu">
                <nav id="blog-menu">
                                <ul class="clearfix">
                                    <?php foreach($this->paginator as $key => $gallery): ?>
                                        <li>
                                            <a href="<?php echo $this->url(array('slug' => $gallery['Translation'][$this->language]['slug']),'domain-gallery'); ?>">
                                            <?php echo substr($gallery['Translation'][$this->language]['name'],0,20);
                                            if(strlen($gallery['Translation'][$this->language]['name'])>20) echo "..."; ?>
                                            </a>
                                        </li>
                                        <?php endforeach; ?>

                                </ul>
                                <a href="#" id="pull-blog">Menu</a>
                        </nav>
        </div>
        <!-- blog menu end -->
        <!-- gallery -->
        
        <div class="gallery-item isotope js-isotope" data-isotope-options='{ "itemSelector": ".gal", "masonry": { "columnWidth": ".col-3" } }'>
            <?php foreach($this->gallery['Photos'] as $key=>$photo): 
                if($key==0)
                    continue;
                ?>
                <div class="gal col-6">
                    <a href="javascript:void(0)">
                        <?php
                        if(strlen($photo['filename'])){
                            $photoUrl = MF_Text::getPhotoPath($photo,'470x235');
                        }
                        else{
                            $photoUrl = "http://placehold.it/470x235";
                        }
                            
                            ?>
                        <img src="<?php echo $photoUrl; ?>" alt="<?php echo $this->gallery['Translation'][$this->language]['name']; ?>" title="<?php echo $this->gallery['Translation'][$this->language]['name']; ?>"/>
                    </a></div>
            <?php endforeach; ?>
        </div>
        <div class="pagination">
                <ul>
                    <li class="nav-arr prev"><a href="#"><i class="fa fa-angle-left"></i>&nbsp;</a></li>
                        <li><a href="#">1</a></li>
                        <li class="nav-arr next"><a href="#"><i class="fa fa-angle-right"></i>&nbsp;</a></li>
                </ul>
        </div>
    </div>
</section>
<!--<article id="content">
        <div class="wrapper tabs">
                <div class="tab-content" id="tab1">
                        <h5>
				<?php echo $gallery['Translation'][$this->language]['name']; ?>
			</h5>
                        <div class="wrapper pad_bot2">
                                <figure class="left marg_right1">
				    <?php if(strlen($gallery['Photos'][1])): ?>
				     <a class="lightview image-hover" href="<?php echo MF_Text::getPhotoPath($gallery['Photos'][1]); ?>"  data-lightview-type="image" data-lightview-group="<?php echo $gallery['Translation'][$this->language]['slug']; ?>" data-lightview-options="
				   width: 800,
				   height: 600,
				 " data-lightbox="lightbox" class="image-hover">
					<img src="<?php echo MF_Text::getPhotoPath($gallery['Photos'][1],'180x141'); ?>" alt="<?php echo $gallery['Translation'][$this->language]['name']; ?>" title="<?php echo $gallery['Translation'][$this->language]['name']; ?>">
				     </a>
				    <?php endif; ?>
				</figure>
                                <p class="pad_bot1"><?php echo $gallery['Translation'][$this->language]['description']; ?></p>
                                
			</div>
			<div class="photoGallery">
			    <?php foreach($gallery['Photos'] as $key => $photo):
				if($key<2)
				    continue;
				?>

			    <a class="lightview image-hover" href="/media/photos/<?php echo $photo['offset']?>/<?php echo $photo['filename'] ?>"  data-lightview-type="image" data-lightview-group="<?php echo $gallery['Translation'][$this->language]['slug']; ?>" data-lightview-options="
				   width: 800,
				   height: 600,
				 " data-lightbox="lightbox" class="image-hover">
				<img src="<?php echo MF_Text::getPhotoPath($photo,'180x141'); ?>" alt="<?php echo $gallery['Translation'][$this->language]['name']; ?>" name="<?php echo $gallery['Translation'][$this->language]['name']; ?>">
				     
			    </a>
			    <?php endforeach; ?>
			</div>
			<div class="share-article-body">
				<div class="main-title">
					<h2>Poleć znajomym</h2>
					<span>Poinformuj innych o artykule</span>
				</div>
				<div class="">
					<a href="http://www.facebook.com/share.php?u=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-facebook"><i class="fa fa-facebook"></i><span></span></a>
					<a href="https://twitter.com/share" class="share-body ot-twitter"><i class="fa fa-twitter"></i><span></span></a>
					<a href="https://plusone.google.com/_/+1/confirm?<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-google"><i class="fa fa-google-plus"></i><span></span></a>
					<a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-linkedin"><i class="fa fa-linkedin"></i><span></span></a>
					<a href="http://pinterest.com/pin/create/button/?<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" class="share-body ot-pinterest"><i class="fa fa-pinterest"></i><span></span></a>
				</div>
			</div>
		</div>
    
        </div>

</article>-->

