<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('invoice_payment', 'paid_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('invoice_payment', 'paid_at');
    }
}