<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('invoice_item', 'item_id', 'integer', '4', array(
             ));
        $this->addColumn('invoice_item', 'count', 'integer', '2', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('invoice_item', 'item_id');
        $this->removeColumn('invoice_item', 'count');
    }
}