<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('invoice_invoice', 'execution_start_date', 'timestamp', '25', array(
             ));
        $this->addColumn('invoice_invoice', 'execution_end_date', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('invoice_invoice', 'execution_start_date');
        $this->removeColumn('invoice_invoice', 'execution_end_date');
    }
}