<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('invoice_invoice', 'code', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('invoice_invoice', 'code');
    }
}