<script type="text/javascript">
$(document).ready(function() {
   
    $('#category_id').select2();
    
     $('.section').hide();
     $('.contentSection').show();
     $('.btnList li').click(function(){
        var rel = $(this).attr('rel');
        $('.section').hide();
        $('.'+rel).show();
     });
});
</script>

<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
         <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add attraction') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <ul class="btnList">
                    <li rel="contentSection"><button class="btn" type="button">Treść</button></li>
                    <li rel="optionsSection"><button class="btn" type="button">Opcje</button></li>
                    <li rel="metatagSection"><button class="btn" type="button">Pokaż metatagi</button></li>
                </ul>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <span class="section contentSection metatagSection">
                        <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>

                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                                <span class="section contentSection">
                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->title ?>
                                <?php echo $this->form->translations->getSubForm($language)->content ?>
                            <?php endif; ?>
                                </span>
                                <span class="section metatagSection">
                                    <div class="title" style ="margin-top: 30px;">

                                        <h4>
                                            <span class="icon16 icomoon-icon-pencil"></span>
                                            <span><?php echo $this->translate('Metatags') ?></span>
                                        </h4>

                                    </div>
                                    <div class="content clearfix">
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                    </div>
                                </span>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </span>
                    <span class="section optionsSection">
                        <?php echo $this->form->publish ?>
                        <?php echo $this->form->publish_date->setAttrib('class', 'combiner-picker') ?>
                        <?php echo $this->form->gallery ?>
                        <?php echo $this->form->id ?>
                    </span>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-attraction', 'district') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
                
                
            
            </div>
            
        </div>
        </div>
</div>

