<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('news_article', 'news_article_category_id_news_category_id', array(
             'name' => 'news_article_category_id_news_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'news_category',
             ));
        $this->createForeignKey('news_article_translation', 'news_article_translation_id_news_article_id', array(
             'name' => 'news_article_translation_id_news_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'news_article',
             ));
        $this->createForeignKey('news_article_translation', 'news_article_translation_id_news_article_id_1', array(
             'name' => 'news_article_translation_id_news_article_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'news_article',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('news_category_translation', 'news_category_translation_id_news_article_id', array(
             'name' => 'news_category_translation_id_news_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'news_article',
             ));
        $this->createForeignKey('news_category_translation', 'news_category_translation_id_news_category_id', array(
             'name' => 'news_category_translation_id_news_category_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'news_category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('news_article', 'news_article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('news_article_translation', 'news_article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('news_category_translation', 'news_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('news_article', 'news_article_category_id_news_category_id');
        $this->dropForeignKey('news_article_translation', 'news_article_translation_id_news_article_id');
        $this->dropForeignKey('news_article_translation', 'news_article_translation_id_news_article_id_1');
        $this->dropForeignKey('news_category_translation', 'news_category_translation_id_news_article_id');
        $this->dropForeignKey('news_category_translation', 'news_category_translation_id_news_category_id');
        $this->removeIndex('news_article', 'news_article_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('news_article_translation', 'news_article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('news_category_translation', 'news_category_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}