<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('news_article_translation');
        $this->dropTable('news_category_translation');
        $this->addColumn('news_article', 'title', 'string', '255', array(
             ));
        $this->addColumn('news_article', 'slug', 'string', '255', array(
             ));
        $this->addColumn('news_article', 'content', 'clob', '', array(
             ));
        $this->addColumn('news_article', 'metatag_id', 'integer', '4', array(
             ));
        $this->addColumn('news_category', 'name', 'string', '255', array(
             ));
        $this->addColumn('news_category', 'slug', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->createTable('news_article_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('news_category_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('news_article', 'title');
        $this->removeColumn('news_article', 'slug');
        $this->removeColumn('news_article', 'content');
        $this->removeColumn('news_article', 'metatag_id');
        $this->removeColumn('news_category', 'name');
        $this->removeColumn('news_category', 'slug');
    }
}