<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('news_serwis1_news', 'news_serwis1_news_author_id_default_service_id');
        $this->dropForeignKey('news_serwis1_news', 'news_serwis1_news_last_editor_id_user_user_id');
        $this->dropForeignKey('news_serwis1_news', 'news_serwis1_news_photo_root_id_media_photo_id');
        $this->dropForeignKey('news_serwis1_news', 'news_serwis1_news_video_root_id_media_video_url_id');
        $this->dropForeignKey('news_serwis1_news', 'news_serwis1_news_metatag_id_default_metatag_id');
    }

    public function down()
    {
        $this->createForeignKey('news_serwis1_news', 'news_serwis1_news_author_id_default_service_id', array(
             'name' => 'news_serwis1_news_author_id_default_service_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'default_service',
             ));
        $this->createForeignKey('news_serwis1_news', 'news_serwis1_news_last_editor_id_user_user_id', array(
             'name' => 'news_serwis1_news_last_editor_id_user_user_id',
             'local' => 'last_editor_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('news_serwis1_news', 'news_serwis1_news_photo_root_id_media_photo_id', array(
             'name' => 'news_serwis1_news_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('news_serwis1_news', 'news_serwis1_news_video_root_id_media_video_url_id', array(
             'name' => 'news_serwis1_news_video_root_id_media_video_url_id',
             'local' => 'video_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_video_url',
             ));
        $this->createForeignKey('news_serwis1_news', 'news_serwis1_news_metatag_id_default_metatag_id', array(
             'name' => 'news_serwis1_news_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
    }
}