<?php

/**
 * User_Model_Doctrine_BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $fb_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $username
 * @property string $salt
 * @property string $password
 * @property string $role
 * @property string $token
 * @property boolean $active
 * @property integer $discount_id
 * @property User_Model_Doctrine_Profile $Profile
 * @property Doctrine_Collection $Update
 * @property Doctrine_Collection $Groups
 * 
 * @package    Admi
 * @subpackage User
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Doctrine_BaseUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_user');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('fb_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('salt', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('role', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('discount_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Doctrine_Profile as Profile', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('User_Model_Doctrine_Update as Update', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('User_Model_Doctrine_Group as Groups', array(
             'refClass' => 'User_Model_Doctrine_UserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}