<?php

/**
 * User_Model_Doctrine_GroupTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage User
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_GroupTranslation extends User_Model_Doctrine_BaseGroupTranslation
{

}