<?php

/**
 * User_Model_Doctrine_Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage User
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_Group extends User_Model_Doctrine_BaseGroup
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function isStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function setDiscountId($discountId) {
        $this->_set('discount_id', $discountId);
    }
    
    public function setUp() {    
        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
            'local' => 'discount_id',
            'foregin' => 'id'
        )); 
        parent::setUp();
    }
}