<?php

/**
 * User_Model_Doctrine_GroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_Doctrine_GroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_Doctrine_GroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Doctrine_Group');
    }
    
    public function getGroupQuery() {
        $q = $this->createQuery('gr');
        $q->addSelect('gr.*');
        return $q;
    }
}