<?php

/**
 * User_Model_Doctrine_ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_Doctrine_ProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_Doctrine_ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Doctrine_Profile');
    }
    
    public function getProfileQuery() {
        $q = $this->createQuery('p')
                ->select('p.*')
                ;
        return $q;
    }
    
    public function getFullProfileQuery() {
        $q = $this->createQuery('p')
                ->select('p.*')
                ->addSelect('u.*')
                ->addSelect('pt.*')
                ->addSelect('ptt.*')
                ->addSelect('pc.*')
                ->addSelect('pp.*')
                ->addSelect('pr.*')
                ->leftJoin('p.User u')
                ->leftJoin('p.Tags pt')
                ->leftJoin('pt.Translation ptt')
                ->leftJoin('p.City pc')
                ->leftJoin('p.Province pp')
                ->leftJoin('p.PhotoRoot pr')
                ;
        return $q;
    }
    
    public function getSearchProfileQuery() {
        $q = $this->getFullProfileQuery();
        $q->addSelect('o.*')
                ->addSelect('oc.*')
                ->leftJoin('u.Offers o')
                ->leftJoin('o.Category oc')
                ;
        return $q;
    }
    
    public function getTagFilteredQuery($slug, $language, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->getProfileQuery();
        }
        
        $q->addSelect('t.*');
        $q->leftJoin('p.Tags t');
        $q->leftJoin('t.Translation tt');
        $q->andWhere('(tt.slug = ? AND tt.lang = ?)', array($slug, $language));
        return $q;
    }
}