<?php

/**
 * User_Model_Doctrine_UpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_Doctrine_UpdateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_Doctrine_UpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Doctrine_Update');
    }
    
    public function deleteUserTokensOfType($userId, $type) {
        $q = Doctrine_Query::create()
                ->delete()
                ->from($this->getComponentName())
                ->where('user_id = ?', $userId)
                ->andWhere('type = ?', $type)
                ;
        return $q->execute();
    }
}