<?php

/**
 * User_Model_Doctrine_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage User
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_User extends User_Model_Doctrine_BaseUser implements User_Model_User_Interface
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setFirstName($firstName) {
	$this->_set('first_name', $firstName);
    }

    public function getFirstName() {
	return $this->_get('first_name');
    }

    public function setLastName($lastName) {
	$this->_set('last_name', $lastName);
    }

    public function getLastName() {
	return $this->_get('last_name');
    }

    public function setEmail($email) {
	$this->_set('email', $email);
    }

    public function getEmail() {
	return $this->_get('email');
    }

    public function setSalt($salt) {
        $this->_set('salt', $salt);
    }

    public function getSalt() {
        return $this->_get('salt');
    }

    public function setPassword($password) {
        $this->_set('password', $password);
    }

    public function getPassword() {
        return $this->_get('password');
    }

    public function setRole($role) {
	$this->_set('role', $role);
    }

    public function getRole() {
	return $this->_get('role');
    }

    public function setToken($token) {
	$this->_set('token', $token);
    }

    public function getToken() {
	return $this->_get('token');
    }

    public function setActive($active = true) {
	$this->_set('active', $active);
    }

    public function isActive() {
	return $this->_get('active');
    }
    
    public function isStatus() {
        return $this->_get('active');
    }
    
    public function setStatus($status = true) {
        $this->_set('active', $status);
    }
    
    public function setDiscountId($discountId) {
        $this->_set('discount_id', $discountId);
    }
    
    public function setFbId($fbId){
        $this->_set('fb_id', $fbId);
    }
    
    public function getFbId(){
        $this->_get('fb_id');
    }
    
    public function setUp() {    
        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
            'local' => 'discount_id',
            'foregin' => 'id'
        )); 
        
        $this->hasMany('Product_Model_Doctrine_Comment as Comments', array(
            'local' => 'id',
            'foreign' => 'user_id'
        ));
        
//        $this->hasMany('Order_Model_Doctrine_Order as Orders', array(
//            'local' => 'id',
//            'foreign' => 'user_id'
//        ));
        parent::setUp();
    }
}