<?php

/**
 * User_Model_Doctrine_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User_Model_Doctrine_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object User_Model_Doctrine_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User_Model_Doctrine_User');
    }
    
    public function findOneByConditions($array) {
        if(!empty($array)) {
            $q = $this->createQuery('u');
            $q->select('u.*');
            $haveConditions = false;
            foreach($array as $field => $value) {
                if(in_array($field, array_keys($this->getColumns()))) {
                    if($value === null) {
                        $q->andWhere('u.' . $field . ' IS NULL');
                    } elseif(is_array($value)) {
                        $q->andWhere('u.' . $field . ' IN ?', array($value));
                    } else {
                        $q->andWhere('u.' . $field . ' = ?', array($value));
                    }
                    
                    $haveConditions = true;
                }
            }
            if($haveConditions) {
                return $q->fetchOne();
            }
        }
        return null;
    }
    
    public function getUserQuery() {
        $q = $this->createQuery('u');
        $q->addSelect('u.*');
        $q->addSelect('prof.*');
        $q->leftJoin('u.Profile prof');
        return $q;
    }
    
    public function getClientQuery() {
        $q = $this->createQuery('cli');
        $q->addSelect('cli.*');
        $q->andWhere('cli.role = ?', array('client'));
        return $q;
    }
}