<?php $attraction = $this->attraction;
$photoRoot = $attraction->get('PhotoRoot');
$videoRoot = $attraction->get('VideoRoot');
?>
<div class="block_breadcrumbs">
    <ul>
        <li><a href="/">Strona głowna</a></li>
        <li><a href="<?php echo $this->url(array(),'domain-list-attraction'); ?>">Atrakcje regionu</a></li>
        <li><?php echo $attraction['Translation'][$this->language]['title']; ?></li>
    </ul>
</div>
<div class="separator" style="height:30px;"></div>

<article class="block_single_news">
        <div class="f_pic">
            <a href="#">
                <img src="/media/photos/<?php echo $photoRoot['offset'];?>/610x292/<?php echo $photoRoot['filename'];?>" alt=""></a>
        </div>
  <p class="title"><?php echo $attraction['Translation'][$this->language]['title']; ?></p>
    <!--<p class="subtitle">Many variations of passages of available, but the majority have suffered alteration in some form. Humour, or randomised words which don't look even slightly believable.</p>-->

    <div class="info">
        <div class="date"><p><?php echo MF_Text::polishTimeFormat($attraction['publish_date'],'d M Y H:i'); ?></p></div>
        <div class="author"><p>Autor: <?php echo $attraction['UserCreated']['first_name']." ".$attraction['UserCreated']['last_name']; ?></p></div>

        
    </div>

    <div class="content">
        <?php echo $attraction['Translation'][$this->language]['content']; ?>
    </div>

</article>
<div class="line_3" style="margin:10px 0px 15px;"></div>
<div class="block_related_posts">
        <h3>Galeria</h3>
    <div class="block_main_news">
        <?php foreach($photoRoot->getNode()->getChildren() as $photo): ?>
        <div class="block_news_post">
            <div class="f_pic">
                <a href="/media/photos/<?php echo $photo['offset'];?>/<?php echo $photo['filename'];?>" class='prettyPhoto' rel="<?php echo $attraction['Translation'][$this->language]['slug']; ?>[]" title='<?php echo $attraction['Translation'][$this->language]['title']; ?>' >
                    <img src="/media/photos/<?php echo $photo['offset'];?>/130x130/<?php echo $photo['filename'];?>" alt="">
                </a>
            </div>
        </div>
          <?php endforeach; ?>
        <?php if($videoRoot->getNode()->hasChildren()): ?>
        <h3>Video</h3>
            <?php foreach($videoRoot->getNode()->getChildren() as $video): ?>
            <div class="block_video">
                <iframe width="612" height="344" src="<?php echo $video->url; ?>" frameborder="0" allowfullscreen=""></iframe>
            </div>
              <?php endforeach; ?>

        <?php endif; ?>


        <div class="clearboth"></div>
    </div>
</div>
<div class="separator" style="height:30px;"></div>

<div class="block_post_tags">
        <!--<p>Tags: <a href="#">business,</a><a href="#">stock market</a></p>-->
</div>

<div class="block_post_social">


    <section class="recommend" style="float:none;margin:0 auto;display:lock;">
        <p class="title"><span>Poleć znajomym</span></p>

        <ul>
            <li><a href="http://www.facebook.com/share.php?u=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" target="_blank"><img src="/assets/images/button_social_1.png" alt=""></a></li>
            <li><a href="https://twitter.com/share" target="_blank"><img src="/assets/images/button_social_2.png" alt=""></a></li>
            <li><a href="https://plusone.google.com/_/+1/confirm?url=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" target="_blank"><img src="/assets/images/button_social_3.png" alt=""></a></li>
            <li><a href="http://pinterest.com/pin/create/button/?url=<?php echo "http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]; ?>" target="_blank"><img src="/assets/images/button_social_4.png" alt=""></a></li>
        </ul>
    </section>

    <div class="clearboth"></div>
</div>

<div class="line_2" style="margin:22px 0px 29px;"></div>


         