<?php

/**
 * Admin_Model_Doctrine_MessageRegistry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Admin
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Doctrine_MessageRegistry extends Admin_Model_Doctrine_BaseMessageRegistry
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setMessageId($messageId) {
        $this->_set('message_id', $messageId);
    }
    
    public function getMessageId() {
        return $this->_get('message_id');
    }
    
    public function setUserId($userId) {
        $this->_set('user_id', $userId);
    }
    
    public function getUserId() {
        return $this->_get('user_id');
    }
    
}