<?php

/**
 * Default_Model_Doctrine_BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $value
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Doctrine_BaseSetting extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default_setting');
        $this->hasColumn('id', 'string', 255, array(
             'primary' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value', 'string', 1024, array(
             'type' => 'string',
             'length' => '1024',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}