<?php

/**
 * Default_Model_Doctrine_BasePhotoDimensions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property int $width
 * @property int $height
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Doctrine_BasePhotoDimensions extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default_photo_dimensions');
        $this->hasColumn('id', 'string', 255, array(
             'primary' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('width', 'int', 11, array(
             'type' => 'int',
             'length' => '11',
             ));
        $this->hasColumn('height', 'int', 11, array(
             'type' => 'int',
             'length' => '11',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}