<?php

/**
 * Default_Model_Doctrine_BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $name
 * @property clob $email
 * @property clob $phone
 * @property clob $address
 * @property clob $opening
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Doctrine_BaseService extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default_service');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('email', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('phone', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('address', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('opening', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}