<?php

/**
 * Default_Model_Doctrine_CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_Doctrine_CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_Doctrine_CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_Doctrine_City');
    }
    
    public function getCityQuery(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('c');
        }
        return $q;
    }
}