<?php

/**
 * Default_Model_Doctrine_City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Doctrine_City extends Default_Model_Doctrine_BaseCity
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setName($name) {
        $this->_set('name', $name);
    }
    
    public function getName() {
        return $this->_get('name');
    }
    
    public function setProvinceId($provinceId) {
        $this->_set('province_id', $provinceId);
    }
    
    public function getProvinceId() {
        return $this->_get('province_id');
    }
}