<?php

/**
 * Default_Model_Doctrine_Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Doctrine_Language extends Default_Model_Doctrine_BaseLanguage implements Default_Model_LanguageInterface 
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setName($name) {
        $this->_set('name', $name);
    }
    
    public function getName() {
        return $this->_get('name');
    }
    
    public function setActive($active = true) {
        $this->_set('active', $active);
    }
    
    public function isActive() {
        return $this->_get('active');
    }
    
    public function setDefault($default = true) {
        $this->_set('default', $default);
    }
    
    public function isDefault() {
        return $this->_get('default');
    }
    
    public function setAdmin($admin = true) {
        $this->_set('admin', $admin);
    }
    
    public function isAdmin() {
        return $this->_get('admin');
    }
}