<?php

/**
 * Default_Model_Doctrine_MetatagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_Doctrine_MetatagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_Doctrine_MetatagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_Doctrine_Metatag');
    }
    public function getMetatagsQuery() {
        $q = $this->createQuery('m')
                ->select('m.*')
                ->addSelect('mt')
                ->leftJoin('m.Translation mt')
                ;
        return $q;
    }
}
