<?php

/**
 * Default_Model_Doctrine_Metatag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Doctrine_Metatag extends Default_Model_Doctrine_BaseMetatag
{
    public static $types = array(
        'title' => 'Title',
        'description' => 'Description',
        'keywords' => 'Keywords'
    );
    
    public static function getAvailableTypes() {
        return self::$types;
    }
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setType($type) {
        $this->_set('type', $type);
    }
    
    public function getType() {
        return $this->_get('type');
    }
    
    public function setContent($content) {
        $this->_set('content', $content);
    }
    
    public function getContent() {
        return $this->_get('content');
    }
}