<?php

/**
 * Default_Model_Doctrine_Metatag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Doctrine_Newsletter extends Default_Model_Doctrine_BaseNewsletter
{
    public function getId() {
        return $this->_get('id');
    }
}