<?php

/**
 * Default_Model_Doctrine_ProvinceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_Doctrine_ProvinceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_Doctrine_ProvinceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_Doctrine_Province');
    }
    
    public function getProvinceQuery(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('p');
        }
        return $q;
    }
}