<?php

/**
 * Default_Model_Doctrine_Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Default
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Default_Model_Doctrine_Tag extends Default_Model_Doctrine_BaseTag
{
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_ProfileTag as ProfileTag', array(
            'local' => 'id',
            'foreign' => 'tag_id' 
        ));
    }
}