<?php

/**
 * Default_Model_Doctrine_TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Default_Model_Doctrine_TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Default_Model_Doctrine_TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Default_Model_Doctrine_Tag');
    }
    
    public function getTagQuery($language) {
        $q = $this->createQuery('t')
                ->addSelect('t.*')
                ->addSelect('tt.*')
                ->leftJoin('t.Translation tt')
                ->andWhere('tt.lang = ?', $language)
                ;
        return $q;
    }
    
}