<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('default_language', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '64',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'default' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'admin' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('default_setting', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '255',
             ),
             'numeric' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'text' => 
             array(
              'type' => 'string',
              'length' => '1024',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('default_language');
        $this->dropTable('default_setting');
    }
}