<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('default_setting', 'numeric');
        $this->removeColumn('default_setting', 'text');
        $this->addColumn('default_setting', 'value', 'string', '1024', array(
             ));
    }

    public function down()
    {
        $this->addColumn('default_setting', 'numeric', 'integer', '4', array(
             ));
        $this->addColumn('default_setting', 'text', 'string', '1024', array(
             ));
        $this->removeColumn('default_setting', 'value');
    }
}