<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('newsletter');
        $this->dropTable('default_metatag_translation');
        $this->createTable('default_tag_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('default_service', 'openinghours');
        $this->removeColumn('default_tag', 'name');
        $this->removeColumn('default_tag', 'slug');
        $this->addColumn('default_metatag', 'title', 'string', '255', array(
             ));
        $this->addColumn('default_metatag', 'description', 'clob', '', array(
             ));
        $this->addColumn('default_metatag', 'keywords', 'clob', '', array(
             ));
        $this->addColumn('default_service', 'opening', 'type:clob', '', array(
             ));
    }

    public function down()
    {
        $this->createTable('newsletter', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('default_metatag_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'keywords' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('default_tag_translation');
        $this->addColumn('default_service', 'openinghours', 'type:clob', '', array(
             ));
        $this->addColumn('default_tag', 'name', 'string', '255', array(
             ));
        $this->addColumn('default_tag', 'slug', 'string', '255', array(
             ));
        $this->removeColumn('default_metatag', 'title');
        $this->removeColumn('default_metatag', 'description');
        $this->removeColumn('default_metatag', 'keywords');
        $this->removeColumn('default_service', 'opening');
    }
}