<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('default_tag_translation', 'default_tag_translation_id_default_tag_id_1', array(
             'name' => 'default_tag_translation_id_default_tag_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'default_tag',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('default_tag_translation', 'default_tag_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('default_tag_translation', 'default_tag_translation_id_default_tag_id_1');
        $this->removeIndex('default_tag_translation', 'default_tag_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}