<?php

/**
 * Newsletter_Model_Doctrine_BaseSent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property integer $subscriber_id
 * @property integer $group_id
 * @property timestamp $send_at
 * @property boolean $sent
 * @property Newsletter_Model_Doctrine_Message $Message
 * @property Newsletter_Model_Doctrine_Subscriber $Subscriber
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseSent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_sent');
        $this->hasColumn('id', 'integer', 6, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('message_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('subscriber_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('send_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('sent', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Newsletter_Model_Doctrine_Message as Message', array(
             'local' => 'message_id',
             'foreign' => 'id'));

        $this->hasOne('Newsletter_Model_Doctrine_Subscriber as Subscriber', array(
             'local' => 'subscriber_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}