<?php

/**
 * Newsletter_Model_Doctrine_GroupSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newsletter_Model_Doctrine_GroupSubscriber extends Newsletter_Model_Doctrine_BaseGroupSubscriber
{
    public function setGroupId($groupId) {
	$this->_set('group_id', $groupId);
    }
    
    public function setSubscriberId($subscriberId) {
	$this->_set('subscriber_id', $subscriberId);
    }
}