<?php

/**
 * Newsletter_Model_Doctrine_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newsletter_Model_Doctrine_Message extends Newsletter_Model_Doctrine_BaseMessage
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function getContent() {
        return $this->_get('content');
    }
    
    public function setUp() {
       
        $this->hasMany('Product_Model_Doctrine_Product as ProductMessages', array(
             'refClass' => 'Newsletter_Model_Doctrine_MessageProduct',
             'local' => 'message_id',
             'foreign' => 'product_id'
        ));
        
        parent::setUp();
    }
    
    
}