<?php

/**
 * Newsletter_Model_Doctrine_SentMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newsletter_Model_Doctrine_SentMessage extends Newsletter_Model_Doctrine_BaseSentMessage
{
    public function setSubscriberId($subscriberId) {
        $this->_set('subscriber_id', $subscriberId);
    }
    
    public function setMessageId($messageId) {
        $this->_set('message_id', $messageId);
    }
    
    public function setGroupId($groupId) {
        $this->_set('group_id', $groupId);
    }
    
    public function setSentAt($sentAt) {
        $this->_set('sent_at', $sentAt);
    }
    
    public function setSent($sent = true) {
        $this->_set('sent', $sent);
    }
    
    public function setError($error) {
        $this->_set('error', $error);
    }
    
    public function isSent() {
        return $this->_get('sent');
    }
}