<?php

/**
 * Newsletter_Model_Doctrine_SubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Newsletter_Model_Doctrine_SubscriberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Newsletter_Model_Doctrine_SubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletter_Model_Doctrine_Subscriber');
    }
    
    public function getSubscriberQuery() {
        $q = $this->createQuery('s');
        $q->addSelect('s.*');
        return $q;
    }
}