<?php

/**
 * League_Model_Doctrine_BaseShooter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $match_id
 * @property integer $player_id
 * @property integer $goal
 * @property League_Model_Doctrine_Player $Player
 * @property Doctrine_Collection $Match
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class League_Model_Doctrine_BaseShooter extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('league_shooter');
        $this->hasColumn('match_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('player_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('goal', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('League_Model_Doctrine_Player as Player', array(
             'local' => 'player_id',
             'foreign' => 'id'));

        $this->hasMany('League_Model_Doctrine_Match as Match', array(
             'local' => 'match_id',
             'foreign' => 'id'));
    }
}