<?php

/**
 * League_Model_Doctrine_BaseLeague
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property boolean $active
 * @property integer $group_id
 * @property Doctrine_Collection $Team
 * @property Doctrine_Collection $Matches
 * @property Doctrine_Collection $Tabela
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class League_Model_Doctrine_BaseLeague extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('league_league');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('League_Model_Doctrine_Team as Team', array(
             'local' => 'id',
             'foreign' => 'league_id'));

        $this->hasMany('League_Model_Doctrine_Match as Matches', array(
             'local' => 'id',
             'foreign' => 'league_id'));

        $this->hasMany('League_Model_Doctrine_Tabela as Tabela', array(
             'local' => 'id',
             'foreign' => 'league_id'));
    }
}