<?php

/**
 * League_Model_Doctrine_BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property integer $league_id
 * @property boolean $my_team
 * @property integer $logo_id
 * @property integer $teamphoto_id
 * @property League_Model_Doctrine_League $League
 * @property Doctrine_Collection $Matches1
 * @property League_Model_Doctrine_Tabela $Tabela
 * @property League_Model_Doctrine_Coach $Coach
 * @property Doctrine_Collection $Players
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class League_Model_Doctrine_BaseTeam extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('league_team');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('league_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('my_team', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('logo_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('teamphoto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('League_Model_Doctrine_League as League', array(
             'local' => 'league_id',
             'foreign' => 'id'));

        $this->hasMany('League_Model_Doctrine_Match as Matches1', array(
             'local' => 'id',
             'foreign' => 'team1'));

        $this->hasOne('League_Model_Doctrine_Tabela as Tabela', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasOne('League_Model_Doctrine_Coach as Coach', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('League_Model_Doctrine_Player as Players', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}