<?php

/**
 * League_Model_Doctrine_Match
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class League_Model_Doctrine_Match extends League_Model_Doctrine_BaseMatch
{
    public function setGoal1($value){
        $this->_set('goal1',$value);
    }
    
    public function setGoal2($value){
        $this->_set('goal2',$value);
    }
    
    public function setPlayed($value=true){
        $this->_set('played',$value);
    }
    
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('League_Model_Doctrine_Team as Team2', array(
             'local' => 'team2',
             'foreign' => 'id'));

    }
}   