<?php

/**
 * League_Model_Doctrine_Tabela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class League_Model_Doctrine_Tabela extends League_Model_Doctrine_BaseTabela
{

}