<?php

/**
 * League_Model_Doctrine_Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage League
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class League_Model_Doctrine_Team extends League_Model_Doctrine_BaseTeam
{
    public function setUp()
    {
        parent::setUp();
        
        $this->hasMany('League_Model_Doctrine_Match as Matches2', array(
             'local' => 'id',
             'foreign' => 'team2'));
        
        $this->hasOne('Media_Model_Doctrine_Photo as Logo', array(
             'local' => 'logo_id',
             'foreign' => 'id'));
        
        $this->hasOne('Media_Model_Doctrine_Photo as TeamPhoto', array(
             'local' => 'teamphoto_id',
             'foreign' => 'id'));
    }
    
    public function getId(){
        return $this->_get('id');
    }
    
    public static $photoDimensions = array(
        '126x126' => 'Photo in admin panel', // admin
        '127x127' => 'Logo klubu'
    );
    
    public static $teamPhotoDimensions = array(
        '126x126' => 'Photo in admin panel', // admin
        '940x511' => 'Zdjęcie klubowe'
    );

    public static function getPhotoDimensions() {
        return self::$photoDimensions;
    } 
    
    public static function getTeamPhotoDimensions() {
        return self::$teamPhotoDimensions;
    } 
    
}