<!--content-->
<section class="page_title_2 translucent_bg_color_scheme image_fixed image_bg_9 t_align_c relative wrapper">
	<div class="container">
		<h1 class="color_light fw_light m_bottom_5"><?php echo $this->translate('Contact') ?></h1>
		<!--breadcrumbs-->
		<ul class="hr_list d_inline_m breadcrumbs">
			<li class="m_right_8 f_xs_none"><a href="/" class="color_grey_light_3 d_inline_m m_right_10">Strona główna</a><i class="icon-angle-right d_inline_m color_grey_light_3 fs_small"></i></li>
			<li><a class="color_grey_light_3 d_inline_m"><?php echo $this->translate('Contact') ?></a></li>
		</ul>
	</div>
</section>
<section class="section_offset">
	<div class="container clearfix">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_30">
				<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c"><?php echo $this->translate('Contact Details') ?></h3>
				<?php echo $this->page['Translation'][$this->language]['content']; ?>
				<div class="row m_top_20">
					<ul class="col-lg-6 col-md-6 col-sm-6 fw_light w_break m_bottom_45 m_xs_bottom_30">
						<li class="m_bottom_8">
							<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
								<i class="icon-phone-1"></i>
							</div>
							<?php echo $this->cms()->setting('phone'); ?>
						</li>
						<li class="m_bottom_8">
							<div class="d_inline_m icon_wrap_size_1 color_pink circle m_right_10">
								<i class="icon-mail-alt"></i>
							</div>
							<a href="mailto:<?php echo $this->cms()->setting('email'); ?>" class="color_black color_pink_hover"><?php echo $this->cms()->setting('email'); ?></a>
						</li>
					</ul>
					<ul class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_30 vr_list_type_5">
						<li class="m_bottom_8 fw_light">
							<div class="f_left icon_wrap_size_1 color_pink circle">
								<i class="icon-location"></i>
							</div>
							<?php echo $this->cms()->setting('address'); ?>, <?php echo $this->cms()->setting('city'); ?>, <?php echo $this->cms()->setting('post_code'); ?>.
						</li>
					</ul>
				</div>
				<h5 class="color_dark m_bottom_20 fw_light">Śledź nas na bieżąco</h5>
				<ul class="hr_list social_icons">
					<!--tooltip_container class is required-->
					<li class="m_right_15 m_bottom_15 tooltip_container">
						<!--tooltip-->
						<span class="d_block r_corners color_default tooltip fs_small tr_all">Follow Us on Facebook</span>
						<a href="<?php echo $this->cms()->setting('facebook_url'); ?>" class="d_block facebook icon_wrap_size_2 circle color_grey_light_2">
							<i class="icon-facebook fs_small"></i>
						</a>
					</li>
					<li class="m_right_15 m_bottom_15 tooltip_container">
						<!--tooltip-->
						<span class="d_block r_corners color_default tooltip fs_small tr_all">Instagram</span>
						<a href="<?php echo $this->cms()->setting('instagram_url'); ?>" class="d_block instagram icon_wrap_size_2 circle color_grey_light_2">
							<i class="icon-instagramm fs_small"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 m_xs_bottom_30">
				<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c"><?php echo $this->translate('Contact Form') ?></h3>
				<p class="m_bottom_35 heading_2 t_align_c"> </p>		
				<form id="contactform">
					<ul>
						<li class="row m_bottom_10">
							<div class="col-lg-6 col-md-6 col-sm-6 w_xs_full m_xs_bottom_10">
							    <?php echo $this->form->name ?>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 w_xs_full">
							    <?php echo $this->form->email ?>	
							</div>
						</li>
						<li class="m_bottom_10">
							<?php echo $this->form->subject ?>	
						</li>
						<li class="m_bottom_5">
							<?php echo $this->form->message ?>
						</li>
						<?php if($this->form->captcha): ?>
						<li class="m_bottom_20">
						   <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 captcha-wrapper">
						       <?php echo $this->form->csrf ?>
						       <div class="controls captcha">
							   <?php echo $this->form->captcha ?>
						       </div>
						       <div class="control-group">
							   <div class="controls">
								<a href="#" id="reload-captcha"><img src="/images/layout/reload_refresh.png" style="padding-top: 22px;"/></a>
							   </div>
						       </div>
						   </div>
						    <div class="clearfix"></div>
						</li>
					       <?php endif; ?>
						<li class="m_bottom_10 m_top_20">
							<button name="send_contact" class="button_type_5 color_blue transparent r_corners fs_medium tr_all m_right_10 m_sm_bottom_10">Submit</button>
						</li>
						
					</ul>
				</form>
			</div>
		</div>
	</div>
</section>