<div id="Banner" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-body">
                	<div class="col-lg-7 col-md-7 col-sm-12">
                    	<h3><?php echo $this->page['Translation'][$this->language]['title']; ?></h3>
                        <?php echo $this->page['Translation'][$this->language]['content']; ?>
                        <form id="newsletter-modal" method="POST">
                            <input type="text" size="6" placeholder="Enter email address." name="email" id="subscribe-modal">
                            <input type="hidden" name="add_subscriber" >
                            <button class="btn btn-default" id="add_subscriber">Subscribe</button>
                        </form>
                    </div>
           					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				</div><!-- end modal body -->
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
    
	<div id="myModal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel"><strong>Login Account</strong></h4>
				</div><!-- end modal header -->
                
				<div class="modal-body">
                    <form class="form-horizontal" role="form">
                      <div class="form-group">
                        <label for="inputEmail3" class="col-sm-4 control-label">User name</label>
                        <div class="col-sm-8">
                          <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputPassword3" class="col-sm-4 control-label">Password</label>
                        <div class="col-sm-8">
                          <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                        </div>
                      </div>                
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-9">
                          <label class="radio-inline">
                            <input type="radio" id="inlineCustomRadio" name="radio"><span class="pseudo-input"></span> Remember me
                          </label>
                        </div>
                      </div>
                    </form>
				</div><!-- end modal body -->
				<div class="modal-footer">                    
					<button type="button" class="btn btn-default">Login</button> <button type="button" class="btn btn-default">Register</button>
				</div><!-- end modal footer -->
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->