<header>
    <div class="topMeta"> 
        <form action="" method="get" enctype="application/x-www-form-urlencoded">
        <?php echo $this->form->phrase; ?>
        </form>
<!--        <input type="text" class="search" />-->
            <ul class="social">
                <li class="tt"><a href="#"></a></li>
                <li class="fb"><a href="#"></a></li>
                <li class="gp"><a href="#"></a></li>
            </ul>
    </div>