<?php

/**
 * Banner_Model_Doctrine_BannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Banner_Model_Doctrine_BannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Banner_Model_Doctrine_BannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banner_Model_Doctrine_Banner');
    }
}