<?php

/**
 * Banner_Model_Doctrine_BannerRightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Banner_Model_Doctrine_BannerRightTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Banner_Model_Doctrine_BannerRightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banner_Model_Doctrine_BannerRight');
    }
    
    public function getBannerQuery() {
        $q = $this->createQuery('b')
                ->select('b.*')
                ->addSelect('pr.*')
                ->leftJoin('b.PhotoRoot pr')
                ->andWhere('b.level > ?', 0)
                ->andWhere('(b.start_display_date <= ? AND b.end_display_date >= ?)', array(date('Y-m-d H:i:s'), date('Y-m-d H:i:s')))
                ->addOrderBy('b.lft ASC')
                ;
        return $q;
    }
}