<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('media_photo', 'offset', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('media_photo', 'offset');
    }
}