<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('media_attachment_translation', 'media_attachment_translation_id_media_attachment_id', array(
             'name' => 'media_attachment_translation_id_media_attachment_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'media_attachment',
             ));
        $this->createForeignKey('media_attachment_translation', 'media_attachment_translation_id_media_attachment_id_1', array(
             'name' => 'media_attachment_translation_id_media_attachment_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'media_attachment',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('media_attachment_translation', 'media_attachment_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('media_attachment_translation', 'media_attachment_translation_id_media_attachment_id');
        $this->dropForeignKey('media_attachment_translation', 'media_attachment_translation_id_media_attachment_id_1');
        $this->removeIndex('media_attachment_translation', 'media_attachment_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}