<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('media_attachment_translation');
        $this->removeColumn('media_attachment', 'product_id');
        $this->removeColumn('media_attachment', 'created_at');
        $this->addColumn('media_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('media_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('media_attachment', 'description', 'clob', '', array(
             ));
        $this->addColumn('media_attachment', 'root_id', 'integer', '8', array(
             ));
        $this->addColumn('media_attachment', 'lft', 'integer', '4', array(
             ));
        $this->addColumn('media_attachment', 'rgt', 'integer', '4', array(
             ));
        $this->addColumn('media_attachment', 'level', 'integer', '2', array(
             ));
    }

    public function down()
    {
        $this->createTable('media_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('media_attachment', 'product_id', 'integer', '4', array(
             ));
        $this->addColumn('media_attachment', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->removeColumn('media_attachment', 'title');
        $this->removeColumn('media_attachment', 'slug');
        $this->removeColumn('media_attachment', 'description');
        $this->removeColumn('media_attachment', 'root_id');
        $this->removeColumn('media_attachment', 'lft');
        $this->removeColumn('media_attachment', 'rgt');
        $this->removeColumn('media_attachment', 'level');
    }
}