<div id="banner" class="banner">
    <div class="frame">
        <div class="viewport">
            <div class="inner">
                <div class="slide">
                    <img src="/images/layout/ext/banner01a.jpg" alt="" />
                    <div class="descr">
                        <header>Zmiana ekspozycji</header>
                            <p>Zapraszamy do zwiedzenia naszych budynków wystawowych, już od listopada prezentujemy nowe modele naszych produktów</p>
                        </div>
                </div>
                <div class="slide">
                    <img src="/images/layout/ext/banner01b.jpg" alt="" />
                    <div class="descr">
                        <header>Kuchenne inspiracje</header>
                            <p>Zapraszamy do zwiedzenia naszych budynków wystawowych, już od listopada prezentujemy nowe modele naszych produktów</p>
                    </div>
                </div>
             </div>
         </div>
     </div>
    <div class="overlay">
        <div class="bannerDots"></div>
    </div>
</div>