		<div id="copyright" class="col-full">
            <div class="container">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div id="copyrighttext" class="pull-left">
                        <p>© 2014 BodyEmpire LTD. Designed by <a href="http://www.connectclick.co.uk/" target="_blank">ConnectClick</a></p>
                    </div>
                </div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div id="credit" class="pull-right">
                        <p><img src="/images/layout/payments.png" alt="" /></p>		
                    </div>
                </div>
            </div><!-- end container -->
		</div><!-- end copyright -->