<meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
<?php echo $this->headTitle()->truncate() ?>
<?php echo $this->headMeta() ?>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="author" content="ConnectClick VArts">
<link rel="stylesheet" href="/assets/css/font-awesome.css">
<link rel="stylesheet" href="/assets/css/bootstrap.css"> 
<link rel="stylesheet" href="/css/style.css">
<link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/plugins/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.css">
<link rel="stylesheet" href="/css/print.css" type="text/css" media="print" />
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<script src="/js/jquery-1.10.2.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

<script>
    window.oncontextmenu = function () {
   return false;
}
</script>
