<nav>
    <ul>
        <?php echo $this->navigation()->menu($this->maincontainer)->render() ?>
       <!-- <li><a href="#" class="homeW">&nbsp;</a></li>
        <li><a href="#">AKTUALNOŚCI</a></li>
        <li><a href="#">RZEMIOSŁO KALWARYJSKIE</a></li>
        <li><a href="#">SPRAWY CECHOWE </a></li>
        <li><a href="#">WYSTAWA MEBLI</a></li>
        <li><a href="#">KONTAKT</a></li>
       -->
    </ul>
</nav>