<div id="message">
    Zapraszamy w niezwykła podróż po królestwie światła...<br />
    <br />
    W naszej kolekcji znajdziecie Państwo zjawiskowe lampy, które<br />
    odmienią wnętrze, nadając mu ponadczasowy charakter.<br />
    Lampy, dzięki którym po zachodzie słońca, przestrzeń nadal emanuje<br />
     subtelnym ciepłem, gdzie gra światła i cieni hipnotyzuje i urzeka.<br />
    Niepowtarzalny wygląd naszej kolekcji czaruje rzeczywistość,<br />
    a limity wyznacza jedynie wyobraźnia kreatorów.<br />
    <br />
    Zapraszamy Państwa, do odkrywania naszej niezwykłej kolekcji...<br />
    Lucoa<br />
</div>