<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
        <div class="box">
            
            
                    <?php if($this->form->isErrors()): ?>
                    <div class="message error closeable">
                        <span class="message-close"></span>
                        <h3><?php echo $this->translate('Error') ?>!</h3>
                    </div>
                    <?php endif; ?>
                    <?php if($this->messages()->count()): ?>
                    <?php echo $this->messages()->render() ?>
                    <?php endif; ?>

            <div class="content">
                    <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>

                        <?php echo $this->form->parent_id ?>
                        <?php echo $this->form->name ?>
                        <?php echo $this->form->href ?>
                        <?php echo $this->form->start_display_date->setAttrib('class', 'combiner-picker') ?>
                        <?php echo $this->form->end_display_date->setAttrib('class', 'combiner-picker') ?>
                        
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('list-banner-left', 'banner') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            </div>
        </div>
</div>