<script type="text/javascript">
$(document).ready(function() { 
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
    
    $("#itemContainer").delegate(".actionBtn .edit", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-banner-photo', 'banner') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-banner-photo', 'banner') ?>/id/"+$('#id').val(),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                    $("#itemContainer").trigger('update');
                }
            }
        });
    });
    
    
    $("#recipe_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            Rodzaje bannerów: <br />
           
            Over news (660x90px) - nad lista newsow(strona glowna)<br />
            Banner right(240x150) - po prawej stronie<br />
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit banner') ?> <?php echo $this->banner->Translation[$this->language]->name ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    
                    <div class="page-header">
                        <h4><?php echo $this->translate('Translations') ?></h4>
                    </div>
                    
                    <ul id="myTab" class="nav nav-tabs pattern">
                        <li class="dropdown">
                            <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                            <?php endforeach; ?>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <?php foreach($this->languages as $key => $language): ?>
                        <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                        <?php if($this->form->translations->getSubForm($language)): ?>
                            <?php echo $this->form->translations->getSubForm($language)->name ?>
                        <?php endif; ?>
                        <?php /*    
                         <div class="title" style ="margin-top: 30px;">

                            <h4>
                                <span class="icon16 icomoon-icon-pencil"></span>
                                <span><?php echo $this->translate('Metatags') ?></span>
                            </h4>

                        </div>
                            
                      <div class="content clearfix">
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                       </div>
                       */ ?>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    
                    <?php echo $this->form->photo ?>
                    <?php echo $this->form->date_from ?>
                    <?php echo $this->form->date_to ?>
                    <?php echo $this->form->position ?>
                    <?php echo $this->form->website ?>
                    <?php echo $this->form->id ?>
                    
                    <div class="page-header">
                        <h4><?php echo $this->translate('Main photo') ?></h4>
                    </div>
                    <div id="itemContainer">
                        <ul id="main_photo_container" class="galleryView center">
                            <li class="pull-left">
                                
                                <a id="main_photo" href="/media/attachments/<?php echo $this->banner['AttachmentRoot']['filename']; ?>" rel="prettyPhoto" title="">
                                    <img src="/media/attachments/<?php echo $this->banner['AttachmentRoot']['filename']; ?>" alt="">
                                </a>
                                
                            </li>
                        </ul>
                    </div>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-banner', 'banner') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
    </div>   
</div> 
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
    