<?php

/**
 * District_Model_Doctrine_EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class District_Model_Doctrine_EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object District_Model_Doctrine_EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('District_Model_Doctrine_Event');
    }
    
     public function getPublishEventQuery() {
        $q = $this->createQuery('e')
                ->addSelect('e.*')
                ->addSelect('et.*')
                ->addSelect('pr.*')
                ->addSelect('p.*')
                ->leftJoin('e.Translation et')
                ;
        
        $q->leftJoin('e.PhotoRoot pr');
        $q->leftJoin('e.Photos p');
//        $q->addWhere('e.publish = 1');
//        $q->addWhere('e.publish_date >= NOW()');
        return $q;
    } 
    
     public function getNextEventQuery() {
        $q = $this->createQuery('e')
                ->leftJoin('e.Translation et')
                ;
        
        return $q;
    } 
}