<?php

/**
 * District_Model_Doctrine_EventTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class District_Model_Doctrine_EventTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object District_Model_Doctrine_EventTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('District_Model_Doctrine_EventTranslation');
    }
}