<?php

/**
 * District_Model_Doctrine_EventTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage District
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class District_Model_Doctrine_EventTranslation extends District_Model_Doctrine_BaseEventTranslation
{

}