<?php

/**
 * District_Model_Doctrine_PeopleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class District_Model_Doctrine_PeopleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object District_Model_Doctrine_PeopleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('District_Model_Doctrine_People');
    }
    
     public function getPublishPeopleQuery() {
        $q = $this->createQuery('pp')
                ->addSelect('pp.*')
                ->addSelect('ppt.*')
                ->addSelect('pr.*')
                ->addSelect('p.*')
                ->leftJoin('pp.Translation ppt')
                ;
        
        $q->leftJoin('pp.PhotoRoot pr');
        $q->leftJoin('pp.Photos p');
//        $q->addWhere('e.publish = 1');
//        $q->addWhere('e.publish_date >= NOW()');
        return $q;
    } 
}