<section class="profile span8">
    <header class="row-fluid">
        <h3 class="span8"><?php echo $this->translate('Banners') ?></h3>
        <span class="span4"><a href="<?php echo $this->url(array('action' => 'banners-new'), 'domain-user-profile') ?>" class="btn btn-small btn-success pull-right"><?php echo $this->translate('New banner') ?></a></span>
    </header>
    
    <?php if(isset($this->paginator)): ?>
    <div class="accordion" id="accordion2">
        <?php $i = 0; foreach($this->paginator as $banner): ?>
        <div class="accordion-group">
            <div class="accordion-heading list-header clearfix">
                <a class="accordion-toggle span11" data-parent="#accordion2" href="<?php echo $this->url(array('action' => 'banners-show', 'banner-id' => $banner['id'])) ?>">
                    <span class="span12"><?php echo $banner['name'] ?></span>
                </a>
                <span class="options pull-right">
                    <div class="btn-group batch-process">
                        <span class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></span>
                        <ul class="dropdown-menu">
                            <a class="btn btn-link" href="<?php echo $this->url(array('action' => 'banners-edit', 'banner-id' => $banner['id']), 'domain-user-profile') ?>"><?php echo $this->translate('Edit') ?></a><br />
                            <a class="btn btn-link" href="<?php echo $this->url(array('action' => 'banners-remove', 'banner-id' => $banner['id']), 'domain-user-profile') ?>"><?php echo $this->translate('Remove') ?></a><br />
                        </ul>
                    </div>
                </span>
            </div>
            <div id="collapse" class="accordion-body collapse">
            </div>
        </div>
        <?php $i++; endforeach; ?>
    </div>
    <div class="pagination">
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'profile_pagination_control.phtml'); ?>
    </div>  
    <?php endif; ?>
    
</section>