
<script type="text/javascript" src="/js/bootstrap/bootstrap.js"></script>  
     
<script type="text/javascript">
$(document).ready(function(){
  
   //google maps producer
    if (typeof(google) != "undefined"){
        var lng = $("#cord_x").val();
        var lat = $("#cord_y").val();

        var mapCenter = new google.maps.LatLng(lat, lng); // London
    //    var mapCenter = new google.maps.LatLng(51.507335,-0.127683); // London

        var mapOptions = {
            zoom: 12,
            mapCenter: mapCenter,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        var markers = [];
        function cleanMarkers() {
            for(marker in markers) {
                markers[marker].setMap(null);
            }
        }

        var map = new google.maps.Map(document.getElementById("google-map"), mapOptions);
        google.maps.event.trigger(map, 'resize');
        map.setCenter(mapCenter);

        google.maps.event.addListener(map, 'click', function(e) {

            mapCenter = new google.maps.LatLng(e.latLng.lat(), e.latLng.lng());
            $("#cord_x").val(e.latLng.lng());
            $("#cord_y").val(e.latLng.lat());
            cleanMarkers();
            var marker = new google.maps.Marker({
                map: map, position: mapCenter, draggable: true
            });
            google.maps.event.addListener(marker, 'dragend', function() {
                $("#cord_x").val(marker.getPosition().lng());
                $("#cord_y").val(marker.getPosition().lat());
                mapCenter = new google.maps.LatLng(marker.getPosition().lat(), marker.getPosition().lng());
                map.setCenter(mapCenter);
            });
            markers.push(marker);
            map.setCenter(mapCenter);
        });
        var marker = new google.maps.Marker({
            map: map, position: mapCenter, draggable: true
        });
        google.maps.event.addListener(marker, 'dragend', function() {
            $("#cord_x").val(marker.getPosition().lng());
            $("#cord_y").val(marker.getPosition().lat());
            mapCenter = new google.maps.LatLng(marker.getPosition().lat(), marker.getPosition().lng());
            map.setCenter(mapCenter);
        });
        markers.push(marker);

        var geocoder = new google.maps.Geocoder();
        var address;

        $("#google-map").bind("address_changed", function() {
            // var cityOption = $("form #city_id").find("option[value="+$("form #city_id").val()+"]");
            // var cityString = $(cityOption).attr("label");
            var cityString = $("form #city").val();
            //var provinceOption = $("form #province_id").find("option[value="+$("form #province_id").val()+"]");
            //var provinceString = $(provinceOption).attr("label");
            var provinceString = $("form #province").val();
            var addressString = $("form #address").val();     
            var locationString = addressString + ", " + cityString + ", " + provinceString + ", Polska";
            //address = $(this).val();
            geocoder.geocode( { 'address': locationString}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    for(marker in markers) {
                        markers[marker].setMap(null);
                    }

                    mapCenter = results[0].geometry.location;
                    map.setCenter(mapCenter);

                    //add marker to the map
                    var marker = new google.maps.Marker({
                        map: map, position: results[0].geometry.location, draggable: true
                    });
                    google.maps.event.addListener(marker, 'dragend', function() {
                        $("#cord_x").val(marker.getPosition().lng());
                        $("#cord_y").val(marker.getPosition().lat());
                        mapCenter = new google.maps.LatLng(marker.getPosition().lat(), marker.getPosition().lng());
                        map.setCenter(mapCenter);
                    });


                    //var latlng = results[0].geometry.location.lat() + "," + results[0].geometry.location.lng();
                    $("#cord_x").val(results[0].geometry.location.lng());
                    $("#cord_y").val(results[0].geometry.location.lat());
                    markers.push(marker);
    //				map.addOverlay(marker);
    //                markers.push(results[0].geometry.location);
    //                map.fitBounds(markers); 
                }
            });
        });
        
        $("#google-map").bind("business_address_changed", function() {
            // var cityOption = $("form #city_id").find("option[value="+$("form #city_id").val()+"]");
            // var cityString = $(cityOption).attr("label");
            var cityString = $("form #business_city").val();
            //var provinceOption = $("form #province_id").find("option[value="+$("form #province_id").val()+"]");
            //var provinceString = $(provinceOption).attr("label");
            var provinceString = $("form #province").val();
            var addressString = $("form #business_address").val();     
            var locationString = addressString + ", " + cityString + ", " + provinceString + ", Polska";
            //address = $(this).val();
            geocoder.geocode( { 'address': locationString}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    for(marker in markers) {
                        markers[marker].setMap(null);
                    }

                    mapCenter = results[0].geometry.location;
                    map.setCenter(mapCenter);

                    //add marker to the map
                    var marker = new google.maps.Marker({
                        map: map, position: results[0].geometry.location, draggable: true
                    });
                    google.maps.event.addListener(marker, 'dragend', function() {
                        $("#cord_x").val(marker.getPosition().lng());
                        $("#cord_y").val(marker.getPosition().lat());
                        mapCenter = new google.maps.LatLng(marker.getPosition().lat(), marker.getPosition().lng());
                        map.setCenter(mapCenter);
                    });


                    //var latlng = results[0].geometry.location.lat() + "," + results[0].geometry.location.lng();
                    $("#cord_x").val(results[0].geometry.location.lng());
                    $("#cord_y").val(results[0].geometry.location.lat());
                    markers.push(marker);
    //				map.addOverlay(marker);
    //                markers.push(results[0].geometry.location);
    //                map.fitBounds(markers); 
                }
            });
        });
    }
    
    // file upload
    function loadphoto(rootId, selector) {
        $(selector).load("<?php echo $this->url(array(), 'domain-user-ajax-photo') ?>", {id: rootId}, function() {
            $(".file-loader").hide();
        });
    }
    
    function loadphoto2(rootId, flag, selector) {
        $(selector).load("<?php echo $this->url(array('action' => "load-company-gallery"), 'domain-user-ajax-photo') ?>", {id: rootId, flag: flag}, function() {
            $(".file-loader2").hide();
        });
    }
    
    $(".main-photo").delegate(".delete-company-photo", "click", function(e) {
        e.preventDefault();
        $(".main-photo").load($(this).attr("href"));
    });
    
    $(".gallery-photos").delegate(".delete-gallery-photo", "click", function(e) {
        e.preventDefault();
        $(".gallery").load($(this).attr("href"));
    });

    var uploader = new qq.FileUploaderBasic({
            // pass the dom node (ex. $(selector)[0] for jQuery users)
            button: document.getElementById('file-uploader'),
            // path to server-side upload script
            action: $("#file-uploader").attr("data-href"),
            inputName: "file",
            debug: true,
            forceMultipart: true,
            params: {id: $("#file-uploader").attr("data-id"), format: "json"},
            onSubmit: function(id, fileName) {
                $(".file-loader").show();
            },
            onComplete: function(id, fileName, responseJSON) {
                if(parseInt(responseJSON.root)) {
                    if(this.getInProgress() == 0) {
                        loadphoto(parseInt(responseJSON.root), ".main-photo");
                        $(".image-not-valid").html("");
                    }
                }
            },
            onError: function(){
                $(".image-not-valid").html("<?php echo $this->translate('Exceeded the maximum height photo') ?>");
            }
    });
    
    var uploader2 = new qq.FileUploaderBasic({
            // pass the dom node (ex. $(selector)[0] for jQuery users)
            button: document.getElementById('file-uploader2'),
            // path to server-side upload script
            action: "<?php echo $this->url(array('company-id' => $this->company->getId()), 'domain-user-ajax-company-gallery') ?>",
            inputName: "file",
            forceMultiple: true,
            debug: true,
            forceMultipart: true,
            sizeLimit: 10520000,
            params: {id: $("#file-uploader2").attr("data-id"), format: "json"},
            onSubmit: function(id, fileName) {
                $(".file-loader2").show();
            },
            onComplete: function(id, fileName, responseJSON) {
                if(parseInt(responseJSON.root)) {
                    if(this.getInProgress() == 0) {
                        loadphoto2(parseInt(responseJSON.root), null, ".gallery");
                    }
                }
                else{
                    loadphoto2(responseJSON.flag, responseJSON.companyId, ".gallery");
                }
            }
    });
    
    if ("<?php echo $this->company->get('BusinessCard')->getType() ?>" == "standard"){
        <?php foreach($this->languages as $language): ?>
            $("#<?php echo $language; ?>-description").attr("placeholder", "<?php echo $this->translate('Available in premium business card') ?>");
            $("#<?php echo $language; ?>-description").prop('disabled', true);
            $("#<?php echo $language; ?>-description").addClass("disabled");
                
            $("#<?php echo $language; ?>-short_description").attr("placeholder", "<?php echo $this->translate('Available in premium business card') ?>");
            $("#<?php echo $language; ?>-short_description").prop('disabled', true);
            $("#<?php echo $language; ?>-short_description").addClass("disabled");
            
            $("#<?php echo $language; ?>-meta_keywords").attr("placeholder", "<?php echo $this->translate('Available in premium business card') ?>");
            $("#<?php echo $language; ?>-meta_keywords").prop('disabled', true);
            $("#<?php echo $language; ?>-meta_keywords").addClass("disabled");
        <?php endforeach; ?>
    }
    else if("<?php echo $this->company->get('BusinessCard')->getType() ?>" == "premium"){
        <?php foreach($this->languages as $language): ?>
            $("#<?php echo $language; ?>-description").attr("placeholder", "");
            $("#<?php echo $language; ?>-description").prop('disabled', false);
            $("#<?php echo $language; ?>-description").removeClass("disabled");
                
            $("#<?php echo $language; ?>-short_description").attr("placeholder", "");
            $("#<?php echo $language; ?>-short_description").prop('disabled', false);
            $("#<?php echo $language; ?>-short_description").removeClass("disabled");
            
            $("#<?php echo $language; ?>-meta_keywords").attr("placeholder", "");
            $("#<?php echo $language; ?>-meta_keywords").prop('disabled', false);
            $("#<?php echo $language; ?>-meta_keywords").removeClass("disabled");
       <?php endforeach; ?>
     } 
     else{
       <?php foreach($this->languages as $language): ?>
            $("#<?php echo $language; ?>-description").attr("placeholder", "");
            $("#<?php echo $language; ?>-description").prop('disabled', false);
            $("#<?php echo $language; ?>-description").removeClass("disabled");
                
            $("#<?php echo $language; ?>-short_description").attr("placeholder", "");
            $("#<?php echo $language; ?>-short_description").prop('disabled', false);
            $("#<?php echo $language; ?>-short_description").removeClass("disabled");
            
            $("#<?php echo $language; ?>-meta_keywords").attr("placeholder", "");
            $("#<?php echo $language; ?>-meta_keywords").prop('disabled', false);
            $("#<?php echo $language; ?>-meta_keywords").removeClass("disabled");
       <?php endforeach; ?>  
     }
     
     <?php foreach ($this->languages as $language): ?>
      var limitShort = 200; //ustalamy limit znakow
       $(".limit-short-info-<?php echo $language; ?>").text(limitShort); //wypisujemy ten limit 'na dobry poczatek'
        $("#<?php echo $language; ?>-short_description").keyup(function() { //jesli wpisano cos do naszego pola
               var ile_wpisano = $(this).val().length; //zliczamy ilosc znakow
               if(ile_wpisano > limitShort) { //jesli przekroczymy limit
                   reset = $(this).val().substring(0, limitShort); //pobieramy znaki od pierwszego do ustalonego w limicie
                                   $(this).val(reset); //wypisujemy wczesniej pobrane znaki
               }
               $(".limit-short-info-<?php echo $language; ?>").text(limitShort - $(this).val().length); //wypisujemy ile znakow pozostalo
       });
      <?php endforeach; ?>
      
      <?php foreach ($this->languages as $language): ?>
      var limitFull = 1200; //ustalamy limit znakow
       $(".limit-full-info-<?php echo $language; ?>").text(limitFull); //wypisujemy ten limit 'na dobry poczatek'
        $("#<?php echo $language; ?>-description").keyup(function() { //jesli wpisano cos do naszego pola
               var ile_wpisano = $(this).val().length; //zliczamy ilosc znakow
               if(ile_wpisano > limitFull) { //jesli przekroczymy limit
                   reset = $(this).val().substring(0, limitFull); //pobieramy znaki od pierwszego do ustalonego w limicie
                                   $(this).val(reset); //wypisujemy wczesniej pobrane znaki
               }
               $(".limit-full-info-<?php echo $language; ?>").text(limitFull - $(this).val().length); //wypisujemy ile znakow pozostalo
       });
      <?php endforeach; ?>
    
    
    
    <?php if ($this->language == 'en'): ?>
        $('button#submit').css('background', "url('/images/layout/ajurweda/save.png') no-repeat 0px -15px"); 
    <?php endif; ?>
        
    <?php foreach ($this->languages as $language): ?>
       var limitShort = 200; //ustalamy limit znakow
       $(".limit-short-info-<?php echo $language; ?>").text(limitShort - $("#<?php echo $language; ?>-short_description").val().length); //wypisujemy ten limit 'na dobry poczatek'
        $("#<?php echo $language; ?>-short_description").keyup(function() { //jesli wpisano cos do naszego pola
               var ile_wpisano = $(this).val().length; //zliczamy ilosc znakow
               if(ile_wpisano > limitShort) { //jesli przekroczymy limit
                   reset = $(this).val().substring(0, limitShort); //pobieramy znaki od pierwszego do ustalonego w limicie
                                   $(this).val(reset); //wypisujemy wczesniej pobrane znaki
               }
               $(".limit-short-info-<?php echo $language; ?>").text(limitShort - $(this).val().length); //wypisujemy ile znakow pozostalo
       });
     <?php endforeach; ?>
      
     <?php foreach ($this->languages as $language): ?>
      var limitFull = 1200; //ustalamy limit znakow
       $(".limit-full-info-<?php echo $language; ?>").text(limitFull - $("#<?php echo $language; ?>-description").val().length);
        $("#<?php echo $language; ?>-description").keyup(function() { //jesli wpisano cos do naszego pola
               var ile_wpisano = $(this).val().length; //zliczamy ilosc znakow
               if(ile_wpisano > limitFull) { //jesli przekroczymy limit
                   reset = $(this).val().substring(0, limitFull); //pobieramy znaki od pierwszego do ustalonego w limicie
                                   $(this).val(reset); //wypisujemy wczesniej pobrane znaki
               }
               $(".limit-full-info-<?php echo $language; ?>").text(limitFull - $(this).val().length); //wypisujemy ile znakow pozostalo
       });
     <?php endforeach; ?>
     
     if ($("#another_address").is(':checked')){
          $("#business_city").addClass("disabled");
          $("#business_city").prop('disabled', true);
          $("#business_address").addClass("disabled");
          $("#business_address").prop('disabled', true);
          $("#business_post_code").addClass("disabled");
          $("#business_post_code").prop('disabled', true);
          $("form #address").keypress(function(e) {
                $("#google-map").trigger("address_changed");
          });
      }
      else{
        $("form #business_address").keypress(function(e) {
            $("#google-map").trigger("business_address_changed");
        });
      }
      
      $("#another_address").change(function(){
        if ($("#another_address").is(':checked')){
          $("#business_city").addClass("disabled");
          $("#business_city").prop('disabled', true);
          $("#business_address").addClass("disabled");
          $("#business_address").prop('disabled', true);
          $("#business_post_code").addClass("disabled");
          $("#business_post_code").prop('disabled', true);
          $("form #business_address").unbind("keypress");
          $("form #address").keypress(function(e) {
            $("#google-map").trigger("address_changed");
          });
        }
        else{
          $("#business_city").removeClass("disabled");
          $("#business_city").prop('disabled', false);
          $("#business_address").removeClass("disabled");
          $("#business_address").prop('disabled', false);
          $("#business_post_code").removeClass("disabled");
          $("#business_post_code").prop('disabled', false);
          $("form #address").unbind("keypress");
          $("form #business_address").keypress(function(e) {
            $("#google-map").trigger("business_address_changed");
          });
        }
      });
      
          
    if ($("#other_activity").is(':checked')){
            $("#other_activity_id").addClass("disabled");
            $("#other_activity_id").prop('disabled', true);
            $("#other_activity_name").removeClass("disabled");
            $("#other_activity_name").prop('disabled', false);
        }
        else{
            $("#other_activity_id").removeClass("disabled");
            $("#other_activity_id").prop('disabled', false);
            $("#other_activity_name").addClass("disabled");
            $("#other_activity_name").prop('disabled', true);
    }
     
    $("#other_activity").change(function(){
        if ($("#other_activity").is(':checked')){
            $("#other_activity_id").addClass("disabled");
            $("#other_activity_id").prop('disabled', true);
            $("#other_activity_name").removeClass("disabled");
            $("#other_activity_name").prop('disabled', false);
        }
        else{
            $("#other_activity_id").removeClass("disabled");
            $("#other_activity_id").prop('disabled', false);
            $("#other_activity_name").addClass("disabled");
            $("#other_activity_name").prop('disabled', true);
        }
    });
        
    if ($("#basic_activity_id").val() == 14){
        $(".other-basic-activity-name").show();
    }
    else{
        $(".other-basic-activity-name").hide();
    }
    
    $("#basic_activity_id").change(function(){
        if ($("#basic_activity_id").val() == 14){
            $(".other-basic-activity-name").show();
        }
        else{
            $(".other-basic-activity-name").hide();
        }
    });
});
</script>

<section id="add-company">
    <header>
        <?php echo $this->translate('Edit company') ?>
    </header>
    <div class="add_company_content">
        <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
            
            <div class="translations">
                <ul id="myTab" class="nav nav-tabs pattern">
                    <li class="dropdown">
                        <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($language == $this->language): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                            <?php endforeach; ?>
                        </li>
                </ul>

                <div class="tab-content">
                    <?php foreach($this->languages as $key => $language): ?>
                        <div class="tab-pane<?php if($language == $this->language): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->name ?>
                                <?php echo $this->form->translations->getSubForm($language)->short_description ?>
                                <div class="limit-characters">
                                    Pozostało znaków: <span class="strong limit-short-info-<?php echo $language; ?>"></span>
                                </div>
                                <?php echo $this->form->translations->getSubForm($language)->description ?>
                                <div class="limit-characters">
                                    Pozostało znaków: <span class="strong limit-full-info-<?php echo $language; ?>"></span>
                                </div>
                            <?php endif; ?>

                            <div class="metatags">
                                <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                            </div>
                        </div>
                   <?php endforeach; ?>
                 </div>
            </div>

                        <?php echo $this->form->id ?>
          <div class="title"><?php echo $this->translate('COMPANY DATA') ?></div>
                <?php echo $this->form->province ?>
                <?php echo $this->form->city ?>
                <?php echo $this->form->address ?>
                <?php echo $this->form->post_code ?> 
                <?php echo $this->form->nip ?>
                <?php echo $this->form->krs_edg ?>
                <?php echo $this->form->email ?>
                <?php echo $this->form->email2 ?>
                <?php echo $this->form->email3 ?>
                <?php echo $this->form->website ?>
                <div class="next-websites">
                    <?php echo $this->form->website2 ?>
                    <?php echo $this->form->website3 ?>
                </div>
                <?php echo $this->form->phone ?>
                <?php echo $this->form->basic_activity_id->setAttribs(array('class' => 'nostyle')) ?>
                <div class="other-basic-activity-name">
                    <?php echo $this->form->basic_activity_name ?>
                </div>
                <?php echo $this->form->other_activity_id->setAttribs(array('class' => 'nostyle')) ?>
                <?php echo $this->form->other_activity ?>
                <?php echo $this->form->other_activity_name ?>
           
          <div class="title"><?php echo $this->translate('ADDRESS THE BUSINESS') ?></div>
                <?php echo $this->form->another_address ?>
                <?php echo $this->form->business_city ?>
                <?php echo $this->form->business_address ?>
                <?php echo $this->form->business_post_code ?> 
          
           <div class="title"><?php echo $this->translate('CONTACT DATA') ?></div>
                 <?php echo $this->form->contact_name ?>
                 <?php echo $this->form->contact_phone ?>
                 <?php echo $this->form->contact_email ?>
          
           <?php echo $this->form->cord_x ?>
           <?php echo $this->form->cord_y ?>
          
         <?php if ($this->company->get('BusinessCard')->getType() != "standard"): ?>
         <div class="main-photo-container">
                <span class="add-main-photo">
                    <a id="file-uploader" data-href="<?php echo $this->url(array('action' => 'upload-company-photo', 'company-id' => $this->company->getId()), 'domain-user-profile') ?>"><?php echo $this->translate('Add photo / logo') ?></a>
                </span>
                <div class="attention"><?php echo $this->translate('Maximum height of image is 200px') ?></div>
                <div class="image-not-valid"></div>
                <div class="main-photo">
                    <ul class="photos">
                        <?php if($this->company['PhotoRoot']['filename']): ?>
                        <li>
                            <?php if(strlen($this->company['PhotoRoot']['filename'])): ?>
                                <img src="/media/photos/<?php echo $this->company['PhotoRoot']['offset'] ?>/200x/<?php echo $this->company['PhotoRoot']['filename'] ?>" /><br />
                                <?php else: ?>
                                <img src="/images/layout/ajurweda/no_photo.jpg" style="width: 200px;" /><br />
                            <?php endif; ?>
                            <a class="delete-company-photo" href="<?php echo $this->url(array('action' => 'delete-company-photo', 'id' => $this->company['PhotoRoot']['id']), 'domain-user-profile') ?>"><?php echo $this->translate('Delete') ?></a>
                        </li>
                        <?php else: ?>
                            <img src="/images/layout/ajurweda/no_photo.jpg" style="width: 200px;" /><br />
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
            <div class="title"><?php echo $this->translate('GALLERY') ?></div>
            <div class="gallery-photos">
                <span class="add-photo">
                    <a id="file-uploader2" href="#"><?php echo $this->translate('Add photos') ?></a>
                </span>
                <div class="attention"><?php echo $this->translate('Maximum 4 photos') ?></div>
                 <ul class="gallery">
                    <?php foreach($this->companyPhotos as $photo): ?>
                        <li>
                        <?php if($photo->getOffset()): ?>
                            <img src="/media/photos/<?php echo $photo->getOffset() ?>/200x/<?php echo $photo->getFilename() ?>" data-original="/media/photos/<?php echo $this->company->get('PhotoRoot')->getOffset() ?>/<?php echo $photo->getFilename() ?>" alt="<?php echo $photo->getTitle() ?>"><br/>
                            <a class="delete-gallery-photo" href="<?php echo $this->url(array('action' => 'delete-gallery-photo', 'id' => $photo['id']), 'domain-user-profile') ?>"><?php echo $this->translate('Delete') ?></a>
                        <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                 </ul>
            </div>
         <?php endif; ?>
            
        <div id="google-map" style="margin-top: 20px; border: 1px solid #B8B8B6; height: 352px; width: 95%;"></div> 
        
        <div class="save-button">
            <?php echo $this->form->submit ?>
        </div>
        </form>
    </div>
</section>
