<ul class="photos">
<?php if($this->photo['filename']): ?>
    <li>
        <?php if(strlen($this->photo['filename'])): ?>
            <img src="/media/photos/<?php echo $this->photo['offset'] ?>/245x155/<?php echo $this->photo['filename'] ?>" /><br />
        <?php else: ?>
            <img src="/images/layout/ajurweda/no_photo.jpg" style="width: 245px; height: 245px;" /><br />
        <?php endif; ?>
        <a class="delete-event-promoted-photo" href="<?php echo $this->url(array('action' => 'delete-event-promoted-photo', 'id' => $this->photo['id']), 'domain-user-profile') ?>"><?php echo $this->translate('Delete') ?></a>
    </li>  
<?php else: ?>
    <img src="/images/layout/ajurweda/no_photo.jpg" style="width: 245px; height: 245px;" /><br />
<?php endif; ?>
</ul>