<article class="profile span8">
    
    <header class="row-fluid">
        <h3 class="span8"><?php echo $this->translate('Send an offer') ?></h3>
    </header>
    
    <section class="notice clearfix">
        <h3><?php echo $this->notice['title'] ?></h3>
        <p class="views"><?php echo $this->notice['views'] ?></p>
        <table class="parameters span5">
            <?php foreach($this->notice['Parameters'] as $parameter): ?>
            <tr>
                <th><?php echo $parameter['ParameterTemplate']['name'] ?></th>
                <?php if($parameter['ParameterTemplate']['range']): ?>
                <td><?php echo $parameter['value'] ?> - <?php echo $parameter['value_to'] ?></td>
                <?php else: ?>
                <td><?php echo $parameter['value'] ?></td>
                <?php endif; ?>
            </tr>
            <?php endforeach; ?>
        </table>
        <div class="content span5">
            <?php echo $this->notice['content'] ?>
        </div>
    </section>
    
    <?php if($this->offer): ?>
    <section class="offer clearfix">
        <h3><?php echo $this->offer['title'] ?></h3>
        <table class="parameters span5">
            <?php foreach($this->offer['Parameters'] as $parameter): ?>
            <tr>
                <th><?php echo $parameter['ParameterTemplate']['name'] ?></th>
                <?php if($parameter['ParameterTemplate']['range']): ?>
                <td><?php echo $parameter['value'] ?> - <?php echo $parameter['value_to'] ?></td>
                <?php else: ?>
                <td><?php echo $parameter['value'] ?></td>
                <?php endif; ?>
            </tr>
            <?php endforeach; ?>
        </table>
        <div class="content span6">
            <?php echo $this->form ?>
            <?php // echo $this->offer['content'] ?>
        </div>
    </section>
    
    <?php else: ?>
    
    <div id="rootwizard_edit">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul>
                        <li class="<?php if($this->step == 1): ?>active<?php endif; ?>"><a href="#tab1" data-toggle="tab"><?php echo $this->translate('Basic informations') ?></a></li>
                        <li class="<?php if($this->step == 2): ?>active<?php endif; ?>"><a href="#tab2" data-toggle="tab"><?php echo $this->translate('Parameters') ?></a></li>
                        <li class="<?php if($this->step == 3): ?>active<?php endif; ?>"><a href="#tab3" data-toggle="tab"><?php echo $this->translate('Provider') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <?php echo $this->form->category ?>
                    <?php echo $this->form->title ?>
                    <?php echo $this->form->content ?>
                    <?php echo $this->form->submit ?>
                </div>
                <div class="tab-pane" id="tab2">
                    <?php echo $this->form->parameters ?>
                </div>
                <div class="tab-pane" id="tab3">

                </div>
                <ul class="pager wizard">
                    <?php if($this->step > 1): ?>
                    <li class="previous"><button class="btn btn-mini btn-link pull-left button-prev" value="<?php echo $this->step - 1 ?>" name="prev" type="submit"><?php echo $this->translate('Back') ?></button></li>
                    <?php endif; ?>
                    <?php if($this->step < 3): ?>
                    <li class="next"><button class="btn btn-mini btn-link pull-right button-next" value="<?php echo $this->step + 1 ?>" name="next" type="submit"><?php echo $this->translate('Forward') ?></button></li>
                    <?php else: ?>
                    <li class="next"><button class="btn btn-mini btn-link pull-right button-next" value="<?php echo $this->step + 1 ?>" name="next" type="submit"><?php echo $this->translate('Save') ?></button></li>
                    <?php endif; ?>
                </ul>
            </div>	
        </form>
    </div>
    <?php endif; ?>
    
</article>