<section class="profile span8">
    <header class="row-fluid">
        <h3 class="span8"><?php echo $this->translate('New offer') ?></h3>
    </header>
    
    <div id="rootwizard_new">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul>
                        <li class="<?php if($this->step == 1): ?>active<?php endif; ?>"><a href="#tab1" data-toggle="tab"><?php echo $this->translate('Basic informations') ?></a></li>
                        <li class="<?php if($this->step == 2): ?>active<?php endif; ?>"><a href="#tab2" data-toggle="tab"><?php echo $this->translate('Parameters') ?></a></li>
                        <li class="<?php if($this->step == 3): ?>active<?php endif; ?>"><a href="#tab3" data-toggle="tab"><?php echo $this->translate('Provider') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
            <div class="tab-content">
                <div class="tab-pane" id="tab1">
                    <?php echo $this->form->offer->category ?>
                    <?php echo $this->form->offer->title ?>
                    <?php echo $this->form->offer->content ?>
                    <?php echo $this->form->offer->submit ?>
                </div>
                <div class="tab-pane" id="tab2">
                    <?php echo $this->form->parameters ?>
                </div>
                <div class="tab-pane" id="tab3">

                </div>
                <ul class="pager wizard">
<!--                    <li class="previous"><a href="#">Previous</a></li>
                    <li class="next"><a href="#">Next</a></li>-->
                    <?php if($this->step > 1): ?>
                    <li class="previous"><button class="btn btn-mini btn-link pull-left button-prev" value="<?php echo $this->step - 1 ?>" name="prev" type="submit"><?php echo $this->translate('Back') ?></button></li>
                    <?php endif; ?>
                    <?php if($this->step < 3): ?>
                    <li class="next"><button class="btn btn-mini btn-link pull-right button-next" value="<?php echo $this->step + 1 ?>" name="next" type="submit"><?php echo $this->translate('Forward') ?></button></li>
                    <?php else: ?>
                    <li class="next"><button class="btn btn-mini btn-link pull-right button-next" value="<?php echo $this->step + 1 ?>" name="next" type="submit"><?php echo $this->translate('Save') ?></button></li>
                    <?php endif; ?>
                </ul>
            </div>	
        </form>
    </div>
    
    
</section>