<div id="BannerUnderStream" class="flexslider article-body-banner banner" style="width:728px;height:90px;margin:0 auto;">
    <ul class="slides">
        <?php foreach($this->banners as $banner): ?>
        <li>
            <a href="<?php echo $banner['website'] ?>" rel="nofollow" target="_blank" >
                <div class="slide">
                    <img style="width:728px;height:90px;" src="/media/attachments/<?php echo $banner['AttachmentRoot']['filename']; ?>" alt="<?php echo $banner['Translation'][$this->language]['name']; ?>">
                </div>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
        $(document).ready(function(){
                $('#BannerUnderStream').flexslider({
                        animation : 'slide',
                        controlNav : false,
                        directionNav : false,
                        animationLoop : true,
                        slideshow : true,
                        useCSS : false
                });

        });
</script>
