<link rel="stylesheet" media="screen" href="/css/notifications.css" />
<script type="text/javascript" src="/js/jquery.ui.widget.min.js"></script>
<script type="text/javascript" src="/js/jquery.notify.js"></script>
<script type="text/javascript" src="/js/jquery.itextclear.js"></script>

<script src="/lib/elfinder/js/elfinder.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/lib/elfinder/css/elfinder.css" type="text/css" media="screen" charset="utf-8">

<link rel="stylesheet" href="/lib/ui-lightness/css/ui-lightness/jquery-ui-1.8.20.custom.css" type="text/css" media="screen" charset="utf-8">
<script type="text/javascript" src="/js/jquery-ui-1.8.14.custom.min.js"></script>

<!-- Load TinyMCE -->
<?php if($this->userAgent()->getDevice()->getType() == 'desktop' || ($this->userAgent()->getDevice()->getFeature('is_tablet') && $this->userAgent()->getDevice()->getFeature('resolution_width') > 480)): ?>
<script type="text/javascript" src="/lib/tinymce/jquery.tinymce.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url : '/lib/tinymce/tiny_mce.js',

            // General options
            width: "100%",
            height: "500px",
            theme : "advanced",
            plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print",
            theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,|,ltr,rtl,|,fullscreen,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true,

            // Replace values for the template plugin
            template_replace_values : {
                username : "Some User",
                staffid : "991234"
            },
            file_browser_callback : function(field_name, url, type, win) {
                var w = window.open('<?php echo $this->serverUrl() ?>/admin/media/client', null, 'width=600,height=500');
                //Save required parameters in global variables of window (not the best solution, can offer better?)
                //else you can pass parameters using GET and than parse them in elfinder.html
                w.tinymceFileField = field_name;
                w.tinymceFileWin = win;
            }
        });
    });
</script>
<?php endif; ?>
<script type="text/javascript">
$(document).ready(function() {
    $('input[type=text], input[type=password], input[type=url], input[type=email], input[type=number], textarea', '.form').iTextClear();

    $("#wrapper").undelegate("#savemessage-button", "click").delegate("#save-message-button", "click", function(e) {
        e.preventDefault();

        $("#wrapper").find("#edit-message-form").append("<input type='hidden' name='saveOnly' value='1' />");
        $("#wrapper").find("#edit-message-form #submit").trigger("click");
    });
    
    $('#elfinder').elfinder({
        url : '/admin/media/connect',
        lang : 'en',
        height: 280,
        width : 550,
        cutURL : domain + "/media/elfinder/",
        editorCallback : function(href) {
            var filename = decodeURIComponent(href);
            filename = filename.replace(/(.+\/)/g, "");
            var name = filename.replace(/(\..+)$/, "");

            $("#main-photo").attr("src", domain + "/media/elfinder/" + href);
            $("#photo_href").val(href);
            $("#photo_name").val(name);
            $("#photo_title").val(name);
            $("#photo_file").val(filename);
        },
        closeOnEditorCallback : false
    });
    
});

</script>
<h1 class="page-title"><?php echo $this->translate('Message') ?>: <?php echo $this->message->subject ?> - <?php echo $this->translate('Edit') ?></h1>
<div class="container_12 clearfix leading">
    <div class="grid_12">

        <a href="<?php echo $this->adminUrl('list-message', 'admin') ?>"><?php echo $this->formButton('', $this->translate('Back'), array('id' => 'back')) ?></a>
        
        <div class="clear"></div>
        
        <?php if($this->form->isErrors()): ?>
        <div class="message error closeable">
                <span class="message-close"></span>
                <h3><?php echo $this->translate('Error') ?>!</h3>
        </div>
        <?php endif; ?>

        <form id="edit-message-form" class="form <!--has-validation-->" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
            
            <?php
            foreach($this->form->getElements() as $element) {
                if($element->hasErrors()) {
                    $element->setAttrib('class', 'error');
                }
            }
            ?>
            
            <?php echo $this->form->subject ?>
            <?php echo $this->form->content->setAttrib('class', 'tinymce') ?>
            <?php echo $this->form->id ?>

            <div class="form-action clrearfix">
                <?php echo $this->form->submit ?>
                <?php echo $this->formButton('', $this->translate('Save'), array('id' => 'save-message-button', 'type' => 'button')) ?>
                <a href="<?php echo $this->adminUrl('list-message', 'admin') ?>"><?php echo $this->formButton('', $this->translate('Cancel'), array('id' => 'cancel-edit-message-button')) ?></a>
            </div>

        </form>

    </div>
    
    <section id="box"></section>
</div>