<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user_profile', 'postal_code', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user_profile', 'postal_code');
    }
}