<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user_user', 'discount_id', 'integer', '4', array(
             ));
        $this->changeColumn('user_user', 'active', 'boolean', '25', array(
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('user_user', 'discount_id');
    }
}