<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('user_profile', 'user_profile_photo_root_id_media_photo_id');
        $this->dropForeignKey('user_profile', 'user_profile_province_id_default_province_id');
        $this->dropForeignKey('user_profile', 'user_profile_city_id_default_city_id');
    }

    public function down()
    {
        $this->createForeignKey('user_profile', 'user_profile_photo_root_id_media_photo_id', array(
             'name' => 'user_profile_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('user_profile', 'user_profile_province_id_default_province_id', array(
             'name' => 'user_profile_province_id_default_province_id',
             'local' => 'province_id',
             'foreign' => 'id',
             'foreignTable' => 'default_province',
             ));
        $this->createForeignKey('user_profile', 'user_profile_city_id_default_city_id', array(
             'name' => 'user_profile_city_id_default_city_id',
             'local' => 'city_id',
             'foreign' => 'id',
             'foreignTable' => 'default_city',
             ));
    }
}