<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('New language') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->id ?>
                    <?php echo $this->form->active ?>
                    <?php echo $this->form->default ?>
                    <?php echo $this->form->admin ?>
                    <?php echo $this->form->submit ?>
                    <div class="form-actions">
                        <a href="<?php echo $this->adminUrl('list-language', 'default') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
        
    </div>

    <div class="span6">
        

    </div>


</div>