<style>
    #cropContainerHeader {
        width: 50px;
        height: 70px;
        position:relative; /* or fixed or absolute */
    }
    
    label[for="photoUrl"]{
        font-size:20px;
        font-weight:bold;
    }
    #submit-upload-photo{
        position:relative;
        z-index:100000;
    }
    
    #croppic2{
        position: relative;
        border: 3px solid #FFF;
        box-sizing: content-box;
        border-radius: 2px;
        background-repeat: no-repeat;
        background-position: center center;
        /*background:#fff;*/
    }
    .premiumWrapper{
        border:2px solid blue;
    }
</style>
                        <script src="/plugins/croppic/assets/js/bootstrap.min.js"></script>
                        <script src="/plugins/croppic/assets/js/jquery.mousewheel.min.js"></script>
                        <script src="/plugins/croppic/croppic.js"></script>
                        <link rel="stylesheet" type="text/css" href="/plugins/croppic/croppic.css"/>
                        
                        
                        

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-crop"></span>
                    <span><?php echo $this->translate('Dostosuj zdjęcie') ?></span>
                </h4>
                
            </div>
            
            
            <div class="content clearfix" style="background:black">
                <?php foreach($this->dimensions as $dimension => $description): 
                    if($dimension=="126x126")
                        continue;
                    $dimensionExplode = explode('x',$dimension);
                    ?>
                <style>
                    #croppic2,.previewWrapper{
                        width: <?php echo $dimensionExplode[0]; ?>px;
                        height: <?php echo $dimensionExplode[1]; ?>px;
                    }
                    
                </style>
                <div id="croppic2">
                    <img src="<?php echo MF_Text::getPhotoPath($this->photo,$dimension); ?>" />
                </div>
                
                
                <div class="clearfix"></div>
                <?php endforeach; ?>
                <?php //  echo $this->cropPhoto($this->photo, $this->imgDimensions, $this->dimensions, 1) ?>
                
            </div>
            <div class='previewBackground' style='  background: white;
  z-index: 1000000;
  position: relative;
  min-height: 200px;
  margin-left: -10px;'>
                
                <h2>Tak twoje zdjęcie jest wyświetlane na stronie</h2>
                <div class="previewWrapper" style='border:14px solid blue;'>
                    <img src="<?php echo MF_Text::getPhotoPath($this->photo,$dimension); ?>" />
                </div>
            </div>
        </div>
        
    </div>
    
    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit photo') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                <form id="form" class="form crop-form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                    <?php echo $this->form->title ?>
                    <?php echo $this->form->alternate_text ?>
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->backUrl ?>" class="btn">Powrót</a>
                    </div>
                    
                </form>
                
            </div>
            
        </div>
        
    </div>
        
</div>
<script type="text/javascript">
   
     var croppicHeaderOptions = {
                    //uploadUrl:'img_save_to_file.php',
                    cropUrl:'/plugins/croppic/img_crop_to_file.php',
                    loadPicture:'<?php echo MF_Text::getPhotoPath($this->photo,$dimension); ?>',
//                    onAfterImgUpload: function(){  
//                        $('#submit-upload-photo').show(); 
//                         $('.cropControlReset').on('click',function(){
//                            $('#submit-upload-photo').hide();
//                        });
//                    },
//                    onAfterImgCrop: function(){  
//                        $('#submit-upload-photo').click(function(){
//                            $('#uploadphotoform').submit();
//                        });
//                    },
            
                    outputUrlId: 'photoUrl',
                    doubleZoomControls:false,
                    rotateControls: false,
//                    customUploadButtonId:'cropContainerHeaderButton',
            }	
            var croppic = new Croppic('croppic2',croppicHeaderOptions);
        
</script>