<div class="container_12 clearfix leading">
    <div class="grid_12">
        <div class="box">
            
            
                    <?php if($this->form->isErrors()): ?>
                    <div class="message error closeable">
                        <span class="message-close"></span>
                        <h3><?php echo $this->translate('Error') ?>!</h3>
                    </div>
                    <?php endif; ?>
                    <?php if($this->messages()->count()): ?>
                    <?php echo $this->messages()->render() ?>
                    <?php endif; ?>

            <div class="content">
                    <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <div class="title">
                            <h4>
                                <span class="icon16 iconic-icon-list-nested"></span>
                                <span><?php echo $this->translate('Edit contact') ?></span>
                            </h4>
                         </div>
                        <div class="tab-content">
                           
                            <div class="content clearfix">
                                <?php echo $this->form->name; ?>
                                <?php echo $this->form->email ?>
                                <?php echo $this->form->phone ?>
                                <?php echo $this->form->address ?>
                                <?php echo $this->form->opening ?>
                                 <?php echo $this->form->submit ?>
                            </div>
                            
                         </div>
                           
                        

                        
                    </form>
            </div>
            </div>
        </div>
</div>