<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#category_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-language-data', 'default') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            null,
            null,
            null,
            null,
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#category_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit language') ?> <?php echo $this->language['name'] ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->id ?>
                    <?php echo $this->form->active ?>
                    <?php echo $this->form->default ?>
                    <?php echo $this->form->admin ?>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-language', 'default') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
        
    </div>

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-comments-2"></span>
                    <span><?php echo $this->translate('Languages') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="category_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Id') ?></th>
                        <th><?php echo $this->translate('Active') ?></th>
                        <th><?php echo $this->translate('Default') ?></th>
                        <th><?php echo $this->translate('Admin') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>


</div>