<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <form action="<?php echo $this->form->getAction() ?>" method="post">
                
                <div class="title">

                    <h4>
                        <span class="icon16 entypo-icon-settings"></span>
                        <span><?php echo $this->translate('Settings') ?></span>

                        <div class="box-form right">
                            <?php // echo $this->form->submit ?>
                            <button class="btn btn-success btn-mini" type="submit"><?php echo $this->translate('Save settings') ?></button>
                        </div>
                    </h4>

                </div>
                <div class="content clearfix">

                    <table id="settings_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Setting') ?></th>
                                <th><?php echo $this->translate('Value') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->form->getElements() as $element): ?>
                            <?php if($element->getName() == 'submit') continue; ?>
                            <?php echo $element ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

            </form>
        </div><!-- End .box -->

    </div>


</div>