<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 entypo-icon-settings"></span>
                    <span><?php echo $this->translate('Settings') ?></span>
                    
                    <form class="box-form right" action="<?php echo $this->adminUrl('edit-settings', 'default') ?>" method="get">
                        <button class="btn btn-primary btn-mini" type="submit"><?php echo $this->translate('Edit settings') ?></button>
                    </form>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="settings_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Setting') ?></th>
                            <th><?php echo $this->translate('Value') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->settings as $setting): ?>
                        <tr>
                            <td>
                                <?php echo $this->translate($setting['label']) ?>
                            </td>
                            <td>
                                <?php echo isset($setting['value']) ? $setting['value'] : '' ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>


</div>