<div class="loginContainer">
    <form class="form-horizontal" action="<?php echo $this->url(array(), 'domain-register-admin-token') ?>" id="loginForm" method="post" >
        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <label class="form-label span12" for="password">
                        <?php echo $this->translate('Password') ?>:
                        <span class="icon16 icomoon-icon-user-3 right gray marginR10"></span>
                    </label>
                    <?php echo $this->form->password ?>
                </div>
            </div>
        </div>

        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <label class="form-label span12" for="confirm_password">
                        <?php echo $this->translate('Confirm password') ?>:
                        <span class="icon16 icomoon-icon-locked right gray marginR10"></span>
                    </label>
                    <?php echo $this->form->confirm_password ?>
                </div>
            </div>
        </div>
        <div class="form-row row-fluid">                       
            <div class="span12">
                <div class="row-fluid">
                    <div class="form-actions">
                    <div class="span12 controls">
                        <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> <?php echo $this->translate('Save') ?></button>
                    </div>
                    </div>
                </div>
            </div> 
        </div>
        <?php echo $this->form->csrf ?>
        <?php echo $this->form->token ?>
    </form>
</div>