<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('newsletter_message_company', 'newsletter_message_company_message_id_newsletter_message_id');
        $this->dropForeignKey('newsletter_message_event', 'newsletter_message_event_message_id_newsletter_message_id');
        $this->dropForeignKey('newsletter_message_news', 'newsletter_message_news_message_id_newsletter_message_id');
        $this->dropForeignKey('newsletter_message_product', 'newsletter_message_product_message_id_newsletter_message_id');
    }

    public function down()
    {
        $this->createForeignKey('newsletter_message_company', 'newsletter_message_company_message_id_newsletter_message_id', array(
             'name' => 'newsletter_message_company_message_id_newsletter_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
        $this->createForeignKey('newsletter_message_event', 'newsletter_message_event_message_id_newsletter_message_id', array(
             'name' => 'newsletter_message_event_message_id_newsletter_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
        $this->createForeignKey('newsletter_message_news', 'newsletter_message_news_message_id_newsletter_message_id', array(
             'name' => 'newsletter_message_news_message_id_newsletter_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
        $this->createForeignKey('newsletter_message_product', 'newsletter_message_product_message_id_newsletter_message_id', array(
             'name' => 'newsletter_message_product_message_id_newsletter_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter_message',
             ));
    }
}