<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Dodaj trenera') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                <style> 
                    
                    table tr td{
                        text-align:center;
                    }
                    </style>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
		    <br /><br />
                    
                    <?php echo $this->form->first_name ?>
                    
                    <?php echo $this->form->last_name ?>
                    <?php echo $this->form->position ?>
                    <?php echo $this->form->team_id ?>
		    <br />
                    
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-coach', 'league') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                    
                </form>
            
            </div>
            
        </div>
        
    </div>


</div>
<div id="explorer" class="dialog"><div id="elfinder"></div></div>