<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#order_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 5,
        "sAjaxSource": "<?php echo $this->adminUrl('list-league-data', 'league') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { sWidth: '50px' },
            null,
            { sWidth: '100px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#order_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16  icomoon-icon-cart"></span>
                    <span><?php echo $this->translate('Lista lig') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-league', 'league') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
               </h4>
            
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="order_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <tr>
                        <th><?php echo $this->translate('Id') ?></th>
                        <th><?php echo $this->translate('Liga') ?></th>
                        <th><?php echo $this->translate('Active') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div>

    </div>
</div>