<?php if ($this->pageCount > 1): ?>
<ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <li><a href="<?php echo $this->url(array('page' => $this->previous), null, false, false); ?>">&laquo;</a></li>
<?php else: ?>
  
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url(array('page' => $page), null, false, false); ?>"><?php echo $page; ?></a></li>
  <?php else: ?>
    <li><a class="active"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <li><a href="<?php echo $this->url(array('page' => $this->next), null, false, false); ?>">&raquo;</a></li>
<?php else: ?>
  
<?php endif; ?>
</ul>
<?php endif; ?>