<?php

/**
 * Gallery_Model_Doctrine_BaseGalleryTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $lang
 * @property string $name
 * @property string $slug
 * @property clob $description
 * @property Gallery_Model_Doctrine_Gallery $Gallery
 * 
 * @package    Admi
 * @subpackage Gallery
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Gallery_Model_Doctrine_BaseGalleryTranslation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery_gallery_translation');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('lang', 'string', 64, array(
             'primary' => true,
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery_Model_Doctrine_Gallery as Gallery', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}