<?php

/**
 * Gallery_Model_Doctrine_GalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Gallery_Model_Doctrine_GalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Gallery_Model_Doctrine_GalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery_Model_Doctrine_Gallery');
    }
    
    public function getFullGalleryQuery() {
        $q = $this->createQuery('p')
                ->addSelect('p.*')
                ->addSelect('t.*')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->leftJoin('p.Translation t')
                ->leftJoin('p.Metatag m')
                ->leftJoin('m.Translation mt')
                ;
        return $q;
    }
}