<?php

/**
 * Gallery_Model_Doctrine_VideoTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Gallery
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Gallery_Model_Doctrine_VideoTranslation extends Gallery_Model_Doctrine_BaseVideoTranslation
{

}