<?php

/**
 * Invoice_Model_Doctrine_BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $invoice_id
 * @property string $name
 * @property string $item_type
 * @property integer $item_id
 * @property decimal $price
 * @property integer $count
 * @property Invoice_Model_Doctrine_Invoice $Invoice
 * 
 * @package    Admi
 * @subpackage Invoice
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Invoice_Model_Doctrine_BaseItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('invoice_item');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('invoice_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('item_type', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             ));
        $this->hasColumn('count', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Invoice_Model_Doctrine_Invoice as Invoice', array(
             'local' => 'invoice_id',
             'foreign' => 'id'));
    }
}