<?php

/**
 * Invoice_Model_Doctrine_Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Invoice
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice_Model_Doctrine_Invoice extends Invoice_Model_Doctrine_BaseInvoice
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setCode($code) {
        $this->_set('code', $code);
    }
    
    public function getCode() {
        return $this->_get('code');
    }
    
    public function setUserId($userId) {
        $this->_set('user_id', $userId);
    }
    
    public function getUserId() {
        return $this->_get('user_id');
    }
    
    public function setSum($sum) {
        $this->_set('sum', $sum);
    }
    
    public function getSum() {
        return $this->_get('sum');
    }
    
    public function setExecutionStartDate($executionStartDate) {
        $this->_set('execution_start_date', $executionStartDate);
    }
    
    public function getExecutionStartDate() {
        return $this->_get('execution_start_date');
    }
    
    public function setExecutionEndDate($executionEndDate) {
        $this->_set('execution_end_date', $executionEndDate);
    }
    
    public function getExecutionEndDate() {
        return $this->_get('execution_end_date');
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}