<?php

/**
 * Invoice_Model_Doctrine_InvoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Invoice_Model_Doctrine_InvoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Invoice_Model_Doctrine_InvoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Invoice_Model_Doctrine_Invoice');
    }
    
    public function getFullInvoiceQuery() {
        $q = $this->createQuery('i')
                ->addSelect('i.*')
                ->addSelect('ii.*')
                ->addSelect('p.*')
                ->addSelect('u.*')
                ->addSelect('up.*')
                ->addSelect('upc.*')
                ->addSelect('upp.*')
                ->leftJoin('i.Payment p')
                ->leftJoin('i.Items ii')
                ->leftJoin('i.User u')
                ->leftJoin('u.Profile up')
                ->leftJoin('up.City upc')
                ->leftJoin('up.Province upp')
                ;
        return $q;
    }
    
    public function getCurrentInvoiceQuery(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->getFullInvoiceQuery();
        }
        $q->andWhere('((i.execution_start_date <= ?) AND (i.execution_end_date >= ?))', array(date('Y-m-d H:i:s'), date('Y-m-d H:i:s')));
        return $q;
    }
}