<?php

/**
 * Invoice_Model_Doctrine_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Invoice
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice_Model_Doctrine_Item extends Invoice_Model_Doctrine_BaseItem
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setInvoiceId($invoiceId) {
        $this->_set('invoice_id', $invoiceId);
    }
    
    public function getInvoiceId() {
        return $this->_get('invoice_id');
    }
    
    public function setName($name) {
        $this->_set('name', $name);
    }
    
    public function getName() {
        return $this->_get('name');
    }
    
    public function setPrice($price) {
        $this->_set('price', $price);
    }
    
    public function getPrice() {
        return $this->_get('price');
    }
    
    public function setCount($count) {
        $this->_set('count', $count);
    }
    
    public function getCount() {
        return $this->_get('count');
    }
    
    public function setItemId($itemId) {
        $this->_set('item_id', $itemId);
    }
    
    public function getItemId() {
        return $this->_get('item_id');
    }
    
    public function setItemType($itemType) {
        $this->_set('item_type', $itemType);
    }
    
    public function getItemType() {
        return $this->_get('item_type');
    }
}