<?php

/**
 * Invoice_Model_Doctrine_Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Invoice
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice_Model_Doctrine_Payment extends Invoice_Model_Doctrine_BasePayment
{
    const TYPE_PAYU = 'payu';
    
    public static $paymentTypes = array(
        self::TYPE_PAYU => 'PayU'
    );
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setType($type) {
        $this->_set('type', $type);
    }
    
    public function getType() {
        return $this->_get('type');
    }
    
    public function setStatus($status) {
        $this->_set('status', $status);
    }
    
    public function getStatus() {
        return $this->_get('status');
    }
}