<?php echo $this->translate('Dziękujemy za zainteresowanie naszym serwisem i chęć zamieszczenia wydarzenia promowanego dotyczącego ajurwedy. Skontaktujemy się z Tobą w celu weryfikacji terminu i miejsca wydarzenia.') ?> <br/><br/>
<?php echo $this->translate('Pozdrawiamy!') ?> <br/>
<?php echo $this->translate('Serwis a-ajurweda.pl') ?> <br/><br/>
<span style='font-size: 10px;'><?php echo $this->translate('Zastrzegamy sobie prawo selekcji zamieszczanych informacji o wydarzeniach dotyczących ajurwedy.') ?> </span>
