<?php echo $this->translate('Dziękujemy za współpracę i dodanie nowej sylwetki. Zweryfikujemy przesłane dane lub skontaktujemy się z Tobą w celu ich weryfikacji.') ?> <br/><br/>
<?php echo $this->translate('Pozdrawiamy!') ?> <br/>
<?php echo $this->translate('Serwis a-ajurweda.pl') ?> <br/><br/>
<span style='font-size: 10px;'><?php echo $this->translate('Zastrzegamy sobie prawo selekcji zamieszczanych informacji o sylwetkach.') ?> </span>

