W serwisie dokonano zmiany zdjęcia głównego firmy o nazwie: <br/>
<?php echo $this->company['Translation']['pl']['name']; ?> <br/>
Dokonaj moderacji firmy podążając za poniższym linkiem:
<a href="http://a-ajurweda.pl<?php echo $this->adminUrl('edit-company', 'company', array('id' => $this->company['id'])) ?>">
http://a-ajurweda.pl<?php echo $this->adminUrl('edit-company', 'company', array('id' => $this->company['id'])) ?>
</a>
<br/>
