Witamy serdecznie, <br/>
<br/>
dziękujemy, że jesteś naszym klientem. Z przyjemnością informujemy, że uruchomiliśmy nową odsłonę serwisu a-ajurweda.pl z większą ilością interakcji, nowymi funkcjonalnościami… i połączonym z nim sklepem internetowym - zielonysklep.com <br/>
<br/>
Prosimy: <br/>
- aktywuj swoje konto, klikając na poniższy link <br/>
(Twój adres emailowy będzie Twoim loginem) <br/>
<a href="<?php echo $this->url(array('token' => $this->token), 'domain-i18n:register-exists-client-token') ?>"><?php echo $this->url(array('token' => $this->token), 'domain-i18n:register-exists-client-token') ?></a><br/>
<br/>
- wprowadź dwukrotnie swoje hasło. <br/>
<br/>
Dziękujemy. Zapraszamy do nas, <br/>
<br/>
Zespół serwisu a-ajurweda.pl i zielonysklep.com <br/>
<br/>
<br/>
<br/>
a-ajurweda.pl to serwis informacyjny, który jest unikalnym na rynku polskim miejscem spotkania i wymiany informacji dotyczących ajurwedy. Znajdziesz w nim odpowiedzi na pytania dotyczące zdrowia i stylu życia, w oparciu o starożytną wiedzę medyczną. <br/>
<br/>
zielonysklep.com to sklep oferujący połączenie wiedzy i doświadczenia z bogatą gamę produktów naturalnych, produktów ajurwedyjskich, w tym książek, kosmetyków, suplementów diety, pysznych herbatek… <br/>
<br/>

