<?php

/**
 * Menu_Model_Doctrine_BaseMenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $target_type
 * @property string $route
 * @property string $target_id
 * @property string $target_href
 * @property integer $menu_id
 * @property string $custom_url
 * @property string $title
 * @property string $title_attr
 * @property string $slug
 * @property string $unique_id
 * @property string $css_class
 * @property integer $photo_root_id
 * @property Menu_Model_Doctrine_Menu $Menu
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Menu
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Menu_Model_Doctrine_BaseMenuItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_menu_item');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('target_type', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('target_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('target_href', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('menu_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('custom_url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title_attr', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('unique_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('css_class', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu_Model_Doctrine_Menu as Menu', array(
             'local' => 'menu_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasMany('Menu_Model_Doctrine_MenuItemTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'target_href',
              1 => 'slug',
              2 => 'title',
              3 => 'title_attr',
             ),
             'tableName' => 'menu_menu_item_translation',
             'className' => 'MenuItemTranslation',
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($i18n0);
        $this->actAs($nestedset0);
    }
}