<?php

/**
 * Menu_Model_Doctrine_MenuItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Menu_Model_Doctrine_MenuItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Menu_Model_Doctrine_MenuItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menu_Model_Doctrine_MenuItem');
    }
    
    public function getMenuItemsQuery($menuId) {
        $q = $this->createQuery('m')
                ->addSelect('m.*')
                ->andWhere('m.level > ?', 0)
                ->andWhere('m.root_id = ?', $menuId)
                ;
        return $q;
    }
    
    public function getMenuMainItemsQuery($menuId) {
        $q = $this->createQuery('m')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->leftJoin('m.Translation mt')
                ->andWhere('m.level = ?', 1)
                ->andWhere('m.root_id = ?', $menuId)
                ;
        return $q;
    }
    public function getSubMenuItemsQuery($od,$do) {
        $q = $this->createQuery('m')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->leftJoin('m.Translation mt')
                ->andWhere('m.level = ?', 2)
                ->andWhere('m.id > ?',$od)
                ->andWhere('m.id < ?',$do)
                ;
        return $q;
    }
    
    public function getMenuItemQuery(){
         $q = $this->createQuery('i')
                ->addSelect('i.*')
                ->addSelect('tr.*')
                ->leftJoin('i.Translation tr')
                ;
        return $q;
    }
}