<?php

/**
 * Menu_Model_Doctrine_MenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Menu_Model_Doctrine_MenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Menu_Model_Doctrine_MenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menu_Model_Doctrine_Menu');
    }
    
    public function resetLocation($location) {
        $this->createQuery()
                ->update()
                ->set('location', 'NULL')
                ->where('location = ?', $location)
                ->execute();
    }
}