<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#page_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-page-shop-data', 'page') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
   
    $("#page_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
});
</script>

<div class="container_12 clearfix leading">
    
    <div class="grid_12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('New page') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <div class="page-header">
                        <h4><?php echo $this->translate('Translations') ?></h4>
                    </div>
                    
                    <ul id="myTab" class="nav nav-tabs pattern">
                        <li class="dropdown">
                            <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                            <?php endforeach; ?>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <?php foreach($this->languages as $key => $language): ?>
                        <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                        <?php if($this->form->translations->getSubForm($language)): ?>
                            <?php echo $this->form->translations->getSubForm($language)->title ?>
                            <?php echo $this->form->translations->getSubForm($language)->content->setAttrib('class', 'tinymce') ?>
                        <?php endif; ?>
                            
                        <div class="title" style ="margin-top: 30px;">

                            <h4>
                                <span class="icon16 icomoon-icon-pencil"></span>
                                <span><?php echo $this->translate('Metatags') ?></span>
                            </h4>

                        </div>
                        <div class="content clearfix">
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                            <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                        </div>

                        </div>
                        <?php endforeach; ?>
                    </div>
                    
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-page-shop', 'page') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
         
    </div>
</div>

        