<?php foreach($this->photos as $photo): ?>
<li class="pull-left">
    <?php if($photo->getOffset()): ?>
    <a id="main_photo" href="/media/photos/<?php echo $photo->getOffset() ?>/<?php echo $photo->getFilename() ?>" rel="prettyPhoto" title="<?php echo $photo->getTitle() ?>">
        <img src="/media/photos/<?php echo $photo->getOffset() ?>/126x126/<?php echo $photo->getFilename() ?>" data-original="/media/photos/<?php echo $photo->getOffset() ?>/<?php echo $photo->getFilename() ?>" alt="<?php echo $photo->getTitle() ?>">
    </a>
    <?php else: ?>
    <a id="main_photo" href="/images/gallery/1.jpg" rel="prettyPhoto" title="<?php echo $this->translate('No photo') ?>">
        <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
    </a>
    <?php endif; ?>
    <div class="actionBtn">
        <?php if($this->type=='about-us'): ?>
            <a href="<?php echo $this->adminUrl('edit-photo', 'default', array('type' => 'page','element-id' => $this->page->getId(),'id' => $photo->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
            <a href="#" rel="<?php echo $photo->id; ?>" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
               
        <?php else: ?>
            <a class="move" href="<?php echo $this->adminUrl('move-page-photo', 'page', array('id' => $photo->id, 'move' => 'up', 'page' => $this->page->id)) ?>"><span class="icon16 minia-icon-arrow-left white"></span></a>
            <a href="#" rel="<?php echo $photo->id; ?>" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
            <a class="move" href="<?php echo $this->adminUrl('move-page-photo', 'page', array('id' => $photo->id, 'move' => 'down', 'page' => $this->page->id)) ?>"><span class="icon16 minia-icon-arrow-right white"></span></a>
        <?php endif; ?>
    </div>
</li>
<?php endforeach; ?>