<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.17.custom.min.js"></script>

<link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/lib/elfinder-2.0-rc1/css/elfinder.min.css">
<link rel="stylesheet" type="text/css" media="screen" href="/lib/elfinder-2.0-rc1/css/theme.css">
<script type="text/javascript" src="/lib/elfinder-2.0-rc1/js/elfinder.min.js"></script>

<script type="text/javascript" src="/lib/tinymce/tiny_mce_popup.js"></script>

<script type="text/javascript">
  var FileBrowserDialogue = {
    init: function() {
      // Here goes your code for setting your custom things onLoad.
    },
    mySubmit: function (URL) {
      var win = tinyMCEPopup.getWindowArg('window');

      // pass selected file path to TinyMCE
      win.document.getElementById(tinyMCEPopup.getWindowArg('input')).value = URL;

      // are we an image browser?
      if (typeof(win.ImageDialog) != 'undefined') {
        // update image dimensions
        if (win.ImageDialog.getImageData) {
          win.ImageDialog.getImageData();
        }
        // update preview if necessary
        if (win.ImageDialog.showPreviewImage) {
          win.ImageDialog.showPreviewImage(URL);
        }
      }

      // close popup window
      tinyMCEPopup.close();
    }
  }

  tinyMCEPopup.onInit.add(FileBrowserDialogue.init, FileBrowserDialogue);

  $().ready(function() {
    var elf = $('#elfinder').elfinder({
      // set your elFinder options here
      url: '/admin/media/elfinder',  // connector URL
      getFileCallback: function(url) { // editor callback
        FileBrowserDialogue.mySubmit(url); // pass selected file path to TinyMCE 
      }
    }).elfinder('instance');      
  });
</script>