<script src="http://maps.googleapis.com/maps/api/js?v=3.9&sensor=false" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
    
    $("form #address").keypress(function(e) {
        $("#google-map").trigger("address_changed");
    });
});
</script>
<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
        <div class="box">
            
            
                    <?php if($this->form->isErrors()): ?>
                    <div class="message error closeable">
                        <span class="message-close"></span>
                        <h3><?php echo $this->translate('Error') ?>!</h3>
                    </div>
                    <?php endif; ?>
                    <?php if($this->messages()->count()): ?>
                    <?php echo $this->messages()->render() ?>
                    <?php endif; ?>
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add producer') ?></span>
                </h4>
                
            </div>

            <div class="content">
                    <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>

                        <?php echo $this->form->owner ?>
                        <?php echo $this->form->email ?>
                        <?php echo $this->form->website ?>
                        <?php echo $this->form->phone ?>
                        <?php echo $this->form->province ?>
                        <?php echo $this->form->city ?>
                        <?php echo $this->form->address ?>
                        <?php echo $this->form->post_code ?>       
                        <?php echo $this->form->nip ?>
                        <?php echo $this->form->discount_id->setAttribs(array('class' => 'nostyle')) ?>
                        <?php echo $this->form->cord_x ?>
                        <?php echo $this->form->cord_y ?>
                        <?php echo $this->form->parent_id ?>
                        
                        <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>
                        
                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->name ?>
                                <?php echo $this->form->translations->getSubForm($language)->description ?>
                            <?php endif; ?>

                            <div class="title" style ="margin-top: 30px;">

                                <h4>
                                    <span class="icon16 icomoon-icon-pencil"></span>
                                    <span><?php echo $this->translate('Metatags') ?></span>
                                </h4>

                            </div>
                            <div class="content clearfix">
                                <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                            </div>

                            </div>
                            <?php endforeach; ?>
                        </div>

                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('list-producer', 'product') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                        
                        <div class="box">
                            <div id="google-map" style="height: 552px; width: 100%"></div> 
                        </div>
                    </form>
            </div>
            </div>
        </div>
</div>