<script type="text/javascript">
$(document).ready(function() {
 
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
    
    $('#explorer2').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
   
    $("#itemContainer").delegate("#add-photo", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
       // $("#explorer").modal({
        //    overlayCss: {"background": "black"}
       // });
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-preview-photo', 'product') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#id").val(resp.id);
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
              //  $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
        
        var elf = $('#elfinder2').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-preview-main-photo', 'product') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer2').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer2').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
            e.preventDefault();
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('remove-preview-main-photo', 'product') ?>/id/"+$('#id').val(),
                data: data,
                success: function(resp) {
                    if(resp.status == "success") {
                        $("#main_photo_con").html(resp.body);
                        $("#itemCon").trigger('update');
                    }
                }
            });
     }); 
     
     
     $("#category_tree_selection").dynatree({
        checkbox: true,  
        autoCollapse: true,
        minExpandLevel: 2
     });
    
     $("#category_tree_selection").click(function(){
        
        var selectedNodes = $("#category_tree_selection").dynatree("getTree").getSelectedNodes(); 

        var selectedKeys = $.map(selectedNodes, function(node){ 
            return node.data.key; 
        }); 
        
        var ids = new Array();
        for(var x=0; x<selectedKeys.length; x++){
            var id = selectedKeys[x];
            ids[x] = id.replace(/^node/, "");
        }
        
        $("#category_id option").each(function(i, elem) {
            $(elem).attr("selected", false);
        });
       
    
        for(id in ids) {
            var option = $("#category_id option[value="+ids[id]+"]");
            if(option) {
                $(option).attr("selected", "selected");
            }
        }   
     });
});
</script>

<div class="row-fluid">

    <div class="grid_12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit preview') ?> <?php echo $this->preview->getName(); ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
                   
                    <?php echo $this->form->id ?>
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->producer_id->setAttribs(array('class' => 'nostyle')) ?>
                     <br/>
                    <?php if ($this->form->category_id->hasErrors()): ?>
                          <div class="box" style="border: 1px solid red; width: 97%;">     
                        <?php else: ?>
                          <div class="box" style="border: 1px solid black; width: 97%;"> 
                        <?php endif; ?>
                            <div class="title">
                            <h4>
                                <span class="icon16 iconic-icon-list-nested"></span>
                                <span><?php echo $this->translate('Categories') ?></span>
                            </h4>

                            </div>
                            <div id="category_tree_selection">
                                <?php echo $this->partial('category-tree-selection.phtml', 'product', array('tree' => $this->categoryTree, 'parent' => $this->parent, 'selectedIds' => $this->form->category_id->getValue())) ?>
                            </div>    
                          </div>
                    <span style="display: none;">
                        <?php echo $this->form->category_id; ?>
                    </span>
                    <?php echo $this->form->description; ?> 
                    
                    <div class="page-header">
                         <h4><?php echo $this->translate('Main photo') ?></h4>
                    </div>  
                    <div id="itemCon">
                        <ul id="main_photo_con" class="galleryView center">
                            <li class="pull-left">
                                <?php if($this->preview->get('PhotoRoot')->getOffset()): ?>
                                <a id="main_photo" href="/media/photos/<?php echo $this->preview->get('PhotoRoot')->getOffset() ?>/<?php echo $this->preview->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->preview->get('PhotoRoot')->getTitle() ?>">
                                    <img src="/media/photos/<?php echo $this->preview->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->preview->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->preview->get('PhotoRoot')->getOffset() ?>/<?php echo $this->preview->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->preview->get('PhotoRoot')->getTitle() ?>">
                                </a>
                                <?php else: ?>
                                <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                    <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                </a>
                                <?php endif; ?>
                                <div class="actionBtn">
                                    <a href="<?php echo $this->adminUrl('edit-preview-main-photo', 'product', array('preview-id' => $this->preview->getId(), 'id' => $this->preview->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                    <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                </div>
                            </li>
                        </ul>
                    </div> 
                    
                    <div class="clearfix"></div>
                    <div class="page-header">
                         <h4><?php echo $this->translate('Gallery View') ?></h4>
                    </div>                  
                      <div id="itemContainer">           
                        <button href="#" id="add-photo" style="width: 120px;"><?php echo $this->translate('Add photo') ?></button>
                        <ul id="main_photo_container" class="galleryView center">                           
                                <?php echo $this->partial('admin/preview-main-photo.phtml', 'product', array('photos' => $this->previewPhotos, 'preview' => $this->preview)) ?>
                        </ul>
                      </div>
                          
                    <?php echo $this->form->youtube ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-preview', 'product') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>                  
                </form>
            
            </div>
            
        </div>
        <div class="box">

                    <div class="title">

                        <h4>
                            <span class="icon16 icomoon-icon-pencil"></span>
                            <span><?php echo $this->translate('Metatags') ?></span>
                        </h4>

                    </div>
                    <div class="content clearfix">
                        <?php echo $this->form->metatags ?>
                    </div>

        </div>
    </div>   
    
</div>     
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
<div id="explorer2" class="dialog"><div id="elfinder2"></div></div>
    