<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#product_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-product-data', 'product') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { sWidth: '100px' },
            null,
            { sWidth: '100px' },
            { "bSortable": false, sWidth: '160px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#product_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Products') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-product', 'product') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="product_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Id') ?></th>
                            <th><?php echo $this->translate('Name') ?></th>
                            <th><?php echo $this->translate('Categories') ?></th>
                            <th><?php echo $this->translate('Price') ?></th>
                            <th><?php echo $this->translate('Availability') ?></th>
                            <th><?php echo $this->translate('Status') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>