<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#comments_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-comment-data', 'product') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { sWidth: '250px' },
            { sWidth: '150px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#comments_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-comments-7"></span>
                    <span><?php echo $this->translate('Comments') ?></span>
               </h4> 
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="comments_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name product') ?></th>
                        <th><?php echo $this->translate('User') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>