<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#category_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-category-data', 'product', array('id' => $this->parent->getId())) ?>",
        "aaSorting": [[ 1, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#category_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    }); 
});
</script>

<div class="row-fluid">
    <div class="span12">
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 iconic-icon-list-nested"></span>
                    <span><?php echo $this->translate('Category tree') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-category', 'product', array('id' => $this->parent->getId())) ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add subcategories') ?></a>
                    </div>
                </h4>

            </div>
            <div class="content">
                
                <div id="category_tree">
                    <?php echo $this->partial('category-tree.phtml', 'product', array('tree' => $this->categoryTree, 'parent' => $this->parent, 'adminLanguage' => $this->adminLanguage)) ?>
                </div>
                
            </div>

        </div><!-- End .box -->
        
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 minia-icon-list-2"></span>
                    <span><?php echo $this->translate('Subcategories') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="category_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>
            
        </div>

    </div>


</div>