<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#producer_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-producer-data', 'product') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { sWidth: '250px' },
            { sWidth: '200px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#producer_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    $("#producer_table").delegate("td .move", "click", function(e) {
        e.preventDefault();
        $.ajax({
            url: $(this).attr("href"),
            type: "post",
            dataType: "json",
            data: {format: "json"},
            success: function (resp) {
                $("#producer_table").trigger("update");
            }
        });
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-user-4"></span>
                    <span><?php echo $this->translate('Producers') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-producer', 'product') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
               </h4>
            
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="producer_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Producer') ?></th>
                        <th><?php echo $this->translate('Owner') ?></th>
                        <th><?php echo $this->translate('Website') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Move') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>