
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Nowa galeria') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <div class="gallery-header">
                        <h4><?php echo $this->translate('Translations') ?></h4>
                    </div>
                    
                    <ul id="myTab" class="nav nav-tabs pattern">
                        <li class="dropdown">
                            <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($key == 0): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                            <?php endforeach; ?>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <?php foreach($this->languages as $key => $language): ?>
                        <div class="tab-pane<?php if($key == 0): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                        <?php if($this->form->translations->getSubForm($language)): ?>
                            <?php echo $this->form->translations->getSubForm($language)->name ?>
                            <?php echo $this->form->translations->getSubForm($language)->description->setAttrib('class', 'tinymce') ?>
                        <?php endif; ?>

                        </div>
                        <?php endforeach; ?>
                    </div>
                    
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-gallery', 'gallery') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Metatags') ?></span>
                </h4>

            </div>
            <div class="content clearfix">
                <?php echo $this->form->metatags ?>
            </div>

        </div>
        
    </div>


</div>

        
    