<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<section class="page_title_2 translucent_bg_color_scheme image_bg_9 image_fixed t_align_c relative wrapper">
	<div class="container">
		<h2 class="color_light fw_light m_bottom_5"><?php echo $this->page['Translation'][$this->language]['title']; ?></h2>
		<!--breadcrumbs-->
		<ul class="hr_list d_inline_m breadcrumbs">
			<li class="m_right_8 f_xs_none"><a href="/" class="color_grey_light_3 d_inline_m m_right_10">Strona główna</a><i class="icon-angle-right d_inline_m color_grey_light_3 fs_small"></i></li>
			<li><a class="color_grey_light_3 d_inline_m"><?php echo $this->page['Translation'][$this->language]['title']; ?></a></li>
		</ul>
	</div>
</section>
<section class="section_offset">
	<main class="container t_align_j">
	    
	    <div class="col-lg-7 col-md-7 col-sm-7 m_xs_bottom_20">
		<h3 class="color_dark fw_light m_bottom_15 heading_1"><?php echo $this->page['Translation'][$this->language]['title']; ?></h3>
		<p class="m_bottom_35 heading_2"></p>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_20 t_align_l">
				<img src="/media/photos/<?php echo $this->page['PhotoRoot']['offset']."/270x155/".$this->page['PhotoRoot']['filename']; ?>" class="r_corners wrapper f_left m_right_30 m_bottom_10 f_xs_none m_xs_right_0 m_xs_bottom_20" alt="Jak stosować ecoslim">
			
			    <?php echo $this->page['Translation'][$this->language]['content']; ?>
			</div>
		</div>
	    </div>
	    
	    <div class="col-lg-5 col-md-5 col-sm-5 m_xs_bottom_20">
			<!--content-->
			<div class="section_offset m_top_0 p_top_0">
				<div class="clearfix">
					<div class="row">
						<section class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_30">
							<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c">FAQ</h3>
							<p class="m_bottom_35 heading_2 t_align_c">Najczęściej zadawane pytania. </p>		
							<div class="tabs t_align_c">
								<!--tabs nav-->
								<ul class="tabs_nav type_2 fs_medium hr_list d_inline_b d_xs_block m_bottom_30 m_xs_bottom_20">
									<li class="f_xs_none"><a href="#tab-1" class="color_dark d_block n_sc_hover">Zobacz poniżej</a></li>
								</ul>
								<!--tabs content-->
								<div id="tab-1">
									<div class="accordion t_align_l">
									    <?php foreach($this->faqs as $faq): ?>
										<dl class="accordion_item r_corners wrapper m_bottom_5 tr_all">
											<dt class="accordion_link relative color_dark tr_all"><?php echo $faq['Translation'][$this->language]['title']; ?>
												<span class="icon_wrap_size_1 circle d_block hide">
													<i class="icon-minus"></i>
												</span>
												<span class="icon_wrap_size_1 circle d_block show">
													<i class="icon-plus"></i>
												</span>
											</dt>
											<dd class="fw_light color_dark"><?php echo $faq['Translation'][$this->language]['content']; ?></dd>
										</dl>
									    <?php endforeach; ?>
										
									</div>
								</div>
							</div>
						</section>
					</div>
				</div>
			</div>
	    </div>
	</main>
			<div class="clearfix"></div>
</section>