<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<section class="page_title_2 translucent_bg_color_scheme image_bg_9 image_fixed t_align_c relative wrapper">
	<div class="container">
		<h2 class="color_light fw_light m_bottom_5"><?php echo $this->page['Translation'][$this->language]['title']; ?></h2>
		<!--breadcrumbs-->
		<ul class="hr_list d_inline_m breadcrumbs">
			<li class="m_right_8 f_xs_none"><a href="/" class="color_grey_light_3 d_inline_m m_right_10">Strona główna</a><i class="icon-angle-right d_inline_m color_grey_light_3 fs_small"></i></li>
			<li><a class="color_grey_light_3 d_inline_m"><?php echo $this->page['Translation'][$this->language]['title']; ?></a></li>
		</ul>
	</div>
</section>
<section class="section_offset">
	<main class="container">
	    
	    <div class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_20 t_align_j">
		<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c"><?php echo $this->page['Translation'][$this->language]['title']; ?></h3>
		<p class="m_bottom_35 heading_2"></p>
		<div class="row">
		    <?php if(strlen($this->page['PhotoRoot']['offset'])): ?>
			<div class="col-lg-4 col-md-4 col-sm-4 m_xs_bottom_4">
				<img src="/media/photos/<?php echo $this->page['PhotoRoot']['offset']."/270x155/".$this->page['PhotoRoot']['filename']; ?>" class="r_corners wrapper f_left m_right_30 m_bottom_10 f_xs_none m_xs_right_0 m_xs_bottom_20" alt="Jak stosować ecoslim">
			</div>
		    
			<div class="col-lg-8 col-md-8 col-sm-8 m_xs_bottom_8 ">
			    <?php echo $this->page['Translation'][$this->language]['content']; ?>
			</div>
		    <?php else: ?>
		    
			<div class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_8 ">
			    <?php echo $this->page['Translation'][$this->language]['content']; ?>
			</div>
		    <?php endif; ?>
		</div>
	    </div>
	    
	</main>
			<div class="clearfix"></div>
</section>