<?php

/**
 * News_Model_Doctrine_ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_Doctrine_ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_Doctrine_ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Doctrine_Article');
    }
    
    public function getPublishArticleQuery($id, $field = 'id') {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->addSelect('m.*')
                ->leftJoin('a.Translation at')
                ->leftJoin('a.Metatags m')
                ->andWhere('(a.publish = ? AND (a.publish_date <= ? OR a.publish_date IS NULL))', array(1, date('Y-m-d H:i:s')))
                ;
        if(is_integer($id)) {
            $q->andWhere('a.' . $field . ' = ?', array($id));
        } elseif(is_array($id) && !empty($id)) {
            $q->andWhere('a.' . $field . ' IN ?', array($id));
        }
        return $q;
    }

    public function getPhotoQuery(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('a');
            $q->addSelect('a.*');
        }
        $q->addSelect('pr.*');
        $q->addSelect('p.*');
        $q->leftJoin('a.PhotoRoot pr');
        $q->leftJoin('a.Photos p');
        return $q;
    }
    
    public function getLimitQuery($limit, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('a');
            $q->addSelect('a.*');
        }
        $q->limit($limit);
        return $q;
    }
    
    public function getCategoryIdQuery($categoryId = null, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('ac');
        }
        $q->addSelect('ac.*');
        $q->leftJoin('a.Category ac');
        if(is_integer($categoryId)) {
            $q->andWhere('ac.id');
        } elseif(is_array($categoryId && !empty($categoryId))) {
            $q->andWhere('ac.id IN ?', array($categoryId));
        }
        return $q;
    }
    
    public function getAllNewsQuery() {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->addSelect('pr.*')
                ->leftJoin('a.PhotoRoot pr')
                ->leftJoin('a.Translation at');
        return $q;
    }
}