<?php

/**
 * News_Model_Doctrine_BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $last_user_id
 * @property string $title
 * @property string $slug
 * @property clob $content
 * @property boolean $publish
 * @property boolean $gallery
 * @property boolean $breaking_news
 * @property timestamp $publish_date
 * @property integer $photo_root_id
 * @property integer $metatag_id
 * @property integer $video_root_id
 * @property integer $category_id
 * @property boolean $student
 * @property boolean $student_accept
 * @property integer $group_id
 * @property integer $views
 * @property boolean $show_views
 * @property Doctrine_Collection $Translation
 * @property News_Model_Doctrine_Category $Category
 * @property Doctrine_Collection $Comments
 * @property News_Model_Doctrine_Group $Group
 * @property Doctrine_Collection $Tags
 * 
 * @package    Admi
 * @subpackage News
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class News_Model_Doctrine_BaseNews extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('news_news');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('last_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('publish', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('gallery', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('breaking_news', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('publish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('metatag_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('video_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('student', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('student_accept', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('views', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('show_views', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('News_Model_Doctrine_NewsTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('News_Model_Doctrine_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('News_Model_Doctrine_Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'news_id'));

        $this->hasOne('News_Model_Doctrine_Group as Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('News_Model_Doctrine_Tag as Tags', array(
             'refClass' => 'News_Model_Doctrine_NewsTag',
             'local' => 'news_id',
             'foreign' => 'tag_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'slug',
              2 => 'content',
             ),
             'tableName' => 'news_news_translation',
             'className' => 'NewsTranslation',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}