<?php

/**
 * News_Model_Doctrine_NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_Doctrine_NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_Doctrine_NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Doctrine_News');
    }
    
     public function getNewsQuery() {
          $q = $this->createQuery('n')
                ->select('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('p.*')
                ->addSelect('c.*')
                ->leftJoin('n.Translation nt')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
        $q->leftJoin('n.Photos p');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        $q->leftJoin('n.Comments c');
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
   
    public function getLastNewsQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('pr.*')
                ->leftJoin('n.Translation nt')
                ;
        
        $q->leftJoin('n.PhotoRoot pr')
     //   $q->leftJoin('n.Photos p')
                ->leftJoin('n.Category c');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    } 
    
    public function getShowNewsQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('p.*')
                ->leftJoin('n.Translation nt')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
        $q->leftJoin('n.Photos p')
                ->leftJoin('n.Category c');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        return $q;
    }
    
    public function getBreakingNewsQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('c.*')
                ->leftJoin('n.Translation nt')
                
        
                ->leftJoin('n.Category c');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
    public function getNewsCategoryListQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('p.*')
                ->addSelect('vr.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.VideoRoot vr');
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
        $q//->leftJoin('n.Photos p')
                ->leftJoin('n.Category c');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
    public function getNewsStudentListQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('p.*')
                ->addSelect('vr.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.VideoRoot vr');
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
        $q//->leftJoin('n.Photos p')
                ->leftJoin('n.Category c');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        $q->addWhere('n.student = 1');
        return $q;
    }
    
    public function getNewsGroupListQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('g.*')
                ->addSelect('p.*')
                ->addSelect('vr.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.VideoRoot vr');
                
        $q->leftJoin('n.PhotoRoot pr');
        $q//->leftJoin('n.Photos p')
                ->leftJoin('n.Category c')
                ->leftJoin('n.Group g');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
    public function getNewsTagListQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('t.*')
                ->addSelect('p.*')
                ->addSelect('vr.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.VideoRoot vr');
                
        $q->leftJoin('n.PhotoRoot pr');
        $q//->leftJoin('n.Photos p')
                ->leftJoin('n.Category c')
                ->leftJoin('n.Tags t');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
    public function getNewsCategoryQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('p.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.Category c')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
       // $q->leftJoin('n.Photos p');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
     public function getNewsCommentQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->addSelect('p.*')
                ->leftJoin('n.Translation nt')
                ->leftJoin('n.Comments c')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
       // $q->leftJoin('n.Photos p');
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    }
    
     public function getPublishNewsQuery() {
        $q = $this->createQuery('n')
                ->select('n.*')
                ->addSelect('nt.*')
                ->addSelect('pr.*')
                ->addSelect('p.*')
                ->addSelect('c.*')
                ->leftJoin('n.Translation nt')
                ;
        
        $q->leftJoin('n.PhotoRoot pr');
       // $q->leftJoin('n.Photos p');
        $q->addWhere('n.publish = 1');
        $q->addWhere('n.publish_date <= NOW()');
        $q->leftJoin('n.Comments c');
        $q->addWhere('n.student_accept IN (IF(n.student = 1, "1","0,1"))');
        return $q;
    } 
}