<?php

/**
 * News_Model_Doctrine_NewsTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_Doctrine_NewsTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_Doctrine_NewsTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Doctrine_NewsTranslation');
    }
}