<?php

/**
 * News_Model_Doctrine_StreamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_Doctrine_StreamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_Doctrine_StreamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Doctrine_Stream');
    }
    
    public function getShowStreamQuery() {
        $q = $this->createQuery('n')
                ->addSelect('n.*')
                ->addSelect('nt.*')
                ->leftJoin('n.Translation nt')
                ;
        
        return $q;
    }
}