<link href="http://vjs.zencdn.net/4.10/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/4.10/video.js"></script>
<script type="text/javascript">
$(document).ready(function() {
   
     $('.section').hide();
     $('.contentSection').show();
     $('.btnList li').click(function(){
        var rel = $(this).attr('rel');
        $('.section').hide();
        $('.'+rel).show();
     });
     
     $('#refresh_preview').click(function(){
         var rand = Math.round(Math.random()*10) + 1;
         $('.cool-video').remove();
         $('#refresh_preview').after("<video id='really-cool-video"+rand+"' class='cool-video cool-video video-js vjs-default-skin' controls width='640' height='264'><source id='source_elem"+rand+"'><p class='vjs-no-js'>To view this video please enable JavaScript, and consider upgrading to a web browser that <a href='http://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a> </p></video>");
         $('#source_elem'+rand).attr('src',$('#url').val());
         $('#source_elem'+rand).attr('type',$('#type').val());
          var player = videojs('really-cool-video'+rand, { /* Options */ }, function() {
              this.play();
            }); 
         
     });
});
</script>

<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
         <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add stream') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                <?php if($this->form->isErrors()): ?>
                <span class="errorMessage">
                    Błąd
                </span>
                  <?php endif; ?>
                <ul class="btnList">
                    <li rel="contentSection"><button class="btn" type="button">Treść</button></li>
                    <li rel="optionsSection"><button class="btn" type="button">Opcje</button></li>
                    <li rel="videoSection"><button class="btn" type="button">Video</button></li>
                    <li rel="metatagSection"><button class="btn" type="button">Pokaż metatagi</button></li>
                </ul>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <span class="section contentSection metatagSection">
                        <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>

                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                                <span class="section contentSection">
                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->title ?>
                                <?php echo $this->form->translations->getSubForm($language)->content ?>
                            <?php endif; ?>
                                </span>
                                <span class="section metatagSection">
                                    <div class="title" style ="margin-top: 30px;">

                                        <h4>
                                            <span class="icon16 icomoon-icon-pencil"></span>
                                            <span><?php echo $this->translate('Metatags') ?></span>
                                        </h4>

                                    </div>
                                    <div class="content clearfix">
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                    </div>
                                </span>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </span>
                    <span class="section optionsSection">
                        <?php echo $this->form->publish ?>
                        <?php echo $this->form->id ?>
                    </span>
                    <span class="section videoSection">
                        <div class="box" style="width: 97%">
                            <div class="title">
                                <h4>
                                    <span class="icon16 entypo-icon-attachment"></span>
                                    <span><?php echo $this->translate('Videos') ?></span>
                                    
                                </h4>  
                            </div>    

                            <div class="content">

                                        <?php echo $this->form->url ?>
                                        <?php echo $this->form->hls_url ?>
                                        <?php echo $this->form->type ?>
                                  
                                        <a id="refresh_preview" style="display:block">Odśwież podgląd</a>
                                        <video id="really-cool-video" class="cool-video video-js vjs-default-skin" controls width="640" height="264">
                                            <source id="source_elem">
                                            <p class="vjs-no-js">
                                                To view this video please enable JavaScript, and consider upgrading to a web browser
                                                that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                                            </p>
                                        </video>

                            </div>
          
                        </div>
                    </span>
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-stream', 'news') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
                
                
            
            </div>
            
        </div>
        </div>
</div>

