<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#news_table").dataTable( {

     "bFilter": true,
     "bSearchable": true,
        "bProcessing": true,
       
        "bServerSide": true,
       
        "bLengthChange": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-tag-data', 'news') ?>",
        "iDisplayLength": 50,
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            { sWidth: '100px' },
            null,
            { "bSortable": false, sWidth: '100px' }
        ]
               
    });
    
    
});


</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span><?php echo $this->translate('Tags') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-tag', 'news') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="news_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Id') ?></th>
                        <th><?php echo $this->translate('Title') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                         <?php echo $this->result; ?>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>