<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#news_table").dataTable( {
"sPaginationType": "full_numbers",
     "bFilter": true,
     "bSearchable": true,
        "bProcessing": true,
       
        "bServerSide": true,
       
        "bLengthChange": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-comment-data', 'news') ?>",
        "iDisplayLength": 50,
        "aaSorting": [[ 3, "desc" ]],
        "aoColumns": [
            { sWidth: '200px' },
            
            { sWidth: '200px' },
            null,
            { sWidth: '150px' },
            
            { sWidth: '150px' },
            
            { "bSortable": false, sWidth: '100px' }
        ]
               
    }).yadcf([
        {
          column_number: 0,
          filter_type: "auto_complete"
          
        },
        {
          column_number: 1,
          filter_type: "text"
        },
        {
          column_number: 2,
          filter_type: "text",
        },
        {
          column_number: 3,
          filter_type: "range_date",
          date_format: "yyyy-mm-dd"
        },
        {
          column_number: 4,
          filter_type: "text",
        },
        
        ]);
    
    
});


</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span><?php echo $this->translate('Comments') ?></span>
                    
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="news_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th>Aktualność</th>
                            <th>Użytkownik</th>
                            <th>Komentarz</th>
                            <th><?php echo $this->translate('Created') ?></th>
                            <th><?php echo $this->translate('Ip') ?></th>
                            <th><?php echo $this->translate('Active') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>