<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><!--[if IE 7 ]>    <html class="ie7 oldie" lang="pl"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8 oldie" lang="pl"> <![endif]-->
<!--[if IE ]>    <html class="ie" lang="pl"> <![endif]-->
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<html lang="pl">
    <head>
        <meta charset="utf-8">
    </head>
    <body>

        <div style="color: #919191; background: #000000; border-radius: 10px; padding: 0px 20px 20px 20px; background: url(http://139.testujemy.info/images/layout/bg.jpg);">
        <div>
            <img src="http://<?php echo $this->domain; ?>/images/layout/logo.png">
            <h1>Club 139</h1>
        </div>
        <h3 style="color: #ffffff;"><?php echo $this->title ?></h3>
        <?php echo $this->content; ?>
        </div>

    </body>
</html>