<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('menu_menu', 'menu_menu_root_id_menu_menu_item_id', array(
             'name' => 'menu_menu_root_id_menu_menu_item_id',
             'local' => 'root_id',
             'foreign' => 'id',
             'foreignTable' => 'menu_menu_item',
             ));
        $this->createForeignKey('menu_menu_item', 'menu_menu_item_menu_id_menu_menu_id', array(
             'name' => 'menu_menu_item_menu_id_menu_menu_id',
             'local' => 'menu_id',
             'foreign' => 'id',
             'foreignTable' => 'menu_menu',
             ));
        $this->createForeignKey('menu_menu_item_translation', 'menu_menu_item_translation_id_menu_menu_item_id', array(
             'name' => 'menu_menu_item_translation_id_menu_menu_item_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'menu_menu_item',
             ));
        $this->createForeignKey('menu_menu_item_translation', 'menu_menu_item_translation_id_menu_menu_item_id_1', array(
             'name' => 'menu_menu_item_translation_id_menu_menu_item_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'menu_menu_item',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('menu_menu', 'menu_menu_root_id', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->addIndex('menu_menu_item', 'menu_menu_item_menu_id', array(
             'fields' => 
             array(
              0 => 'menu_id',
             ),
             ));
        $this->addIndex('menu_menu_item_translation', 'menu_menu_item_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('menu_menu', 'menu_menu_root_id_menu_menu_item_id');
        $this->dropForeignKey('menu_menu_item', 'menu_menu_item_menu_id_menu_menu_id');
        $this->dropForeignKey('menu_menu_item_translation', 'menu_menu_item_translation_id_menu_menu_item_id');
        $this->dropForeignKey('menu_menu_item_translation', 'menu_menu_item_translation_id_menu_menu_item_id_1');
        $this->removeIndex('menu_menu', 'menu_menu_root_id', array(
             'fields' => 
             array(
              0 => 'root_id',
             ),
             ));
        $this->removeIndex('menu_menu_item', 'menu_menu_item_menu_id', array(
             'fields' => 
             array(
              0 => 'menu_id',
             ),
             ));
        $this->removeIndex('menu_menu_item_translation', 'menu_menu_item_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}