<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('page_page', 'page_page_user_id_user_user_id');
        $this->dropForeignKey('page_page', 'page_page_metatag_id_default_metatag_id');
    }

    public function down()
    {
        $this->createForeignKey('page_page', 'page_page_user_id_user_user_id', array(
             'name' => 'page_page_user_id_user_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('page_page', 'page_page_metatag_id_default_metatag_id', array(
             'name' => 'page_page_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
    }
}