<script type="text/javascript">
$(document).ready(function() {
    
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
    
    $("#itemCon").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-footer-item-photo', 'menu') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });

    $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
            e.preventDefault();
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('remove-footer-item-photo', 'menu') ?>/id/"+$('#id').val(),
                data: data,
                success: function(resp) {
                    if(resp.status == "success") {
                        $("#main_photo_con").html(resp.body);
                        $("#itemCon").trigger('update');
                    }
                }
            });
     });  

    var oTable = $("#menu_item_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-footer-item-data', 'menu', array('id' => $this->menu['id'], 'item' => $this->menuItem['id'])) ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            null,
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#menu_item_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    $("#target").select2();

    $("#save-button").click(function(e) {
        e.preventDefault();

        $("#form").append("<input type='hidden' name='saveOnly' value='1' />");
        $("#form #submit").trigger("click");
    });
    
});
</script>
<div class="row-fluid">
    
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Edit footer') ?> <?php echo $this->menuItem->Translation[$this->language]->title ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    <ul id="myTab" class="nav nav-tabs pattern">
                        <li class="dropdown">
                            <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($key == 0): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                            <?php endforeach; ?>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <?php foreach($this->languages as $key => $language): ?>
                        <div class="tab-pane<?php if($key == 0): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                        <?php if($this->form->translations->getSubForm($language)): ?>
                            <?php echo $this->form->translations->getSubForm($language)->title ?>
                            <?php echo $this->form->translations->getSubForm($language)->title_attr ?>
                        <?php endif; ?>

                        </div>
                        <?php endforeach; ?>
                    </div>
                    
                    <?php echo $this->form->target->setAttribs(array('class' => 'nostyle')) ?>
                    <?php echo $this->form->unique_id ?>
                    <?php echo $this->form->css_class ?>
                    <?php echo $this->form->parent_id ?>
                    <?php echo $this->form->menu_id ?>
                    <?php echo $this->form->id ?>
                    
                    <div class="page-header">
                         <h4><?php echo $this->translate('Photo') ?></h4>
                    </div>  
                    <div id="itemCon">
                        <ul id="main_photo_con" class="galleryView center">
                            <li class="pull-left">
                                <?php if($this->item->get('PhotoRoot')->getOffset()): ?>
                                <a id="main_photo" href="/media/photos/<?php echo $this->item->get('PhotoRoot')->getOffset() ?>/<?php echo $this->item->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->item->get('PhotoRoot')->getTitle() ?>">
                                    <img src="/media/photos/<?php echo $this->item->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->item->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->item->get('PhotoRoot')->getOffset() ?>/<?php echo $this->item->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->item->get('PhotoRoot')->getTitle() ?>">
                                </a>
                                <?php else: ?>
                                <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                    <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                </a>
                                <?php endif; ?>
                                <div class="actionBtn">
                                    <a href="<?php echo $this->adminUrl('edit-footer-item-photo', 'menu', array('menu-id' => $this->item->getId(), 'id' => $this->item->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                    <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                </div>
                            </li>
                        </ul>
                    </div> 
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-footer', 'menu') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>

        </div><!-- End .box -->

   
        
    <div class="box">
            
            <div class="title">

                <h4 class="clearfix">
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Footer tree') ?></span>
                    <form class="box-form right" action="<?php echo $this->addForm->getAction() ?>" method="post">
                        <span class="span8">
                            <input type="text" name="title" class="search-query span2 text" placeholder="<?php echo $this->translate('Title') ?>">
                        </span>
                        <span class="span4">
                            <button class="btn btn-success btn-small" type="submit"><?php echo $this->translate('Add') ?></button>
                        </span>
                        <?php echo $this->addForm->menu_id ?>
                        <?php echo $this->addForm->parent_id ?>
                    </form>
                </h4>
                
            </div>
            <div class="content clearfix">

                <div id="menu_tree">
                    <?php echo $this->partial('footer_tree.phtml', 'menu', array('tree' => $this->tree, 'parent' => $this->menuItem, 'language' => $this->language)) ?>
                </div>
                
            </div>

        </div><!-- End .box -->
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Footer') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="menu_item_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th><?php echo $this->translate('Name') ?></th>
                            <th><?php echo $this->translate('Footer') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->
        
    </div>
</div>
<div id="explorer" class="dialog"><div id="elfinder"></div></div>