<script type="text/javascript">
$(document).ready(function() {
    
    $("#subscriber_id").select2();
    
});
</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit group') ?></span>
                </h4>

            </div>
            <div class="content clearfix">

                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->subscriber_id->setAttribs(array('class' => 'nostyle')); ?>
                    
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-group', 'newsletter') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            </div>

        </div>
            
    </div>
</div>