<script type="text/javascript">
$(document).ready(function() {
    
    $("#subscriber_id").select2();
    $("#group_id").select2();
//    $("#news_id").select2();
//    $("#event_id").select2();
    $("#product_id").select2();
//    $("#company_id").select2();
    
//    var newsIds = Array();
//    newsIds = $('#news_id').val();
    
//    var eventsIds = Array();
//    eventsIds = $('#event_id').val();

    var productsIds = Array();
    productsIds = $('#product_id').val();
    
//    var companiesIds = Array();
//    companiesIds = $('#company_id').val();
    
   tinymce.init({
    selector: ".tinymce2",

		// General options
		theme : "modern",
		plugins: [
                        "responsivefilemanager advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                        "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                        "save table contextmenu directionality emoticons template paste textcolor"
                ],
                
                width: "100%",
                height: "400px",
                entity_encoding: "raw",
                
               toolbar1: " filemanager, fullscreen,template,insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "| responsivefilemanager | print preview media | forecolor backcolor emoticons",
      
                // Example content CSS (should be your site CSS)
                content_css : "/css/content-tiny.css",   
                
                template_cdate_classes: "cdate creationdate",
                template_mdate_classes: "mdate modifieddate",
                template_selected_content_classes: "selcontent",
                template_cdate_format: "%m/%d/%Y : %H:%M:%S",
                template_mdate_format: "%m/%d/%Y : %H:%M:%S",
                 external_filemanager_path:"/filemanager/",
   filemanager_title:"Responsive Filemanager",
                relative_urls: false,
                remove_script_host: false,

                templates : [
                    {
                        title: "Header",
                        url: "<?php echo $this->adminUrl('header-template', 'newsletter') ?>",
                        description: "Header template"
                    },
                   
                    {
                        title: "The newest products",
                        url: "<?php echo $this->adminUrl('newest-products-template', 'newsletter') ?>/products-ids/"+productsIds,
                        description: "The newest products template"
                    },
                    {
                        title: "Footer",
                        url: "<?php echo $this->adminUrl('footer-template', 'newsletter') ?>",
                        description: "Footer template"
                    }
                ],
    });
    
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit message') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="#" method="POST" enctype="multipart/form-data">
                                        
                    <?php echo $this->form->title ?>
                    <?php// echo $this->form->news_id->setAttribs(array('class' => 'nostyle')); ?> 
                    <?php// echo $this->form->event_id->setAttribs(array('class' => 'nostyle')); ?> 
                    <?php// echo $this->form->company_id->setAttribs(array('class' => 'nostyle')); ?> 
                    <?php // echo $this->form->product_id->setAttribs(array('class' => 'nostyle')); ?> 
                    <?php echo $this->form->content ?>
                    <?php echo $this->form->all_subscribers ?>
                    <?php if($this->allSubscribers == 0): ?>
                        <?php echo $this->form->subscriber_id->setAttribs(array('class' => 'nostyle')); ?> 
                        <?php echo $this->form->group_id->setAttribs(array('class' => 'nostyle')); ?>
                    <?php endif; ?>
                    
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-message', 'newsletter') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
        
    </div>
</div>