<table width="800px" style="margin-left: auto; margin-right: auto; background: url(/images/layout/belka.png) repeat-x; margin-top: 10px; height: 50px;"> 
    <tr style="margin: 0px; padding: 0px;">
        <td style="width: 60%; vertical-align: middle;">
            <table> 
                <tr>
                    <td>
                        <img src="/images/logo.png" class="logo" alt="Calvarianum" width="40px">
                        <!--<img src="/images/layout/ajurweda/logo_stopka.png" alt="Logo stopka" width="40px"/>-->
                    </td>
                    <td style="color: #5d563c;font-size: 12px;">
                        CALVARIANUM<br />Wydawnictwo oo. Bernardynów<br />
                        34-130 Kalwaria Zebrzydowska<br />
                        ul. Bernardyńska 46
                    </td>
                </tr>
            </table>
        </td>
        <td style="width: 40%; vertical-align: top; color: #5d563c;">
            <div style="font-size: 12px; padding-top: 10px; text-align: right; margin-right: 10px;">
                Redakcja <br />
                
                30-960 Kraków <br />
ul. Bernardyńska 2<br />
skr. poczt. 765<br />
 
<br />
               © Copyright calvarianum.pl 2014
            </div>
        </td>
    </tr>
</table>

