<table width="800px" style="margin-left: auto; margin-right: auto;"> 
    <tr>
        <td style="width: 87%">
            <img src="/images/layout/ajurweda/poczta_ico.png" />
            <font color="#958f8a">wydawnictwo@calvarianum.pl</font>
            <img src="/images/layout/ajurweda/telef_ico.png" style="margin-left: 20px;"/>
            <font color="#958f8a">+48 12 422-16-50 w. 73</font>
             <img src="/images/layout/ajurweda/icon_fax.png" style="margin-left: 20px;"/>
            <font color="#958f8a">+48 12 432-22-30</font>
        </td>
        <td style="width: 12%;margin: 0px 5px;">
	 
</td>
       
    </tr>
</table>
<table width="800px" style="margin-left: auto; margin-right: auto;"> 
    <tr>
        <td style="width: 40%;padding: 10px 0px;padding-bottom: 0px;">
            <img src="/images/napisa.png" alt="Wydawnictwo CALVARIANUM"  height="55px"/>
        </td>
        <td class="text" style="width: 60%; vertical-align: top; color: #5d563c;">
            <img src="/images/mailing1a.jpg" class="logo" alt="Calvarianum" style="float:right;margin-right:10px;">
        </td>
    </tr>
     
</table>
<table width="800px" style="margin-left: auto; margin-right: auto;"> 
   <tr>
        
        <td class="text" style="min-height:30px; vertical-align: top;  color: #5d563c;margin: 0px 5px;padding:10px 5px">
            Lorem ipsum sit dolorem
        </td>
    </tr>
     
</table>
