<script type="text/javascript">	
    
$(document).ready(function() {
    
    <?php if($this->counter > 0): ?>
    setTimeout(
      function() 
      {

               $.ajax({
                   type: "post",
                   dataType: "json",
                   url: "<?php echo $this->adminUrl('send-message-portion', 'newsletter', array("id" => $this->message->getId())) ?>",
                   data: {format: "json", status: "status"},
                   success: function(resp) {
                       if(resp.status == "success") {
                            $("#progress-bar").html(resp.body);
                       }
                   }
               });

      }, 3000);
     <?php endif; ?>

});

</script>

<div id="progress-bar"> 
               
    <?php echo $this->counter; ?>
    
     <div class="span8">
                            <div class="page-header">
                                <h4>Progress</h4>
                            </div>
                            <div class="vital-stats">
                                <ul class="unstyled">

                                    <li>
                                        <span class="icon24 icomoon-icon-arrow-up-2 green"></span> <?php echo $this->percent; ?>%
                                        <span class="pull-right strong"><?php echo $this->allMessagesToSentCounter; ?></span>
                                        <div class="progress progress-success progress-striped ">
                                            <div class="bar" style="width: <?php echo $this->percent; ?>%;"></div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    
</div>
 
