<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('product_category', 'product_category_metatag_id_default_metatag_id');
        $this->dropForeignKey('product_producer', 'product_producer_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_producer', 'product_producer_metatag_id_default_metatag_id');
        $this->dropForeignKey('product_product', 'product_product_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_product', 'product_product_metatag_id_default_metatag_id');
        $this->createForeignKey('product_category', 'product_category_discount_id_product_discount_id', array(
             'name' => 'product_category_discount_id_product_discount_id',
             'local' => 'discount_id',
             'foreign' => 'id',
             'foreignTable' => 'product_discount',
             ));
        $this->addIndex('product_category', 'product_category_discount_id', array(
             'fields' => 
             array(
              0 => 'discount_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('product_category', 'product_category_metatag_id_default_metatag_id', array(
             'name' => 'product_category_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('product_producer', 'product_producer_photo_root_id_media_photo_id', array(
             'name' => 'product_producer_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_producer', 'product_producer_metatag_id_default_metatag_id', array(
             'name' => 'product_producer_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('product_product', 'product_product_photo_root_id_media_photo_id', array(
             'name' => 'product_product_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_product', 'product_product_metatag_id_default_metatag_id', array(
             'name' => 'product_product_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->dropForeignKey('product_category', 'product_category_discount_id_product_discount_id');
        $this->removeIndex('product_category', 'product_category_discount_id', array(
             'fields' => 
             array(
              0 => 'discount_id',
             ),
             ));
    }
}