<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product_category', 'discount_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product_category', 'discount_id');
    }
}