<script type="text/javascript">
$(document).ready(function(){
    
    String.prototype.startsWith = function(str) 
    {return (this.match("^"+str)==str)}

    $('#target_href').on('blur',function(){
      
      var val = '';
                
     // jeżeli nie zaczyna się od http to dodajemy http
     if($(this).val().match(/^(?:http:\/\/)/)||$(this).val().match(/^(?:https:\/\/)/))
          val = $(this).val();
      else
          val = "http://" + $(this).val();
            
            // dla youtube zamieniamy znacznik watch?=v na embed
      if(val.indexOf("/watch?") >= 0){
          val = val.replace('/watch\?v=', '/embed/');
      }
          
      if(val.indexOf("vimeo") >= 0 && val.indexOf("player") < 0){
          var index = val.lastIndexOf("/");
          var res = val.substring(index+1, val.length);
          val = 'http://player.vimeo.com/video/'+res;
      }    
          
       $('#videoPreview').attr('src',val); 
       $(this).val(val);
       
    });
});
</script>
<div class="row-fluid">
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add layer') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                     <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <?php echo $this->form->class ?>
                        <?php echo $this->form->animation ?>
                        <?php echo $this->form->easing ?>
                        <?php echo $this->form->speed ?>
                        <?php echo $this->form->start ?>
                        <?php echo $this->form->x_position ?>
                        <?php echo $this->form->y_position ?>
                        <?php echo $this->form->target_href ?>
                        <iframe id="videoPreview" width="420" height="315" frameborder="0" allowfullscreen></iframe>
                        <?php echo $this->form->width_iframe ?>
                        <?php echo $this->form->height_iframe ?>
                         
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('edit-slide', 'slider', array('slider' => $this->slide->getSliderId(), 'id' => $this->slide->getId())) ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            
        </div>
        
</div>