<script type="text/javascript">
$(document).ready(function() {
    $("#add_slide").click(function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-article-photo', 'news') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-article-photo', 'news') ?>/id/"+$('#id').val(),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                }
            }
        });
    });
    
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('New slide') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
                    
                    <?php echo $this->form->id ?>
                    <?php echo $this->form->title ?>
                    <?php echo $this->form->description ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-page', 'page') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
                
                <div id="itemContainer">
                    <ul id="slide_container" class="galleryView center">
                        <?php foreach($this->slider->get('Slides') as $slide): ?>
                        <li class="pull-left">
                            <?php if($slide->get('PhotoRoot')->getOffset()): ?>
                            <a id="main_photo" href="/media/photos/<?php echo $slide->get('PhotoRoot')->getOffset() ?>/<?php echo $slide->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $slide->get('PhotoRoot')->getTitle() ?>">
                                <img src="/media/photos/<?php echo $slide->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $slide->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $slide->get('PhotoRoot')->getOffset() ?>/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->article->get('PhotoRoot')->getTitle() ?>">
                            </a>
                            <?php else: ?>
                            <a id="main_photo" href="/images/gallery/1.jpg" rel="prettyPhoto" title="<?php echo $this->translate('No photo') ?>">
                                <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
                            </a>
                            <?php endif; ?>
                            <div class="actionBtn">
                                <a href="<?php echo $this->adminUrl('edit-article-photo', 'news', array('article-id' => $slide->getId(), 'id' => $slide->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                            </div>
                        </li>
                        <?php endforeach; ?>
                        <?php /*
                        <li class="pull-left">
                            <?php if($this->article->get('PhotoRoot')->getOffset()): ?>
                            <a id="main_photo" href="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->article->get('PhotoRoot')->getTitle() ?>">
                                <img src="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->article->get('PhotoRoot')->getTitle() ?>">
                            </a>
                            <?php else: ?>
                            <a id="main_photo" href="/images/gallery/1.jpg" rel="prettyPhoto" title="<?php echo $this->translate('No photo') ?>">
                                <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
                            </a>
                            <?php endif; ?>
                            <div class="actionBtn">
                                <a href="<?php echo $this->adminUrl('edit-article-photo', 'news', array('article-id' => $this->article->getId(), 'id' => $this->article->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                            </div>
                        </li>
                        */ ?>
                    </ul>
                </div>
            
            </div>
            
        </div>
        
    </div>


</div>

        
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
    