<div class="row-fluid">
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add layer') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                     <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <?php echo $this->form->animation ?>
                        <?php echo $this->form->easing ?>
                        <?php echo $this->form->speed ?>
                        <?php echo $this->form->start ?>
                        <?php echo $this->form->x_position ?>
                        <?php echo $this->form->y_position ?>
                        <?php echo $this->form->target_href ?>
                         
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('edit-slide', 'slider', array('slider' => $this->slide->getSliderId(), 'id' => $this->slide->getId())) ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            
        </div>
        
</div>