<script type="text/javascript">
$(document).ready(function() { 
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
    
    $("#itemContainer").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-slide-layer-image-photo', 'slider') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-slide-layer-image-photo', 'slider') ?>/id/"+$('#id').val(),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                    $("#itemContainer").trigger('update');
                }
            }
        });
    });
});
</script>
<div class="row-fluid">
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add layer') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                     <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <?php echo $this->form->id ?>
                        <?php echo $this->form->animation ?>
                        <?php echo $this->form->easing ?>
                        <?php echo $this->form->speed ?>
                        <?php echo $this->form->start ?>
                        <?php echo $this->form->x_position ?>
                        <?php echo $this->form->y_position ?>
                        <?php echo $this->form->target_href ?>
                         
                         <div id="itemContainer">
                            <ul id="main_photo_container" class="galleryView center">
                                <li class="pull-left">
                                    <?php if($this->slideLayer->get('PhotoRoot')->getOffset()): ?>
                                    <a id="main_photo" href="/media/photos/<?php echo $this->slideLayer->get('PhotoRoot')->getOffset() ?>/<?php echo $this->slideLayer->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->slideLayer->get('PhotoRoot')->getTitle() ?>">
                                        <img src="/media/photos/<?php echo $this->slideLayer->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->slideLayer->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->slideLayer->get('PhotoRoot')->getOffset() ?>/<?php echo $this->slideLayer->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->slideLayer->get('PhotoRoot')->getTitle() ?>">
                                    </a>
                                    <?php else: ?>
                                    <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                        <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                    </a>
                                    <?php endif; ?>
                                    <div class="actionBtn">
                                        <a href="<?php echo $this->adminUrl('edit-slide-layer-image-photo', 'slider', array('slide-layer-id' => $this->slideLayer->getId(), 'id' => $this->slideLayer->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                        <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                        <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                         
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('edit-slide', 'slider', array('slider' => $this->slide->getSliderId(), 'id' => $this->slide->getId())) ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            
        </div>
        
</div>
<div id="explorer" class="dialog"><div id="elfinder"></div></div>