<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><!--[if IE 7 ]>    <html class="ie7 oldie" lang="pl"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8 oldie" lang="pl"> <![endif]-->
<!--[if IE ]>    <html class="ie" lang="pl"> <![endif]-->
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <style media="screen" type="text/css">
            .text{
                color: black;
            }
        </style>
    </head>
    <body>
        <div style="border: 1px solid #B8B8B6; width: 800px; margin: 0 auto; border-radius: 5px; padding: 10px;">
  
            <?php echo $this->message->getContent(); ?>
            <table width="800px" style="margin-left: auto; margin-right: auto;"> 
                <tr>
                    <td style="color: #958f8a; font-size: 12px; text-align:justify; text-justify:inter-word;">
                        Otrzymaliście Państwo tę wiadomość, ponieważ jesteście 
                        subskrybentami serwisu calvarianum.pl. Jeżeli nie chcecie otrzymywać 
                        podobnych informacji, proszę kliknąć na link. 
                        <a href="<?php echo $this->url(array('token' => $this->token), 'domain-i18n:subscriber-sign-out') ?>">
                            Wypisz się 
                        </a>
                    </td>
                </tr>
            </table>
        </div>

    </body>
</html>