<?php

/**
 * Slider_Model_Doctrine_BaseSlider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property integer $slide_root_id
 * @property Doctrine_Collection $Slides
 * @property Slider_Model_Doctrine_Slide $SlideRoot
 * 
 * @package    Admi
 * @subpackage Slider
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Slider_Model_Doctrine_BaseSlider extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('slider_slider');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('slide_root_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Slider_Model_Doctrine_Slide as Slides', array(
             'local' => 'slide_root_id',
             'foreign' => 'root_id'));

        $this->hasOne('Slider_Model_Doctrine_Slide as SlideRoot', array(
             'local' => 'slide_root_id',
             'foreign' => 'id'));
    }
}