<?php

/**
 * Slider_Model_Doctrine_BaseSlideLayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $slide_id
 * @property string $type
 * @property string $text_html
 * @property string $animation
 * @property string $easing
 * @property integer $speed
 * @property string $target_href
 * @property integer $x_position
 * @property integer $y_position
 * @property integer $start
 * @property string $class
 * @property integer $width_iframe
 * @property integer $height_iframe
 * @property integer $photo_root_id
 * @property Slider_Model_Doctrine_Slide $Slide
 * 
 * @package    Admi
 * @subpackage Slider
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Slider_Model_Doctrine_BaseSlideLayer extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('slider_slide_layer');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('slide_id', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('type', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('text_html', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('animation', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('easing', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('speed', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('target_href', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('x_position', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('y_position', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('start', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('class', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('width_iframe', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('height_iframe', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('photo_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Slider_Model_Doctrine_Slide as Slide', array(
             'local' => 'slide_id',
             'foreign' => 'id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($nestedset0);
    }
}