<?php

/**
 * Slider_Model_Doctrine_SlideLayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Slider
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Slider_Model_Doctrine_SlideLayer extends Slider_Model_Doctrine_BaseSlideLayer
{
    public static $slideLayerPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '' => 'Thumb'
    );

    public static function getSlideLayerPhotoDimensions() {
        return self::$slideLayerPhotoDimensions;
    }
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getSlideId() {
        return $this->_get('slide_id');
    }
    
    public function setUp() {
        parent::setUp();
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
    }
}