<script type="text/javascript">
$(document).ready(function(){
    
    $("#user_id").select2();
});
</script>
<div class="container_12 clearfix leading">
    
    <div class="row-fluid">

        <div class="span12">

            <div class="box">
                <?php if($this->form->isErrors()): ?>
                    <div class="message error closeable">
                        <span class="message-close"></span>
                        <h3><?php echo $this->translate('Error') ?>!</h3>
                    </div>
                <?php endif; ?>
                <?php if($this->messages()->count()): ?>
                    <?php echo $this->messages()->render() ?>
                <?php endif; ?>
                
                <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Add group') ?></span>
                </h4>
                
                </div>

                <div class="content">
                    <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
                        <?php foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        } ?>
                        
                               <div class="page-header">
                            <h4><?php echo $this->translate('Translations') ?></h4>
                        </div>
                        
                        <ul id="myTab" class="nav nav-tabs pattern">
                            <li class="dropdown">
                                <?php foreach($this->languages as $key => $language): ?>
                                <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                                <?php endforeach; ?>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->name ?>
                                <?php echo $this->form->translations->getSubForm($language)->description ?>
                            <?php endif; ?>

                            </div>
                            <?php endforeach; ?>
                        </div>

                        <?php echo $this->form->user_id->setAttribs(array('class' => 'nostyle')) ?>
                        <?php echo $this->form->discount_id->setAttribs(array('class' => 'nostyle')) ?>
                        
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('list-group-client', 'user'); ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>  
                    </form>
                </div>

            </div><!-- End .box -->

        </div><!-- End .span12 -->
    
</div>