<script type="text/javascript">
$(document).ready(function(){
    
    $("#save-button").click(function(e) {
        e.preventDefault();

        $("#form").append("<input type='hidden' name='saveOnly' value='1' />");
        $("#form #submit").trigger("click");
    });
    
});
</script>
<h1 class="page-title"><?php echo $this->translate('Edit user') ?></h1>
<div class="container_12 clearfix leading">
    <div class="grid_12">

        <?php if($this->form->isErrors()): ?>
        <div class="message error closeable">
                <span class="message-close"></span>
                <h3><?php echo $this->translate('Error') ?>!</h3>
        </div>
        <?php endif; ?>
        
        <?php if($this->messages()->count()): ?>
        <?php echo $this->messages()->render() ?>
        <?php endif; ?>
       

        <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

            <?php
            foreach($this->form->getElements() as $element) {
                if($element->hasErrors()) {
                    $element->setAttrib('class', 'error');
                }
            }
            ?>

            <?php echo $this->form->first_name ?>
            <?php echo $this->form->last_name ?>
            <?php echo $this->form->username ?>
            <?php echo $this->form->email ?>
            <?php echo $this->form->role ?>
            <?php echo $this->form->active ?>
            <?php echo $this->form->id ?>
            
            <div class="form-action clrearfix">
                <?php echo $this->form->submit ?>
                <?php echo $this->formButton('', $this->translate('Save'), array('id' => 'save-button', 'type' => 'button')) ?>
                <a href="<?php echo $this->adminUrl('list-user', 'user') ?>"><?php echo $this->formButton('', $this->translate('Cancel'), array('id' => 'cancel-button')) ?></a>
            </div>
            
        </form>
    </div>
</div>