<script type="text/javascript">
    $(document).ready(function() {
        $("#wrapper").undelegate("#edit-user-account", "click").delegate("#edit-user-account", "click", function(e) {
            e.preventDefault();

            var url = "<?php echo $this->adminUrl('edit-user-account', 'user') ?>";
            var id = url.replace(/[\/\.]/g,"-");

            $.ajax({
                type : "get",
                url : url,
                dataType : "html",
                success : function(resp, qXHR, textStatus) {
                    pageDownloaded(resp, id);
                }
            });
        });
    });
</script>
<h1 class="page-title"><?php echo $this->translate('User account') ?></h1>
<div class="container_12 clearfix leading">
    <?php echo $this->formButton('', $this->translate('Edit user account'), array('id' => 'edit-user-account')) ?>
    
    <?php if($this->messages()->count()): ?>
    <?php echo $this->messages()->render() ?>
    <?php endif; ?>
    
    <section class="portlet grid_12 leading">
        <header>
            <h2><?php echo $this->translate('Settings') ?></h2>
        </header>
        <section class="items">
            <table class="full">
                <tbody>
                    <tr>
                        <td><?php echo $this->translate('First name') ?></td>
                        <td class="ar"><?php echo $this->user->getFirstName() ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('Last name') ?></td>
                        <td class="ar"><?php echo $this->user->getLastName() ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('email') ?></td>
                        <td class="ar"><?php echo $this->user->getEmail() ?></td>
                    </tr>
                </tbody>
            </table>
        </section>
    </section>
</div>