<div class="loginContainer">
    <form class="form-horizontal" action="<?php echo $this->url(array(), 'domain-login') ?>" id="loginForm" method="post" >
        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <label class="form-label span12" for="username">
                        <?php echo $this->translate('Email') ?>:
                        <span class="icon16 icomoon-icon-user-3 right gray marginR10"></span>
                    </label>
                    <?php echo $this->loginForm->username->setDecorators(array('ViewHelper'))->setAttribs(array('class' => 'span12', 'required' => 'required', 'placeholder' => $this->translate('E-mail'))) ?>
                </div>
            </div>
        </div>

        <div class="form-row row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <label class="form-label span12" for="password">
                        <?php echo $this->translate('Password') ?>:
                        <span class="icon16 icomoon-icon-locked right gray marginR10"></span>
                        <span class="forgot"><a href="<?php echo $this->url(array('context' => 'admin'), 'domain-recover-password') ?>"><?php echo $this->translate('Forgot password?') ?></a></span>
                    </label>
                    <?php echo $this->loginForm->password->setDecorators(array('ViewHelper'))->setAttribs(array('class' => 'span12', 'required' => true, 'placeholder' => $this->translate('Password'))) ?>
                </div>
            </div>
        </div>
        <div class="form-row row-fluid">                       
            <div class="span12">
                <div class="row-fluid">
                    <div class="form-actions">
                    <div class="span12 controls">
                        <?php echo $this->loginForm->remember->setDecorators(array('ViewHelper'))->setAttribs(array('class' => 'styled')) ?> <?php echo $this->translate('Keep me logged in') ?>
                        <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> <?php echo $this->translate('Log in') ?></button>
                    </div>
                    </div>
                </div>
            </div> 
        </div>

    </form>
</div>