<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('banner_banner', 'banner_banner_photo_root_id_media_photo_id');
    }

    public function down()
    {
        $this->createForeignKey('banner_banner', 'banner_banner_photo_root_id_media_photo_id', array(
             'name' => 'banner_banner_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
    }
}