<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('banner_banner', 'user_id');
        $this->addColumn('banner_banner', 'description', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('banner_banner', 'user_id', 'integer', '4', array(
             ));
        $this->removeColumn('banner_banner', 'description');
    }
}