<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('banner_banner', 'views', 'integer', '4', array(
             'default' => '0',
             ));
        $this->changeColumn('banner_banner', 'clicks', 'integer', '4', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}